### PR TITLE
Add shortcuts for levels and config

### PR DESCRIPTION
**Pull request by carusogabriel**
Following https://github.com/Symplify/Symplify/pull/705.

IMHO we should add this, to give the user all possible options to run their commands :)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could you also verify they work? They're both related to Config resolver in bin file

**Comment by carusogabriel** [comment]
@TomasVotruba Looks like https://github.com/Symplify/Symplify/blob/master/packages/PackageBuilder/src/Configuration/LevelConfigShortcutFinder.php will need to be changed as well :smile:

**Comment by carusogabriel** [comment]
@TomasVotruba Should we wait to require the next version of Symplify or is RTM?

**Comment by TomasVotruba** [comment]
Merge would break the use actually. I'd wait for the stable release, since there is already enough troubles with other dev dependencies

**Comment by TomasVotruba** [comment]
ECS 4 is behind the corner, so this can be merged

**Pull request merged**
