### PR TITLE
[CI] Downgrade Rector to PHP 7.1 + prefix it

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes https://github.com/rectorphp/rector/issues/5472

---

The former bash script is extremely complicated and hard to debug. After static reflection something broke and it's impossible to find out where and what. Each vendor package has it's on matrix of configs, so there is probbaly around 100-200 small little jobs that are being run inside the bash script. 

We need simple approach as Rectror CI has - one run, one dir. That way we can see what file broke on which rule, and ale to fix it.

This is attempt to make it KISS again :slightly_smiling_face: 

## Acceptance Criteria

- [x] single build with scoping + PHP 7.1 downgraded job passing
- [ ] https://github.com/rectorphp/rector-prefixed running on PHP 7.1

### CODE REVIEW

**Comment by leoloso** [comment]
Since I built the script, I'll be happy to help you clarify how/why I did anything, if you need to. Just let me know.

Btw, I later on simplified the downgrade script for my own repo (check [here](https://github.com/leoloso/PoP/blob/master/layers/Engine/packages/root/ci/downgrade_code.sh)). So if you need to understand what it does, checking there might be easier.

**Comment by TomasVotruba** [comment]
Thanks! I get the idea, just need 1 config-approach for Rector, so we can maintain it easily.

**Comment by TomasVotruba** [comment]
Closes https://github.com/rectorphp/rector/issues/5472

**Comment by TomasVotruba** [comment]
Looking good :eyes:

**Comment by TomasVotruba** [comment]
Few bugs on PHP 7.1

image

image

**Comment by TomasVotruba** [comment]
There is an issue with covariance, here the `string` must be completed:

image

**Comment by TomasVotruba** [comment]
Surpassed by https://github.com/rectorphp/rector/pull/5880

**Pull request closed without merging**
