### PR TITLE
[Performance] Add CountArrayToEmptyArrayComparisonRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it is functional for non-yoda condition. The following :

```php
count($array) === 0;
count($array) > 0;
```

is replaced with: 

```php
$array === [];
$array !== [];
```

**Comment by samsonasik** [comment]
implemented yoda condition for identical comparison

**Comment by samsonasik** [comment]
implemented yoda condition for greater/smaller comparison

**Comment by samsonasik** [comment]
@TomasVotruba still need close-reopen to start ci for auto-commit " [ci-review] Rector Rectify "

**Comment by samsonasik** [comment]
All checks have passed :tada: @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I've added handling passed arg to count is a method call

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
The passed parameter is now allow any Expr instance as far as its type is an ArrayType.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I've added handling `count($var)` mark as truthy inside if cond like below:

```diff
        $data = [];

-        if (count($data)) {
+        if ($data !== []) {
        
         }
```

**Comment by samsonasik** [comment]
I've added handling `count($var)` mark as truthy inside elseif cond like below:

```diff
         $otherData = [];

-        elseif (count($otherData)) {
+        elseif ($otherData !== []) {
        
         }
```

**Comment by samsonasik** [comment]
I've added handling `count($var)` mark as truthy inside while cond like below:

```diff
         $data = [];

-        while (count($data)) {
+        while ($data !== []) {
        
         }
```

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I skipped mark truthy in while statement as inside it, the var can be re-assigned to countable which make it false positive and infinite loop.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I've added handling truthy negation like `! count($var)` like below:

```diff
        $data = [];
-        ! count($data);
+        $data === [];
```

**Comment by samsonasik** [comment]
I've added handling truthy negation inside if/elseif statement like `if (! count($var)) {}` like below:

```diff
         $data = [];
-        if (! count($data)) {
+        if ($data === []) {

         }
```

**Comment by samsonasik** [comment]
All checks have passed 🎉 🎉 🎉  I think it already handled most of use cases 🎉 🎉 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
I'll look into it now

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1: 


Could you add it to `CODE_QUALITY_STRICT` in next PR? And add this set to `rector-ci`?

That will help us discover more edge case

**Comment by samsonasik** [comment]
I will try.

**Pull request merged**
