### PR TITLE
Another attempt to add Compiler + upgrade to PHPStan 0.12

### LINKED ISSUE #2385: Doesn't work with phpstan 0.12
A new version of phpstan has been published and rector doesn't work with it.

### PR DESCRIPTION
**Pull request by TomasVotruba**
- Reference #177 - still needs lot of testing in the wild
- Closes #2385 

### Inspiration

- https://github.com/phpstan/phpstan-src/commit/339819882edeccf87db133b6856b9f4c707c5489

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Current error

- https://github.com/symfony/symfony/blob/c62bb82e27974ef4e389da523f0de451b6632266/src/Symfony/Component/Finder/Finder.php#L589

Might be related

- https://github.com/symfony/symfony/commit/b61c8fcb77282f480941026fabcbc112b8a7f50e

**Comment by TomasVotruba** [comment]
This is the place where file is called as a glob:
https://github.com/symfony/symfony/blob/c62bb82e27974ef4e389da523f0de451b6632266/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php#L162

**Comment by TomasVotruba** [comment]
Fuckup post is comming :D

**Comment by gnutix** [comment]
Hey @TomasVotruba ! Just discovered this PR, awesome work! :D Is it already testable somehow ? I've `cd ~/dev/oss/rector && git fetch && git checkout compiler && cd compiler && bin/compile`, which gave me `tmp/rector.phar`.

Now when I `cd` into our project and run `php ~/dev/oss/rector/tmp/rector.phar`, it gives : 

```
PHP Fatal error:  Uncaught _HumbugBox24440d0b0be5\Nette\FileNotFoundException: File '/composer/vendor/phpstan/phpstan-symfony/extension.neon' is missing or is not readable. in phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/Config/Loader.php:29
Stack trace:
#0 phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/Config/Loader.php(43): _HumbugBox24440d0b0be5\Nette\DI\Config\Loader->load('/composer/vendo...', false)
#1 phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/Compiler.php(98): _HumbugBox24440d0b0be5\Nette\DI\Config\Loader->load('/home/gnutix/de...', false)
#2 phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(186): _HumbugBox24440d0b0be5\Nette\DI\Compiler->loadConfig('/home/gnutix/de...', Object(_HumbugBox24440d0b0be5\Nette\DI\Config\Loader))
#3 phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/ContainerLoader.php(101): _HumbugBox24440d0b0be5\Nette\Configurator->generateCon in phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/Config/Loader.php on line 29

Fatal error: Uncaught _HumbugBox24440d0b0be5\Nette\FileNotFoundException: File '/composer/vendor/phpstan/phpstan-symfony/extension.neon' is missing or is not readable. in phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/Config/Loader.php:29
Stack trace:
#0 phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/Config/Loader.php(43): _HumbugBox24440d0b0be5\Nette\DI\Config\Loader->load('/composer/vendo...', false)
#1 phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/Compiler.php(98): _HumbugBox24440d0b0be5\Nette\DI\Config\Loader->load('/home/gnutix/de...', false)
#2 phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(186): _HumbugBox24440d0b0be5\Nette\DI\Compiler->loadConfig('/home/gnutix/de...', Object(_HumbugBox24440d0b0be5\Nette\DI\Config\Loader))
#3 phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/ContainerLoader.php(101): _HumbugBox24440d0b0be5\Nette\Configurator->generateCon in phar:///home/gnutix/dev/oss/rector/tmp/rector.phar/vendor/nette/di/src/DI/Config/Loader.php on line 29
```

Am I misusing it ? Or is it a bug ? ^^

**Comment by TomasVotruba** [comment]
Check Travis job, there is steps to test it.
I know it fails on autoloader, but your issue should be fixed

**Comment by gnutix** [comment]
I'm not really sure what you mean I'm supposed to look at inside `.travis.yml` : it contains tons of stuff, I'm a bit lost. What do you mean by "your issue should be fixed" ? (I'm using the latest `compiler` branch version... is there another, more up-to-date ? This branch hasn't been merged yet, right ?)

**Comment by escopecz** [comment]
@gnutix check these lines: https://github.com/rectorphp/rector/pull/2373/files#diff-354f30a63fb0907d4ad57269548329e3R39-R49

To sum them up, the phar is being built automatically and the result is in the https://github.com/rectorphp/rector-prefixed repo. However, there are still issues with the final phar as Tomas noted.

**Comment by gnutix** [comment]
Thanks @escopecz. I've downloaded the .phar from `rectorphp/rector-prefixed`, same error because of PHPStan's extension within the Docker image. Should I create a separate issue about this ?

**Comment by escopecz** [comment]
That's odd. I'm getting `".phar://rector.phar/vendor/autoload.php", "phar://rector.phar/../../../vendor/autoload.phpHave you ran "composer update"?` when I run that. Anyway, I don't think it makes sense to create new issues about features that haven't been merged to the core yet. Let's just help Tomas to get it working.

**Comment by TomasVotruba** [comment]
@gnutix These lines are used to build phar:

https://github.com/rectorphp/rector/pull/2373/files#diff-354f30a63fb0907d4ad57269548329e3R27-R31

**Comment by TomasVotruba** [comment]
Still not 100 % stable, but good enought to :ship:  it and test it in the wil.
Let's roll :+1:

**Comment by mpdude** [comment]
This may be a stupid question... but where can I find the off-the-shelf `.phar` version? 

There is no hint in the README, neither here nor over at https://github.com/rectorphp/rector-prefixed, they don't even contain `.phar`. I also checked the GitHub "Releases" in both repos and found nothing.

Since the `.phar` build (at least, in this PR) was set up for Travis, and since the project seems to use GHA now... maybe it was just lost?

**Comment by mpdude** [comment]
Ah, the answer lies in e7f1963d672c82d9beeca8988b35e36a12740be2... 

@TomasVotruba do you recall why you stopped building the .phar version?

IMO, having a .phar is the most simple and elegant solution for using a tool like Rector, since you have no interference with your project's dependencies, and grabbing a file and running it is all it takes to try a new tool.

**Comment by TomasVotruba** [comment]
Here is the release info about moving from PHAR to scoped code:
https://getrector.org/blog/2020/12/28/rector-09-released

It's important stepping stone to downgradable releases, that are easy to use and debug.

That way it will be possible

**Comment by mpdude** [comment]
Debugging phar-specific issues (guess you ment that?) for sure isn’t fun. Symfony (Console?) cannot be packed into a phar – I’ll take your word for it.

I guess it boils down to the same questions as in #5593:

Is there a requirement that the (major?) version of PHP that runs Rector must match the version of PHP currently required by the project?

Is this by design/unavoidable, or just a current bug?

Can/does/should Rector treat project code as „data“ only, or does it have to parse/load/interpret it at the runtime interpreter/language level?

I am so persistent on these particular questions because it seems to me that has great impact on how much sense it makes to invest into Docker images: In a container, at best we can keep Rector and all its dependencies fully isolated from the project (after all, that’s what it is all about). The PHP version, available extensions etc. when running Rector will almost never be in line with what the project itself uses at runtime.

That‘s all not an issue if the container runs something that will happily parse PHP 5 up to PHP 8 code as input.

But if the version of Rector (and at least also PHPStan, even in the „scoped“ variant) must match project dependencies, it‘s going to be hard to make that work with Docker images... 👨🏻‍💻

Am I making sense?

**Comment by TomasVotruba** [comment]
Symfony can be packed into phar, but it's a road to hell: https://tomasvotruba.com/blog/2019/12/02/how-to-box-symfony-app-to-phar-without-killing-yourself/ + Also,`realpath()` in phar does not work.

As for project vs Rector dependencies, they can differ: https://getrector.org/blog/2020/01/20/how-to-install-rector-despite-composer-conflicts

**Comment by mpdude** [comment]
Sorry, I don't understand it...

You removed the PHAR:

> Here is the release Rector 0.9 info about moving from PHAR to scoped code: https://getrector.org/blog/2020/12/28/rector-09-released

... suggesting to use the scoped version and to install it using Composer, so that Composer can find versions compatible with the project's other requirements? 

And then, when I asked why/how/which dependencies and/or language versions need to be in sync between the project and Rector, you answer 

> they can differ: https://getrector.org/blog/2020/01/20/how-to-install-rector-despite-composer-conflicts

... pointing me to a blog post that, at the bottom, announces the `.phar` version. I am confused 😕.

**Comment by TomasVotruba** [comment]
> ... suggesting to use the scoped version and to install it using Composer, so that Composer can find versions compatible with the project's other requirements?

Yes. Use the rector-scoped

The second post is about phar, but that's because it's older. Take it as synonymum for rector-scoped

**Comment by glensc** [comment]
The third point in the blog:
- https://tomasvotruba.com/blog/2019/12/02/how-to-box-symfony-app-to-phar-without-killing-yourself/

it should start with the fact that you are committing the `.phar` to the repo, otherwise, it's confusing that you have the "spoiler" at the end of the paragraph, accidentally even mentioning a commit. 'we shipped' requires to have previous knowledge of your project and how you do the shipping.

**Comment by TomasVotruba** [comment]
Hi, thanks for your suggestion.

Could you edit the post content so it makes more sense?
https://github.com/tomasvotruba/tomasvotruba.com/edit/main/packages/blog/data/2019/2019-12-02-how-to-box-symfony-app-to-phar-without-killing-yourself.md

**Pull request merged**
