### PR TITLE
[Doc] Remove unused images assets and apply phpunit image in readme

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
For `PHPUnit` may refer to PhpSpecToPHPUnit  https://github.com/rectorphp/rector/tree/main/rules/PhpSpecToPHPUnit

**Comment by samsonasik** [comment]
Just checked that `PHPUnit` rules moved to https://github.com/rectorphp/rector-phpunit

**Comment by TomasVotruba** [comment]
Makes sense, thank you :+1:

**Comment by TomasVotruba** [comment]
Hi, I'm checking the README and design is broken:

image


It should be 2 lines only. Could you fix it?

**Comment by samsonasik** [comment]
Yes https://github.com/rectorphp/rector/pull/5946

**Pull request merged**
