### PR TITLE
Test PR 3

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba finally, it works 🎉 🎉 🎉

**Comment by TomasVotruba** [comment]
Woohoo, very nice! What was the trick?

**Comment by TomasVotruba** [comment]
Could you add this to Symplify repositories as well? We have now repository-lock-down package, but it does not work.

**Comment by samsonasik** [comment]
It uses https://github.com/superbrothers/close-pull-request . I will try.

**Comment by samsonasik** [comment]
@TomasVotruba implemented, PR https://github.com/symplify/symplify/pull/3226 demo https://github.com/symplify/static-detector/pull/2#issuecomment-845448452

**Pull request closed without merging**
