### PR TITLE
[CountOnNullRector] fix Rector applying on properties with phpdocs array

### LINKED ISSUE #2474: [PHP] CountOnNull on properties with PHPDoc shouldn't apply
I've had the case in my code base that the following code change was triggered : 

```diff
/** @var string[] $array */
$array = $someObject->someMethod();

- if (count($array) > 0) {
+ if (is_countable($array) ? count($array) > 0 : 0) {

}
```

I was quite surprised by this proposition, as IMO a `string[]` doesn't need to be surrounded by `is_countable` (if the developer is misusing type hints/doc blocks, PHPStan should warn him).

I digged into it and even noticed there's a test Fixture that seems to affirm this behavior : 

`packages/Php71/tests/Rector/FuncCall/CountOnNullRector/Fixture/property_with_doc.php.inc`

Isn't that weird ?

### PR DESCRIPTION
**Pull request by gnutix**
Fixes #2474.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Test case is needed in this PR so CI can verify it

**Comment by gnutix** [comment]
I couldn't reproduce it within your Fixtures. But I could in my playground repo : https://github.com/gnutix/rector-playground/pull/3 (test is currently failing, but if you merge this in master it will pass).

I can't do better than that (tried for hours already), sorry.

**Comment by TomasVotruba** [comment]
I see.

We should discover the point of origin, since it's probably cause of other related bugs.

**Comment by gnutix** [comment]
I checked the history of this condition I removed before doing the change, and it's not used anywhere else and the feature it was added for works the same (read: the related test still passes) without this condition.

So I'm not sure there's much potential consequences here.

**Comment by TomasVotruba** [comment]
> So I think there is not much risk of consequences to merge this (

I believe your testing, let's give it a try then.

**Pull request merged**
