### PR TITLE
[Mysql to Mysqli] Add mysql_error to mysqli_error with RenameFunctionRector in mysql-to-mysqli set

### LINKED ISSUE #6377: Incorrect behavior of RenameFunctionRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/e386bccf-7050-4fc3-a6c9-22dd33e38d43

I am not sure if MYSQL_TO_MYSQLI is supposed to replace all occurrences. Interestingly enough, the same function are replaced if I reduce the script to something different. It may be other but so far mysql_error is not replace 100% of the case, other depends on the context.

Btw, amazing work you have done here! A life changer :)

```php
<?php
session_start();

include '../../includes/connexion.php';
include '../../includes/fonctions.php';
include '../../files/verif_etablissement.php';
include '../../backoffice/files/mail_smbg.php';

$id_fiche = $_GET['id'];
$type = $_GET['type'];

if($type == 'rh') {
	$suffixe = '_rh';
} else {
	$suffixe = '';
}

$Array = explode('.', $_FILES['NomFichier']['name']);
$extension = strtolower(end($Array));

if($extension == 'xls' || $extension == 'xlsx') {
	$rq = "
		SELECT 
		abcd.c, 
		abcd.eded,
		abcd.nb_eleve
		FROM enquete_fiche
		INNER JOIN enquete_etablissement
		ON (abcd.etablissement = enquete_etablissement.id)
		INNER JOIN abcde
		ON (abcde.id_fiche = abcd.id_fiche AND abcde.annee = enquete_fiche.annee)
		WHERE abcd.id_fiche = '".$id_fiche."' 
		AND abcd.annee = '".date('Y')."'
	";

	$form_req = mysql_query($rq) or die(mysql_error());
	$row_formulaire = mysql_fetch_array($form_req);
  	$nb_eleve = (int) $row_formulaire['nb_eleve'];

	if($_FILES['NomFichier']['tmp_name'] != '') {
		$filename2 = $id_fiche.'.xls';
		move_uploaded_file($_FILES['NomFichier']['tmp_name'], $type.'/recu/'.$filename2);

    	if($type == 'etudiant') {
        	$lines_count = compter_lignes_excel($type.'/recu/'.$filename2);
		}

		// Envoi du mail BO
		$sql_texte = "
			SELECT a,b
			FROM foo
			WHERE type = 'a_" . $type . "_bo'
		";

		$que_texte = mysql_query($sql_texte) or die(mysql_error());
		$row_texte = mysql_fetch_array($que_texte);

		$sender = trim(post($_POST['email']));
		$receiver = 'a@example.com';
		$objet = utf8_encode(post($_POST['subject'])) . " ID formation : " . $id_fiche;
		$message = $row_texte['texte'];
		$to_replace = array('[message]');
		$replaced = array(nl2br(post($_POST['msg'])));
		mail_smbg($sender, $receiver, $objet, $message, $to_replace, $replaced, $type.'/recu/'.$filename2);

		// Envoi du mail de confirmation �cole
		$sql_texte = "SELECT a,b FROM table2 WHERE title = 't".$type."_avs'";
		$que_texte = mysql_query($sql_texte) or die ('Error: ' . mysql_error());
		$row_texte = mysql_fetch_array($que_texte);

		$sender = 'sender@example.com';
		$objet = $row_texte['objet'];
		$message = $row_texte['texte'];
		$to_replace = array('[nom_formation]');
		$replaced = array($row_formulaire['nom_formation']);
		mail_smbg($sender, $_POST['email'], utf8_encode($objet), $message, $to_replace, $replaced);

		$query = "
			UPDATE table1
			SET sent_file" . $suffixe . " = '1'
			WHERE id_file = " . $id_fiche . "
			AND yearSent = " . date('Y')
		;

		$req = mysql_query($query) or die('Errror ' . mysql_error());
		mysql_close();

		header("Location: confirm.php?type=".$type);
		exit;
	}
} else {
	$_SESSION['erreur'] = 'error';
	$redirection = "Location: other.php?id=".$id_fiche;

	header($redirection);
	exit;
}
```

### Responsible rules

* `RenameFunctionRector`

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #6377

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems it cause conflict with `MysqlQueryMysqlErrorWithLinkRector` with parameter connection.

**Comment by samsonasik** [comment]
So, `mysqli_error` has a required connection parameter, I think the `MysqlQueryMysqlErrorWithLinkRector` should be used instead of the mysql-to-mysqli set. Closing.

**Comment by pierrejoye** [comment]
Oh, thank you!

My apologize, I missed my self set ETA to provide the tests. Got quarantined messing up my time  :(

Keep the great work!

**Pull request closed without merging**
