### PR TITLE
[UPGRADE] Add Rector 0.9 upgrade docs

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref https://github.com/rectorphp/rector/issues/4905#issuecomment-746399661

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@Wirone Thanks for the input to make this +1

Could you check what else should be mentioned?

**Comment by Wirone** [comment]
Is it correct to have one `SKIP` option for rectors and paths? Rectors should be passed as keys (where value can be `null` or array of paths) where paths rather as values 🤔 I did not look at code, would it automatically check if key is integer and resolve it correctly? Even so, this is less readable than previous options...

**Comment by TomasVotruba** [comment]
> Is it correct to have one SKIP option for rectors and paths?

Yes, that's the goal.

It might be confusing at first, but in long term it saves 2 extra parameters.

```php
$parameters->set(Option::SKIP, [
    // path or rule?
    // be explicit!
]);

$parameters->set(Option::SKIP_PATH, [
    // path
]);

$parameters->set(Option::SKIP_RULE, [
    RuleRector::class
]);

// ← or maybe just a path? →

$parameters->set(Option::SKIP_RULE_AND_PATH, [
    RuleRector::class => [
       //
	],
]);
```

I explain the reasoning in a post:
https://tomasvotruba.com/blog/2020/12/10/new-in-symplify-9-skipper-skipping-files-and-rules-made-simple/

---

> would it automatically check if key is integer and resolve it correctly?

Yes!

**Comment by Wirone** [comment]
I've read blog post and must say that reasoning doesn't convince me. Tools have different parameters' naming and it's not a problem if there is proper documentation and/or IDE support. It can be schema for XML or options defined as constants like in Rector/ECS. You can't make a typo in such scenarios, just like in Symfony bundle with proper configuration definition - compiler will throw exception for unsupported option. Using the same parameter name for different purposes (excluding files from processing vs. limiting processing rules/scope) is IMHO violation of SRP in terms of configuration. As a user I prefer more small-scope options to tweak everything rather than multi-purpose, "magic" options. But this is only my subjective opinion, you can treat it as a friendly feedback :wink:

**Comment by TomasVotruba** [comment]
Thank you for feedback. I imagine change from quite ok options is hard and I wish I figured this earlier, before we introduced those options.

> You can't make a typo in such scenarios, just like in Symfony bundle with proper configuration definition - compiler will throw exception for unsupported option.

We had dozens of reported bugs just because of typos. In YAML times and even in PHP times. We live in cognitive overload world. Users don't have time to read docs carefuly step by step. I don't read docs untill I have a problem. 

The 3 options above were really confusing. Even for us. The goal of this feature is to "skip", whatever it is. Not to read docs about how this or that or that and this should be skipped. That's not Rector's domain. If we're a e.g. symfony\validator, that would be different :)

It also opens for future format like ECS or PHPStan has (`"#this is a message \d"`), without forcing users to memorize new keyword.

<br>

Despite different opinions. This is highly experimental feature, as there is no such component in PHP. If it goes wrong, we're ready to split it.

**Comment by nelson6e65** [comment]
Drop support for PHP 7.2 should be documented:

```
Problem 1
    - Root composer.json requires rector/rector ^0.9.15 -> satisfiable by rector/rector[0.9.15].
    - rector/rector 0.9.15 requires php ^7.3|^8.0 -> your php version (7.2.34) does not satisfy that requirement.
```

**Comment by TomasVotruba** [comment]
Be sure follow up our blog :) 
https://getrector.org/blog/2020/12/28/rector-09-released

**Comment by nelson6e65** [comment]
Hi. Sorry, I did not know about the blog. I use to check changes directly in repos 😅

Thanks for the link!

**Pull request merged**
