### PR TITLE
 [CodingStyle] Add %s for pass PHP_EOL constant on EncapsedStringsToSprintfRector 

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #5060

### CODE REVIEW

**Comment by samsonasik** [comment]
@brucealdridge I think this still needs improvement for multi `\n`, for example:

```php
return "prefix $format\n\n";
```

**Comment by samsonasik** [comment]
I skipped multiple eol.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
