### PR TITLE
Document import_short_classes + import_doc_blocks

### PR DESCRIPTION
**Pull request by gnutix**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you

**Comment by UFTimmy** [comment]
Sorry if this is a dumb question, but I don't see `import_doc_blocks` present anywhere in the code. It's not a constant on the Option class, and I don't see it mentioned anywhere else in my vendor files or on GitHub, aside from this commit.

Is this actually a feature? It's one I'd love.

**Comment by TomasVotruba** [comment]
It's autowired parameter, try camel case format search

**Comment by TomasVotruba** [comment]
See https://github.com/Symplify/AutoBindParameter

**Pull request merged**
