### PR TITLE
add FileDiff object over array

### PR DESCRIPTION
**Pull request by TomasVotruba**
@carusogabriel Could you review and merge if ok? Thank you

### CODE REVIEW

**Comment by carusogabriel** [comment]
@TomasVotruba Fails is a due new version of Symplify. I'll commit that separately

**Comment by TomasVotruba** [comment]
No problem, I'll handle it here

**Comment by carusogabriel** [comment]
@TomasVotruba Please rebased on top of https://github.com/rectorphp/rector/commit/ae7131819b149bde6a84356d23ef4c0d642d1129

**Comment by TomasVotruba** [comment]
Ok :+1:

**Comment by TomasVotruba** [comment]
Done :+1:

**Pull request merged**
