### PR TITLE
[NodeNameResolver] Set return false on node is MethodCall/StaticCall on NodeNameResolver::isName()

### LINKED ISSUE #5979: Rector\Core\Exception\ShouldNotHappenException : Name called on "PhpParser\Node\Expr\StaticCall" is not possible. Use $this->getName($node->name) instead
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

While running rector

```
In NodeNameResolver.php line 100:
                                                                                                            
  [Rector\Core\Exception\ShouldNotHappenException]                                                          
  Name called on "PhpParser\Node\Expr\StaticCall" is not possible. Use $this->getName($node->name) instead  
                                                                                                            
```
## Minimal PHP Code Causing Issue

```php
<?php

final class Carbon
{
    public $timestamp;

    public static function now()
    {
        return new static();
    }
}

class Demo
{
    public function getCurrentTimestamp()
    {
        return Carbon::now()->timestamp;
    }
}
```

### Responsible rules

* `CompleteDynamicPropertiesRector`

## Expected Behavior

Nothing needs to be changed

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5979

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by zingimmick** [comment]
Thank you! 👍

**Pull request merged**
