### PR TITLE
[Downgrade PHP 7.4]  Add DowngradeFreadFwriteFalsyToNegationRector

### LINKED ISSUE #4326: [Downgrade PHP 7.4] fread() and fwrite() function
# Feature Request

Downgrade from PHP 7.4 to 7.3.

From [here](https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.fread-fwrite):

<blockquote>
    <span class="function"><a href="https://www.php.net/manual/en/function.fread.php" class="function">fread()</a></span> and <span class="function"><a href="https://www.php.net/manual/en/function.fwrite.php" class="function">fwrite()</a></span> will now
    return <strong><code>FALSE</code></strong> if the operation failed.
    Previously an empty string or 0 was returned.
    EAGAIN/EWOULDBLOCK are not considered failures.
   </blockquote>
 
## Diff 

This diff or something like this, double check:

```diff
-if(fread($handle, $length) === false)
+if(!fread($handle, $length))
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #4326

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
@leoloso Could you review this? I'm not familiar with the issue. Thank you

**Review by leoloso — APPROVED** [review]
Looks good to me

**Comment by TomasVotruba** [comment]
@leoloso Thank you for review :+1: 

@samsonasik Thanks :+1:

**Pull request merged**
