### PR TITLE
[Privatization] Skip PrivatizeLocalOnlyMethodRector on use Symfony Route Attribute 

### LINKED ISSUE #5724: Incorrect behavior of PrivatizeLocalOnlyMethodRector: Symfony Route with PHP 8 Attributes
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/cfcba653-8f4b-4fcb-9163-22293a12a43d

```php
<?php
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/')]
final class FrontController
{
    #[Route(path: '', name: 'homepage')]
    public function homeAction() : Response
    {
    }
}
```

### Responsible rules

* `PrivatizeLocalOnlyMethodRector`

## Expected Behavior

See #5670 and #5671.

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #5725 Fixes #5724

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba I am not sure why it cause another test error:

```bash
1) Rector\SymfonyCodeQuality\Tests\Rector\Attribute\ExtractAttributeRouteNameConstantsRector\ExtractAttributeRouteNameConstantsRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...), 'src/ValueObject/Routing/RouteName.php', '/home/runner/work/rector/rect...le.php')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
     /**\n
      * @var string\n
      */\n
+    public const HOMEPAGE = 'homepage';\n
+    /**\n
+     * @var string\n
+     */\n
     public const NAME = 'name';\n
     /**\n
      * @var string\n
```
as it working fine locally:

Screen Shot 2021-03-03 at 10 45 56

**Comment by samsonasik** [comment]
It is very strange, it Github action under PHP 8, it keep getting error even with very unique routing definition:

```bash
 1) Rector\SymfonyCodeQuality\Tests\Rector\Attribute\ExtractAttributeRouteNameConstantsRector\ExtractAttributeRouteNameConstantsRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...), 'src/ValueObject/Routing/RouteName.php', '/home/runner/work/rector/rect...le.php')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
     /**\n
      * @var string\n
      */\n
+    public const ASYMFONYPAGEEXAMPLEROUTING = 'asymfonypageexamplerouting';\n
+    /**\n
+     * @var string\n
+     */\n
     public const NAME = 'name';\n
```

**Comment by samsonasik** [comment]
load service with `provideConfigFilePath()` seems fixed it 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
