### PR TITLE
[Php71] Add failing test case for CountOnNullRector

### PR DESCRIPTION
**Pull request by gnutix**
Managed to create a failing test for https://github.com/rectorphp/rector/issues/2474

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could you look at fix while at it?

**Comment by TomasVotruba** [comment]
This one is more tricky then it meets the eye

**Comment by gnutix** [comment]
Seemed tricky indeed, as the local variable test passes but not the "remote" (reference?) one.

**Comment by TomasVotruba** [comment]
Not sure what you mean. Could you send test case?

**Comment by gnutix** [comment]
Forget it, I hadn't seen yet that you had already made a PR to fix it :) I'll try it out next week. Thanks!

**Comment by TomasVotruba** [comment]
Ah :)

**Pull request merged**
