### PR TITLE
DocBlockManipulator empty spaces fix

### PR DESCRIPTION
**Pull request by JanMikes**
Please see #1434 for more info

### CODE REVIEW

**Comment by JanMikes** [comment]
Run tests please if you have any idea how to fix

**Comment by TomasVotruba** [comment]
You need to remove WIP to make Travis pass.

Personally I'd use the WIP only to prevent review, not to ask for it.

**Comment by TomasVotruba** [comment]
Could you trigger travis? Still no errors

**Comment by JanMikes** [comment]
I have no idea how to force it - i tried it even before but all travis says is: `Queued 8 days ago` but still no tests run

**Comment by TomasVotruba** [comment]
Just repush

**Comment by TomasVotruba** [comment]
Closing as answered in the issue

**Pull request closed without merging**
