### PR TITLE
add first OXID rector

### PR DESCRIPTION
**Pull request by alfredbez**
We created this initially in https://github.com/OXID-eSales/oxideshop_ce/pull/758, but I think this is useful for module developers as well. We plan to create a few other rectors in the future.

### CODE REVIEW

**Comment by alfredbez** [comment]
Ah, I just saw https://github.com/rectorphp/rector/commit/bb460b2eb351a997eeac5b1e913f9749970a9a37#diff-bdab44e68ad19f0f21d3a9f8a259f9ad I'll remove the second commit then.

**Comment by TomasVotruba** [comment]
Great move! I hope you add more rules in the future

In response I made a rule that should have been created ages ago...

Now all you need to do (submit in this PR) is:

```yaml
# config/set/oxid/oxid60.yaml
services:
    Rector\Renaming\Rector\FuncCall\RenameFuncCallToStaticCallRector:
        $functionsToStaticCalls:
            getStr: ['OxidEsales\Eshop\Core\Str', 'getStr']
```

**Comment by alfredbez** [comment]
Awesome work, thanks a lot :tada: 

I've rebased and force pushed that again.

**Comment by TomasVotruba** [comment]
Thank you for first rule in the set!

**Pull request merged**
