### PR TITLE
Moved dependencies in composer.json to allow run without dev deps

### LINKED ISSUE #2185: error docker run: Nette\FileNotFoundException missing config.neon
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | docker `rector/rector:latest` |
| PHP version    | docker |
| Full Command   | any `docker run -v $(pwd):/project rector/rector:latest --version` | 

## Current Behaviour 

```
Fatal error: Uncaught Nette\FileNotFoundException: File '/rector/vendor/symplify/phpstan-extensions/config/config.neon' is missing or is not readable. in /rector/vendor/nette/di/src/DI/Config/Loader.php:43
Stack trace:
#0 /rector/vendor/nette/di/src/DI/Config/Loader.php(60): Nette\DI\Config\Loader->load('/rector/vendor/...', false)
#1 /rector/vendor/nette/di/src/DI/Compiler.php(127): Nette\DI\Config\Loader->load('/rector/phpstan...', false)
#2 /rector/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(258): Nette\DI\Compiler->loadConfig('/rector/phpstan...', Object(Nette\DI\Config\Loader))
#3 /rector/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#4 /rector/vendor/nette/di/src/DI/ContainerLoader.php(79): Nette\DI\ContainerLoader->generate('Container_48b06...', Array)
#5 /rector/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile('Container_48b06...', Array)
#6 /rector/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(2 in /rector/vendor/nette/di/src/DI/Config/Loader.php on line 43

```

## Minimal PHP Code Causing Issue

No php code needed. Run using e.g. `docker run -v $(pwd):/project rector/rector:latest --version` and make sure to remove the local docker image before to make sure it's freshly downloaded.

Maybe docker image build is broken somehow, not copying the needed config file?

### PR DESCRIPTION
**Pull request by JanMikes**
Fixes #2185

### CODE REVIEW

**Comment by JanMikes** [comment]
Repro steps for this bug before fix:

`composer update --no-dev && bin/rector`

or 

`docker run -v $(pwd):/project rector/rector:latest --version`

**Comment by TomasVotruba** [comment]
These packages are dev, not production. This is not way to fix it

**Comment by JanMikes** [comment]
Then why they are required to run `bin/rector` if they are dev?

**Comment by TomasVotruba** [comment]
I run `bin/rector` reasily without them

**Comment by TomasVotruba** [comment]
E.g. here https://github.com/TomasVotruba/tomasvotruba.cz/blob/master/.travis.yml#L19

**Comment by TomasVotruba** [comment]
Not sure if, but this one might be related to PHPStan rather:
https://github.com/rectorphp/rector/pull/2184

**Comment by JanMikes** [comment]
> E.g. here https://github.com/TomasVotruba/tomasvotruba.cz/blob/master/.travis.yml#L19

@TomasVotruba well, this is kinda "lucky" because pehapkari.cz project has all dependencies in dev, that are otherwise failing, but for example when tried on other project, where we do not use symplify phpstan extensions and so on, this fails. It fails even for rector itself

1. `git clone https://github.com/pehapkari/pehapkari.cz.git`
2. `composer install --no-dev`
3. `bin/rector --version`

Imho this is definitely bug, that affects most of projects where rector is installed. 

It is caused by that when running `bin/rector` it loads `phpstan.neon` which is targeted for internal use (running phpstan against repository itself) if i understand it correctly and it should not be used for analysing other repositories with rector. As mentioned by you, #2184 could do the trick

**Pull request closed without merging**
