### PR TITLE
Return error code on diff with dry-run option

### LINKED ISSUE #800: The --dry-run option should return a non-zero exit code
Or if it's not possible, maybe add a `--exit-code` option as you can see on the `git diff` command.

It is for CI usage.

Related to https://github.com/rectorphp/rector/issues/799#issuecomment-442900482

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #800

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
The failing CI is not related to the PR. A CS update is needed.

**Comment by TomasVotruba** [comment]
Please fix that too

**Comment by Soullivaneuh** [comment]
@TomasVotruba Done.

**Comment by Soullivaneuh** [comment]
Well, now Travis want to revert my changes! https://travis-ci.org/rectorphp/rector/jobs/462834349 \o/

Any idea why? :smile:

**Comment by TomasVotruba** [comment]
I see a different one: https://travis-ci.org/rectorphp/rector/jobs/462834349#L653

**Comment by Soullivaneuh** [comment]
Indeed, but it's the command I found who did the exact same changes.

**Comment by TomasVotruba** [comment]
But no troubles, I can handle this :+1:

**Comment by TomasVotruba** [comment]
Thank you

**Comment by TomasVotruba** [comment]
So that error is related to PHPStan && php-parser: print incompatibility: https://github.com/nikic/PHP-Parser/issues/554#issuecomment-443343732

I'll exclude the code in `ecs.yml` for now as workaround

What do you think?

**Comment by TomasVotruba** [comment]
Let's see if this resolves it #806

**Pull request merged**
