### PR TITLE
[TypeDeclaration] Handle return self on ReturnTypeFromStrictTypedCallRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixees https://github.com/rectorphp/rector/issues/5770

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I added nullable type handling as well https://github.com/rectorphp/rector/pull/5781/commits/4b520c4cebf475198c808b7544e7fd050109aea8

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
