### PR TITLE
allow Nette 3.0

### PR DESCRIPTION
**Pull request by mimmi20**
I wanted to test this tool, but I require Nette 3.0. 

By the way, Is it normal that your PHPUnit coverage tests require more than 25 minutes on travis ci?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks :+1: 

It usually takes 4-5 mins.

In this PR it's 6:

image


Where is 25 mins?

**Comment by mimmi20** [comment]
image

**Comment by TomasVotruba** [comment]
Could you share link?

**Comment by sanmai** [comment]
This got to be a glitch. Like, sometimes Composer can’t do its thing on time., or the like. Should be in the logs.

**Comment by mimmi20** [comment]
> Could you share link?

https://travis-ci.com/mimmi20/rector/jobs/193220853
https://api.travis-ci.com/v3/job/193220853/log.txt

I hope you can see this.

**Comment by TomasVotruba** [comment]
Yes I can, for open source projects it's always public.

Probably some glitch. If it happens again, let me know

**Pull request merged**
