### PR TITLE
[Downgrade PHP 7.3] Trailing commas in function calls

### PR DESCRIPTION
**Pull request by quisse**
https://github.com/rectorphp/rector/issues/4168

### CODE REVIEW

**Comment by quisse** [comment]
After some digging I can conclude that this is not possible using php-parser because php-parser isn't aware of the trailing comma AFAIK.
Any help would be appreciated.

**Comment by TomasVotruba** [comment]
Same here. Maybe php-cs-fixer is better for this job

**Comment by quisse** [comment]
So is including php-cs-fixer as a dependency an option? It would be nice if rectorphp makes downgrading every php version possible.

**Comment by quisse** [comment]
Triggering regeneration removes the trailing commas. The only side effect I'm aware of is that when having a method call inline in a string in a method call, the curly brackets are doubled.
```
    public function refactor(Node $node): ?Node
    {
        if($node->args){
            $node->setAttribute(AttributeKey::ORIGINAL_NODE,null);
        }
        return $node;
    }
```

Makes 
```
        $this->setOnClick("[Zip ID: {$modelid}]  {$e->getMessage($modelId,)}");
```
results in 
```
        $this->setOnClick("[Zip ID: {$modelid}]  {{$e->getMessage($modelId)}}");
```
A possible workaround could be
```
    public function refactor(Node $node): ?Node
    {
        if($node->args){
            if(! $node->getAttribute(AttributeKey::PARENT_NODE) instanceof Node\Scalar\Encapsed){
                $node->setAttribute(AttributeKey::ORIGINAL_NODE,null);
            }
        }
        return $node;
    }
```
But the trailing comma isn't removed then.

**Comment by TomasVotruba** [comment]
Removing original node usually lead to reprint without format. Then it depends on default printer setting.

What could work is do is hack around `BetterStandardPrinter` and remove comma there.

**Comment by quisse** [comment]
With this one I am waiting for https://github.com/nikic/PHP-Parser/pull/732.
That issue causes that `"[Zip ID: {$modelid}]  {$e->getMessage($modelId)}"` is rewritten as `"[Zip ID: {$modelid}]  {{$e->getMessage($modelId)}}"`

**Comment by quisse** [comment]
@TomasVotruba updating nikic/phpparser doesn't seem sufficient, do I need to wait for phpstan to include the latest phpparser or am I missing something?

**Comment by TomasVotruba** [comment]
I'll look into this

**Comment by TomasVotruba** [comment]
These 2 last details are ok. Do not change the code meaning and solves the comma.

Merged in: https://github.com/rectorphp/rector/pull/4796

Thank you :+1:

**Pull request closed without merging**
