### PR TITLE
Add Yaml refactoring support

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref #503

## Preview

image

### CODE REVIEW

**Comment by xabbuh** [comment]
How does this support the different ways to write YAML? I am thinking of for example the inline notation and literal or folded blocks. On a quick glance it looks like we could end up with invalid YAML here.

**Comment by TomasVotruba** [comment]
This is just prototype. Vission is to support those format to end up with valid YAML file

**Comment by xabbuh** [comment]
You may find some inspiration in the test suite of the Symfony YAML component where we had to deal with such edge cases.

**Comment by TomasVotruba** [comment]
Could link those? Are they relevant to refactoring?

**Comment by xabbuh** [comment]
You could scan the tests in https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Yaml/Tests.

**Comment by TomasVotruba** [comment]
Thanks, I'll get to it after 
https://github.com/rectorphp/rector/issues/514

**Pull request merged**
