### PR TITLE
[DeadCode] Skip RemoveUnusedPrivatePropertyRector on isset as well

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by lulco** [comment]
👍

**Comment by lulco** [comment]
@samsonasik isset / unset is now ok, but something has changed... I have this class:

```
<?php

declare(strict_types=1);

namespace Rector\Composer\ValueObject;

use Rector\Composer\Modifier\ComposerModifier;
use Rector\Composer\Contract\ComposerModifier\ComposerModifierInterface;

/**
 * Changes one package for another
 * @see \Rector\Composer\Tests\ValueObject\ChangePackageTest
 */
final class ChangePackage implements ComposerModifierInterface
{
    /** @var string */
    private $oldPackageName;

    /** @var string */
    private $newPackageName;

    /** @var string */
    private $targetVersion;

    public function __construct(string $oldPackageName, string $newPackageName, string $targetVersion)
    {
        $this->oldPackageName = $oldPackageName;
        $this->newPackageName = $newPackageName;
        $this->targetVersion = $targetVersion;
    }

    public function modify(array $composerData): array
    {
        foreach ([ComposerModifier::SECTION_REQUIRE, ComposerModifier::SECTION_REQUIRE_DEV] as $section) {
            if (isset($composerData[$section][$this->oldPackageName])) {
                unset($composerData[$section][$this->oldPackageName]);
                $composerData[$section][$this->newPackageName] = $this->targetVersion;
            }
        }
        return $composerData;
    }
}
```

And `newPackageName` is removed while it is used as array key on level 2
```
$composerData[$section][$this->newPackageName] = $this->targetVersion;
```

If these changes will be available on rector demo, I can try to create minimal code

**Comment by samsonasik** [comment]
@lulco fixed now.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by lulco** [comment]
gr8

**Comment by TomasVotruba** [comment]
Looks good to me, thank you @samsonasik

**Pull request merged**
