### PR TITLE
allow loading bleedingEdge.neon config inside PHPStan phar

### LINKED ISSUE #2431: Cannot load bleedingEdge from phpstan
| Subject        | Details                                                      |
| :------------- | :----------------------------------------------------------- |
| Rector version | v0.6.1          |
| PHP version    | PHP 7.3.12                               |
| phpstan version    | v0.12.2                               |

## Current Behaviour 

After run process:

```
rector process module/ --dry-run

Fatal error: Uncaught _HumbugBox22f0dbe102af\Nette\FileNotFoundException: File 'phar://phpstan.phar/conf/bleedingEdge.neon' is missing or is not readable. in phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php on line 29

_HumbugBox22f0dbe102af\Nette\FileNotFoundException: File 'phar://phpstan.phar/conf/bleedingEdge.neon' is missing or is not readable. in phar:///var/www/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php on line 29

Call Stack:
    0.0558     458192   1. {main}() /var/www/vendor/rector/rector/bin/rector:0
    1.4034   23744432   2. ContainerKpKdxQ6\HttpKernelRector_HttpKernel_RectorKernelProd5699145Container->get() /var/www/vendor/rector/rector/bin/rector:47
    1.4034   23744432   3. ContainerKpKdxQ6\HttpKernelRector_HttpKernel_RectorKernelProd5699145Container->make() /var/www/vendor/symfony/dependency-injection/Container.php:225
```

## Minimal PHP Code Causing Issue

My phpstan config includes `bleedingEdge.neon`, which is fine, even in phar.
```neon
includes:
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon
```

## Expected Behaviour
No fatal, bleedingEdge included.

### PR DESCRIPTION
**Pull request by TomasVotruba**
Fixes #2431

### CODE REVIEW

**Comment by snapshotpl** [comment]
@TomasVotruba this fix should help in my case

**Comment by TomasVotruba** [comment]
Could you confirm it works? I could not think of better way

**Comment by snapshotpl** [comment]
@TomasVotruba confirmed!

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
