### PR TITLE
[Solid] Improve MoveVariableDeclarationNearReferenceRector : skip variable with usage in multiple level

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I found another false positive when there is maybe a statement between used in parent next:

```php
    $varused = 1;

    if (mktime() === false) {
        if (true) {
            if (false) {
                return $varused;
            }
        }
    }

    echo 'STATEMENT HERE';

    echo $varused;
```

**Comment by samsonasik** [comment]
fixed.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
