### PR TITLE
[CodingStyle] UnderscoreToCamelCaseVariableAndPropertyNameRector

### LINKED ISSUE #3414: [CodingStyle] under_score to camelCase variable names
```diff
-$value_name
+$valueName
```

<br>

See failed cs attemps:

- https://github.com/squizlabs/PHP_CodeSniffer/issues/1228
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2362

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #3414

### CODE REVIEW

**Comment by popovserhii** [comment]
@TomasVotruba As I understand the `UnderscoreToCamelCaseVariableAndPropertyNameRector` property is not available any more in [the latest release](https://github.com/rectorphp/rector/releases/tag/0.10.3)? What should we use instead?

**Comment by TomasVotruba** [comment]
Yes, that's correct. These rules are more about subjective naming conventions, that should be handled by  coding standards.
See references coding standard rules https://github.com/rectorphp/rector/issues/3414

**Comment by popovserhii** [comment]
This rule was only the reason why I've started to use Rector and was waiting for 4 months while two related issues will be fixed ( #4620, #5392), and now I need to discover another solution.

**Comment by TomasVotruba** [comment]
That was my mistake, that original upgrade/refactoring shifted way too close to coding standards. I'm sorry about that.

The phpdoc fix is still in progress, see https://github.com/rectorphp/rector/issues/4334

**Comment by josep11** [comment]
Hello. It's not on main, right?

**Comment by samsonasik** [comment]
@josep11 yes, it removed, if you need it, you can check on `CodeIgniter4` custom rule for it with customize on based on CodeIgniter4 coding standard, see https://github.com/codeigniter4/CodeIgniter4/blob/develop/utils/Rector/UnderscoreToCamelCaseVariableNameRector.php

**Pull request merged**
