### PR TITLE
PHPStan fixes

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
The fail in `Static Analysis / phpstan` is relevant to an experimental feature that will be fixed before 0.12.10 is released. Otherwise it looks fine :)

**Comment by TomasVotruba** [comment]
Looks good, let's give it a try :)

**Comment by bendavies** [comment]
was this mean to fix ` "Class '_HumbugBoxebb6c51d1e3e\JetBrains\PHPStormStub\PhpStormStubsMap' not found".`?
Because i'm still seeing that

**Comment by TomasVotruba** [comment]
Where?

Phat was just build and it passes
https://github.com/rectorphp/rector-prefixed

**Comment by TomasVotruba** [comment]
I also released 0.7.0 just now

**Comment by bendavies** [comment]
I'm not using the phar. I'm using checked out master branch.

**Comment by TomasVotruba** [comment]
To little information. Could you send Github Action with same scenary to reproduce it?

**Comment by bendavies** [comment]
Struggling but here's a stack trace in the mean time:
```
➜  release-tool git:(php7.4) ✗ ~/Code/misc/rector/bin/rector  process src/CircleCI/Api/V1/Me/Response/Job.php --set php74 -vvv
Rector 0.6.x-dev@b2c0c3e

[parsing] src/CircleCI/Api/V1/Me/Response/Job.php
PHP Fatal error:  Uncaught Error: Class '_HumbugBoxebb6c51d1e3e\JetBrains\PHPStormStub\PhpStormStubsMap' not found in phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:67
Stack trace:
#0 phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(38): _HumbugBoxebb6c51d1e3e\Roave\BetterReflection\SourceLocator\SourceStubber\PhpStormStubsSourceStubber->generateClassStub('self')
#1 phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(31): _HumbugBoxebb6c51d1e3e\Roave\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->getClassSource(Object(_HumbugBoxebb6c51d1e3e\Roave\BetterReflection\Identifier\Identifier))
#2 phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/ph in phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php on line 67
Fatal error: Uncaught Error: Class '_HumbugBoxebb6c51d1e3e\JetBrains\PHPStormStub\PhpStormStubsMap' not found in phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php:67
Stack trace:
#0 phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(38): _HumbugBoxebb6c51d1e3e\Roave\BetterReflection\SourceLocator\SourceStubber\PhpStormStubsSourceStubber->generateClassStub('self')
#1 phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/PhpInternalSourceLocator.php(31): _HumbugBoxebb6c51d1e3e\Roave\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator->getClassSource(Object(_HumbugBoxebb6c51d1e3e\Roave\BetterReflection\Identifier\Identifier))
#2 phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/ph in phar:///Users/ben/Code/owsy/release-tool/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php on line 67
```

**Comment by TomasVotruba** [comment]
Without full test, it's just black box

**Comment by bendavies** [comment]
I realise that. I'm trying to debug it.

**Comment by ondrejmirtes** [comment]
1) What does vendor/bin/phpstan —version tell you?
2) What dependencies you have in composer.json?

**Comment by bendavies** [comment]
good catch. my project had a different version of phpstan installed, `0.12.9`.
after upgrading, to match rector, `0.12.10`, it works

**Pull request merged**
