### PR TITLE
Add failing test fixture for ChangeReadOnlyPropertyWithDefaultValueToConstantRector

### PR DESCRIPTION
**Pull request by zingimmick**

### CODE REVIEW

**Comment by samsonasik** [comment]
@zingimmick it seems placing in `Source` directory make not detected by `NodeRepository`, I actually register to composer.json as well but it still not found by `NodeRepository`, move to the current fixture solve it. 

Actually, this already handled, I cherry-picked your commit and move the class that has reference in arg method inside the fixture itself at #6234

**Comment by zingimmick** [comment]
> @zingimmick it seems placing in `Source` directory make not detected by `NodeRepository`, I actually register to composer.json as well but it still not found by `NodeRepository`, move to the current fixture solve it.

Sorry for the slow response, but that is one of the steps to reproduce the problem because the code in `Source` directory is actually in `vendor` directory.

> Actually, this already handled, I cherry-picked your commit and move the class that has reference in arg method inside the fixture itself at #6234

Yes, PRs #6084, #6049 skipped `ChangeReadOnlyPropertyWithDefaultValueToConstantRector` on parameter referenced in method/static call, and [skip_referenced2.php.inc](https://github.com/rectorphp/rector/blob/dd0c1038da9d0d1da7c1ccd38f3b544801bf7cc6/rules-tests/Privatization/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_referenced2.php.inc) already handled this.

But since the code in `vendor` directory, move the class is not the optional way for me.

I also tried add these files to the option `autoload_paths` or `bootstrap_files` or both, but it not works. Did I miss something?

**Comment by samsonasik** [comment]
@zingimmick could you create sample repository to check with github action enabled with the `ChangeReadOnlyPropertyWithDefaultValueToConstantRector ` rule enabled? Thank you.

**Comment by zingimmick** [comment]
> @zingimmick could you create sample repository to check with github action enabled with the `ChangeReadOnlyPropertyWithDefaultValueToConstantRector ` rule enabled? Thank you.

Repository: https://github.com/zingimmick/rector-sample

**Comment by samsonasik** [comment]
@TomasVotruba the `NodeRepository` seems can't get `ClassMethod` by `MethodCall` if the `ClassMethod` definition outside the code that call it. It seems the `addCallByType()` only register the `MethodCall`, not the `ClassMethod` 

https://github.com/rectorphp/rector/blob/a5a99317b7418c2914021d24ced9c172773465d9/packages/NodeCollector/NodeCollector/NodeRepository.php#L637-L657

**Comment by samsonasik** [comment]
@zingimmick I cherry-picked your commit at PR https://github.com/rectorphp/rector/pull/6256

**Pull request closed without merging**
