### PR TITLE
apply ArrayToYieldDataProviderRector

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref #401 

Refactoring Rector with Rector :)

image

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I think there was some issue reported. Could you try it?

**Comment by carusogabriel** [comment]
@TomasVotruba We can use. But, we'd need to rollback the annotations. What is your opinion?

**Comment by TomasVotruba** [comment]
What would be added value of that?

**Comment by carusogabriel** [comment]
@TomasVotruba We're just using the features we have. The decision is up to you :)

**Comment by TomasVotruba** [comment]
I just don't see any added value in it. Only it's less precise, more code, less readable and ambiguous. But that's me. Do you think of any advantages?

**Comment by TomasVotruba** [comment]
:+1: Thanks

**Pull request merged**
