### PR TITLE
Do not mark injected properties as private when moved to constructor

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/rectorphp/rector/issues/1400#issuecomment-508336071

### CODE REVIEW

**Comment by TomasVotruba** [comment]
What about classes with no children?

**Comment by holtkamp** [comment]
As mentioned here https://github.com/rectorphp/rector/issues/1400#issuecomment-508675676, I do not think "detecting" this is the responsibility of this rector...? Better to have a lot of small and focussed rectors and let them work together, right?

**Comment by TomasVotruba** [comment]
Great approach and usually I'd agree. 

I try to look at this from users perspective - what would they change in code at one go?
Would they not care about visibility?

**Comment by holtkamp** [comment]
Well, from my user-perspective. In case I have marked my `property` as public or `protected`, this has a reason...

Of course, in case rector can determine properly that the visibility can be set to `private`, this would be great. However: I do not know how to determine that reliable, so I choose the easy way 😄 

In case it is possible for rector to determine whether:
- a `public` property is used by by other code
- a `protected` property is used by specializing classes

=> then this could be added. But I "assumed" this would be possibly get quite complex?

**Comment by TomasVotruba** [comment]
I see. Thanks for explaning your point of view. It helped me to improve my pespective :)

Let's try your idea and see how it goes.

**Comment by TomasVotruba** [comment]
Thanks for the PR!

**Pull request merged**
