### PR TITLE
Introduce a CallReflectionResolver

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could elaborate on motivation and main features  for this PR?

**Comment by Lctrs** [comment]
Main motivation was to reduce duplicated code and leverage PHPStan to create a class that is able to return the reflected function from any calls given, even on a variable that has been assigned a closure (eg. `$f = function(){}; $f();`)

**Comment by TomasVotruba** [comment]
I see, thanks :+1:

**Comment by Lctrs** [comment]
Worth noting that `Rector\PhpParser\Node\Manipulator\CallManipulator` class is now unused across the project. Didn't had the gut to remove it.

**Comment by TomasVotruba** [comment]
Go for it

**Pull request merged**
