### PR TITLE
Fixes #4290 wrong skip assignment not from parameter in UnderscoreToCamelCaseLocalVariableNameRector

### LINKED ISSUE #4290: UnderscoreToCamelCaseLocalVariableNameRector bug: wrong skip when assignment not from parameter
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master             |
| Installed as   | prefixed Rector PHAR                      |

## Minimal PHP Code 

The following code still not changed correctly:

```php
   public function run()

     {

         $_a = 'a';

         $_some_value = $_a;

         $this->run($_some_value);

     }
```

## Expected Behaviour

All changed correctly.

I will check it.

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I found another bug, when using expression:

```php
final class InsideExpression
{
    public function run($_a)
    {
        if ($_a) {
            $_some_value = $_a;
        }
    }
}
```

`$_a` in ` if ($_a) {` expression should be skipped.

**Comment by samsonasik** [comment]
I've added handling for inside expression

**Comment by samsonasik** [comment]
I found another bug, the following should be skipped:

```php
final class AssignToClassProperty
{
    public function run($a_b)
    {
        $this->a_b = $a_b;
    }
}
```

**Comment by samsonasik** [comment]
I've added handling assignment to property fetch

**Comment by samsonasik** [comment]
I found another bug, the following should be skipped:

```php
final class FromExpressionWithCheckValueComparison
{
    public function run($a_b)
    {
        if ($a_b === false) {

        }
    }
}
```

**Comment by samsonasik** [comment]
I've added handling comparison check inside expression

**Comment by samsonasik** [comment]
I found another bug, the following should be skipped:

```php
final class SkipPassFunctionParameterToClosure
{
    public function run(string $a_b, string $c_d)
	{
		function ($a_b) use ($c_d) {

		};
	}
}
```

**Comment by samsonasik** [comment]
I've added handling ClosureUse parameter

**Comment by samsonasik** [comment]
I think it is ready

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
