### PR TITLE
[Core] Fixes Cache in FilesFinder

### LINKED ISSUE #6389: Caching is not working anymore.
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.10.5 and greater            |
| Installed as   | composer dependency                      |

Rector cache is not working(processing all files over and over). I am like 99% sure this pull request(https://github.com/rectorphp/rector/pull/6085) is the cause. 

Latest version with working caching is v0.10.4.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #6389 . It was due to cache key overlapped with next cache key, while `[php]` suffix not checked.

### CODE REVIEW

**Comment by samsonasik** [comment]
The issue now is it always cached even with `--clear-cache` parameter or set `Option::ENABLE_CACHE` to false.

**Comment by samsonasik** [comment]
@TomasVotruba I've updated to use `Nette\Caching\Cache` at https://github.com/rectorphp/rector/pull/6398/commits/9a22f7377b8844d99cf383a9ba81f0c844dc01cd to ensure collection of files is cached.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Moved to development repository https://github.com/rectorphp/rector-src/pull/29

**Comment by derrickleemy** [comment]
Has this fix been released? I'm still having problems where rector is running on all files even on the second attempt even when:

```
$parameters->set(Option::ENABLE_CACHE, true);
```

**Comment by TomasVotruba** [comment]
> Has this fix been released? 

If the feature was released, you can check the exact version here:

https://github.com/rectorphp/rector-src/pull/29

image

**Comment by derrickleemy** [comment]
> > Has this fix been released?
> 
> If the feature was released, you can check the exact version right in the pull-request:
> 
> [rectorphp/rector-src#29](https://github.com/rectorphp/rector-src/pull/29)
> 
> image

Screenshot 2021-06-18 at 6 04 47 PM

I don't see it. And i'm using rector 0.11.20 and still having this issue

**Comment by TomasVotruba** [comment]
Ah, I thought this is provided by Github by default.
When I disabled all my extensions, I found out it's part of Refined Github :slightly_smiling_face: 
https://github.com/sindresorhus/refined-github

We'll need a reproducible repository to verify the fix

**Comment by mssimi** [comment]
I can confirm that caching is still not working.

**Comment by samsonasik** [comment]
@TomasVotruba the patch seems removed when migrating to own cache, see https://github.com/rectorphp/rector-src/commit/ac81e98fbfb138ffd1b3dd2725ee1c6b7010a22b#diff-c1b4d526cfa7d17990bde4cf0146bcf748e35382d13d14ca350a21820d2df256L49

**Comment by TomasVotruba** [comment]
I'm sorry if I broke something.
I've removed that part because it was caching a directory. If there was a new file a in a directory, it was missed.

We should have a test for broken behavior first.

**Comment by samsonasik** [comment]
Ok, I created new PR to enable back it https://github.com/rectorphp/rector-src/pull/260

**Pull request closed without merging**
