### PR TITLE
[DeadDocBlock] Skip RemoveUselessReturnTagRector on Generic Type

### LINKED ISSUE #5674: RemoveUselessReturnTagRector should not remove if iterable type is specified
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.9.31 (invoke `vendor/bin/rector --version`)              |
| Installed as   | prefixed Rector                           |

In my example this should not be removed:

https://getrector.org/demo/03643045-9933-4fce-9a70-3c948e737c5a

Produced diff:
```diff
@@ -2,11 +2,8 @@
 
 final class DemoFile
 {
-    /**
-     * @return iterable<stdClass>
-     */
     public function run(): iterable
     {
         yield \stdClass;
     }
 }
```

If you remove, PHPStan is complaining, if I add, rector removes it 😄 

> Method App\ArgumentResolver\UserIdArgumentResolver::resolve() return type has no value type specified in
         iterable type iterable.
         💡 See: https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-iterable-type

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5674

### CODE REVIEW

**Comment by OskarStark** [comment]
Looks great, thank you!

Maybe you can have a look at #5676 this too, it needs to receive the same fix I guess

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
