### PR TITLE
[DeadCode] Fixes #4663 Handle RemoveEmptyMethodCallRector on parent is Assign

### LINKED ISSUE #4663: Is Rector that slow?
# Question

Hey, I've upgraded to the latest Rector and now when I run the same command on the same code base as before then it times out after 1 hour 23 minutes 20 seconds:

```
composer rector -- --dry-run
> bin/rector process --config rector.php '--dry-run'
Rector 0.8.52
Config file: rector.php

 2769/9112 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30%
                                                                                                
  [Symfony\Component\Process\Exception\ProcessTimedOutException]                                
  The process "bin/rector process --config rector.php '--dry-run'" exceeded the timeout of 5000 seconds.
```

It takes 1 minute 49 seconds on version 0.6.13. See https://github.com/mautic/mautic/runs/1386226195

Is this normal?

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba composer install error seems unrelated:

```bash
Run composer install --no-progress --ansi
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symplify/autowire-array-parameter dev-master -> satisfiable by symplify/autowire-array-parameter[dev-master].
    - symplify/autowire-array-parameter dev-master requires php >=7.3 -> your php version (7.2.34) does not satisfy that requirement.
```

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
