### PR TITLE
[Github Action]  Fixes fail-fast location to be in strategy on publish_docker_images action

### LINKED ISSUE #5849: publish_docker_images.yaml error Unexpected value 'false'
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |
| Installed as   | in CI                           |

It seems PR https://github.com/rectorphp/rector/pull/5830 caused an error : 

```
The workflow is not valid. .github/workflows/publish_docker_images.yaml (Line: 18, Col: 28): Unexpected value 'false'
```

ref https://github.com/rectorphp/rector/actions/runs/651700845

/cc @mpdude could you verify it? Thank you.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5849

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 let's merge and see if it works

**Comment by samsonasik** [comment]
The `Build docker images` action seems running now

Screen Shot 2021-03-14 at 23 42 39

**Comment by mpdude** [comment]
Thanks for catching this!

**Pull request merged**
