### PR TITLE
[Privatization] Fix another get class

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by HenkPoley** [comment]
This is just to get more idiomatic PHP? Not that there is any issue with it. Just wondering, why not apply it in anything earlier than SetList::PHP_74 (or why at all)? If it's just a code quality thing.

**Comment by TomasVotruba** [comment]
This is a bug fix of missing class in a new node. Not sure what you comment on.

**Comment by HenkPoley** [comment]
When I apply SetList::PHP_74 it applies a lot of __CLASS__ to self::class replacements (rule: Rector\Php74\Rector\Class_\ClassConstantToSelfClassRector). Which lead me here.

I probably clicked / commented on a patch too late.

**Comment by TomasVotruba** [comment]
That's not related to this PR

**Comment by HenkPoley** [comment]
Ah, I see. It is probably more likely this one: https://github.com/rectorphp/rector/commit/2e7bdca4e2c2b630d638b2fb3bd58b09a951c154#diff-66f9f0cb0082623f20869a1493f7c2257f22669b3ac81a2ee4c05a16d6338f4c

Should I open an issue about this, or is this more of a 'shrug' thing, that will be kept anyways?

**Comment by TomasVotruba** [comment]
> Should I open an issue about this

:+1:

**Pull request merged**
