### PR TITLE
[Docker] Fixing configure - install - enable intl

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by HenkPoley** [comment]
Looks good to me

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready

**Comment by TomasVotruba** [comment]
Thank you

**Comment by samsonasik** [comment]
Now got another error:

```bash

configure: error: Package requirements (icu-uc >= 50.1 icu-io icu-i18n) were not met:

No package 'icu-uc' found
No package 'icu-io' found
No package 'icu-i18n' found
```

For testing, I think github action need to be in PR to ensure the docker build working

**Comment by TomasVotruba** [comment]
Docker build is very slow, so it would block PRs to review.

Docker image should be tested locally, not depend on Github Actions feedback, as there can be 5 bugs in a row. Waiting for Github Actions is for ages, while locally you can see the error instantly.

**Comment by samsonasik** [comment]
Ok, I will try.

**Pull request merged**
