### PR TITLE
Clarify paths.

### PR DESCRIPTION
**Pull request by dereuromark**
What do you think about this?

It is recommended to clarify paths with the slash, as in most OS a file can be anything without an ext as well.
Even if it works without, I think the docs are clearer.

The PSR-4 map is also recommended to have the clarity of trailing slash in place.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I assume this is known to particular OS users. Like upper/lower case for Windows and Linux, `PHP_EOL` differences or `\`, `/` separators for file paths. Adding all these to all documentations would only create clutter and make Rector Documentation complicated to read.

**Comment by dereuromark** [comment]
The PSR4 part is still true, though.

**Comment by TomasVotruba** [comment]
If it causes bugs on specific OS, it should be validated/required by composer then

**Comment by dereuromark** [comment]
The normalized version is also documented and advised to be used.
Both are valid, but what I PRd is the recommended form of writing it.

**Comment by TomasVotruba** [comment]
On what OS does this cause bug?

How does the bug exactly look like while using Rector?

**Comment by dereuromark** [comment]
Its not a bug, it is the normalized and documented form what is supposed to be put into the composer path section.

**Pull request closed without merging**
