### PR TITLE
Improved rector in docker autoloading

### LINKED ISSUE #4234: Dockerized rector does not seem to work properly
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.8.x-dev              |
| Installed as   | docker container                      |

When I run the following command:
```
docker run -v $(pwd):/project rector/rector:latest process /project/src --set symfony40 --dry-run
```
or 
```
docker run -v $(pwd):/project rector/rector:latest process /project/src --set symfony40 --dry-run --autoload-file /project/vendor/autoload.php
```
https://github.com/rectorphp/rector#run-rector-in-docker

I get a lot of the following errors. e.g.:
```
 [ERROR] Could not process                                                      
         "../project/src/User/UserService.php" file, due to:  
         "Analyze error: "Class                                                 
         User/User not found.". Include 
         your files in "parameters > autoload_paths".                           
         See https://github.com/rectorphp/rector#extra-autoloading".  
```

The code itself works, so autoloading is set up correctly.

Am I doing something wrong? or is the docker container not working properly?

### PR DESCRIPTION
**Pull request by JanMikes**
Fixes #4234

### CODE REVIEW

**Comment by rgeraads** [comment]
This fix needs to be explicitly documented that `$(pwd):/project` needs to be used as entry path.

**Comment by JanMikes** [comment]
Can you please explain a little bit? It is already in readme: https://github.com/rectorphp/rector#run-rector-in-docker

Since in this PR i changed workdir to `/project` so it takes it's autoloader by default, it is no longer required to us absolute paths for process command `/project/src` -> `src`, though, it is still possible to use it. 

Anyways you are right that changing the volume to something else that `/project` would cause autoloading problems again.

**Comment by rgeraads** [comment]
It is in the readme, but often that is a personal preference which can be changed to everyone's desire (e.g. `$(pwd):/app` is often used as well).

I think it's worth adding a note that `/project` **must** be used, otherwise it will break


```
docker run -v $(pwd):/app rector/rector:docker-autoload-fix process src --set php80 --dry-run                                    
Rector dev-master@4865855


In FilesystemTweaker.php line 41:
                                  
  Directory "src" was not found.
```

**Comment by JanMikes** [comment]
Added in  https://github.com/rectorphp/rector/pull/4368/commits/c745849715297b09f6c27b79cd10440bb43b9ced, thank you for your suggestion.

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
