### PR TITLE
Add failing fixture for RemoveUnusedAliasRector

### PR DESCRIPTION
**Pull request by u01jmg3**
Ref #3764

### CODE REVIEW

**Comment by u01jmg3** [comment]
@TomasVotruba: on attempting to fix #3764 I've also upset 4 other previously passing tests. 

Therefore, what is the best way of determining that a static method call is present and thus an alias should be kept?

**Comment by u01jmg3** [comment]
@TomasVotruba: on attempting to fix #3764 I've also upset 4 other previously passing tests. 

Therefore, what is the best way of determining that a static method call is present and thus an alias should be kept?

**Comment by TomasVotruba** [comment]
I'm sorry I missed this PR.

> Therefore, what is the best way of determining that a static method call is present and thus an alias should be kept?

Why not change the name of the alias class? The alias is not needed anymore in this case.

You can either use `NodeFinder` or `CallableNodeTraverser` to find particular nodes.

**Comment by TomasVotruba** [comment]
I'll look into it

**Comment by TomasVotruba** [comment]
Yes, see https://github.com/rectorphp/rector/pull/4068

**Comment by u01jmg3** [comment]
Thanks - I am finding that the rector is still not quite working for constants.

e.g.

```diff
-use Stripe\PaymentIntent as StripePaymentIntent;
+use Stripe\PaymentIntent;

if (StripePaymentIntent::STATUS_SUCCEEDED) {
    return;
}
```

**Comment by TomasVotruba** [comment]
I see. I linked you in the #4068 PR to ask for a fix

**Pull request closed without merging**
