### PR TITLE
[Doc] Fixes spacing in images position in readme

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba should be fixed now:

Screen Shot 2021-03-22 at 18 03 36

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
