### PR TITLE
[SOLID] Add PrivatizeLocalClassConstantRector

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref #151

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ad PHP 7.1 level min

**Comment by mxr576** [comment]
@TomasVotruba Have you forgotten to add the new PrivatizeLocalClassConstantRector to the SOLID config?

https://github.com/rectorphp/rector/blob/v0.4.11/config/level/solid/solid.yaml

**Comment by TomasVotruba** [comment]
It seem like. Care for PR?

**Comment by mxr576** [comment]
Thanks for the confirmation. Sure, I'll create one tomorrow with the fix.

**Pull request merged**
