### PR TITLE
[TypeDeclarationg] Add Tokens iterator to AddArrayReturnDocTypeRector and AddArrayParamDocTypeRector

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it will keep adding `@return` tag:

```php

     * @return array<string, SmartFileInfo[]>&mixed[]|SmartFileInfo[]
     * @return array<string, SmartFileInfo[]>&mixed[]|SmartFileInfo[]
     * @return array<string, SmartFileInfo[]>&mixed[]|SmartFileInfo[]
     * @return array<string, SmartFileInfo[]>&mixed[]|SmartFileInfo[]
```

probably need to be closed first?

**Comment by TomasVotruba** [comment]
This is WIP

**Comment by samsonasik** [comment]
The issue is the rectify seems keep adding: 

```php
@return array<string, SmartFileInfo[]>&mixed[]|SmartFileInfo[]
```

while it already added, it probably will be infinite. 

I think we can close first, if any change, re-open with force push to the PR.

**Comment by TomasVotruba** [comment]
This is WIP. Wait for CI to be green before any review. Thanks

**Pull request merged**
