### PR TITLE
[Nette-To-Laravel]

### PR DESCRIPTION
**Pull request by genesiscz**
I am currently in process of migrating Nette application to Laravel and I've written several rules that could help a wide audience. I need a help tho. For some reason, this PresenterMethodsToControllerMethodsRector rule does delete spaces between some lines inside of the methods. Any help is appreciated :)

```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -72,22 +72,22 @@
                }
        }

-       function actionDefault($reservation_id): void
+       function actionDefault(\App\Requests\Request $request): void
        {
+               $reservation_id = $request->input('reservation_id');
                $this->redirect("hall", ["id" => 1]);
        }

-       function actionHall($id, $reservation_id): void
+       function actionHall(\App\Requests\Request $request): void
        {
+               $id = $request->input('id');
+               $reservation_id = $request->input('reservation_id');
                $this->template->hall = $hall = $this->getHall($id);
-
                $reservations_q = $this->hall_reservations->where("hall_id", $id);
                $reservations = [];
-
                foreach ($reservations_q as $reservation) {
                        $reservations[$reservation->hour][$reservation->minute] = $reservation;
                }
-
                $this->template->reservations = $reservations;
                $this->template->reservation_id = $reservation_id;
        }
```

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi,

spacing is limited by AST technology, so this is expected. See README: https://github.com/rectorphp/rector#known-drawbacks

This is handled by coding standard that should be run after each Rectoring :)

**Comment by genesiscz** [comment]
@TomasVotruba Could you please help with getting this rule into some better shape? It is currently too specific (using App\Requests\Request instead of Laravel's Request), renames the Presenter -> Controller in place (which I am not sure is correct thing to do), fills `return $this->response()` to all action (handle/action/render functions) functions, which of course makes the code broken after you rector it without futher editing. 

Thanks!

**Comment by TomasVotruba** [comment]
Hi, I'm sorry I missed your comment.

To finish the rule, there must be tests + fixtures present. They will show how the rule should behave. 

E.g. like this: https://github.com/rectorphp/rector/tree/master/rules/nette-to-symfony/tests/Rector/Class_/NetteControlToSymfonyControllerRector

**Comment by TomasVotruba** [comment]
Hi, any plans to push the rest of rule? We need the tests :)

**Comment by TomasVotruba** [comment]
Closing for lack of feedback for last 2 months.
Let me know if you have time and space for this. We can move it further, but it would require more intenstive work to the ruleset right.

Another way is to implement own package based on Rector, e.g. like https://github.com/rectorphp/rector-nette

**Comment by genesiscz** [comment]
> Closing for lack of feedback for last 2 months.
> Let me know if you have time and space for this. We can move it further, but it would require more intenstive work to the ruleset right.
> 
> Another way is to implement own package based on Rector, e.g. like https://github.com/rectorphp/rector-nette

I am so sorry I totally forgot and missed the notification apparently. Unfortunately I have no more time right now to look into that further as I feel I have moved past Nette already and I am in a rush with deadlines on that project I am working on, but if you or anybody here feels they could handle this & take my existing code, feel free to. 

Thank you for your amazing work Tomas, Rector helped a lot.

**Comment by TomasVotruba** [comment]
Thanks for your feedback and using the tool to such an amazing switches :hugs: 

<br>

Btw, if you ever have a talk/post about this, let me know I want to see it :+1:

**Comment by TomasVotruba** [comment]
Related dicussion for those who want to do the same migration: https://github.com/rectorphp/rector/discussions/5002

**Pull request closed without merging**
