### PR TITLE
Issue #2307 minimal code

### PR DESCRIPTION
**Pull request by JanMikes**

### CODE REVIEW

**Comment by JanMikes** [comment]
Both commands have unexpected results and fail in some way:

```bash
bin/rector p src/Issue2307/Exception.php --debug --config issue2307.yaml -n
bin/rector p src/Issue2307/AnotherClass.php --debug --config issue2307.yaml -n
```

**Comment by TomasVotruba** [comment]
I just fixed the test ;) 

Could you guess what was wrong? Hint: not Rector-related

**Comment by JanMikes** [comment]
I dont know but I would guess robot loader? :-)

**Comment by TomasVotruba** [comment]
No, no. It's reated to `/src` location + Symfony :)

**Pull request closed without merging**
