### PR TITLE
[Php73] Refactor JsonThrowOnErrorRector: change 2nd parameter of json_decode to null and skip on json_last_error, json_last_error_msg

### PR DESCRIPTION
**Pull request by samsonasik**
- change 2nd parameter of json_decode to null  as default value is null, ref https://www.php.net/manual/en/function.json-decode.php 

- skip when next func call is/are `json_last_error()`, `json_last_error_msg()` as may be used next ref https://3v4l.org/3R5fM

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Also handling when next statement is `Return_`

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
