### PR TITLE
[Renaming] Handle RenameMethodRector on new in caller class

### PR DESCRIPTION
**Pull request by samsonasik**
Close #5449

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by ruudk — APPROVED** [review]
🙌

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by ruudk** [comment]
Thanks for fixing it. Wanted to give it a try but it doesn't work on the latest version. Turns out it's not tagged yet. 

1) Could it be tagged?
2) Would it be possible to have rector-prefixed always in sync with rector master? Then I can just pull rector-prefix dev-master.

**Comment by ruudk** [comment]
Also, what's the tagging policy? I thought this happened automatically. Or is that a manual process?

**Comment by TomasVotruba** [comment]
The 0.x branch is with BC breaks, so having it tagged on every commit could cause many broken versions.
Thus the tagging is manual.

For now, use the `dev-master` version.

**Comment by ruudk** [comment]
Is it possible then to sync rector-prefixed on every commit with rector master? I cannot install rector master as it conflicts with my installed phpstan version :(

**Comment by TomasVotruba** [comment]
It should be synced on every commit: https://github.com/rectorphp/rector-prefixed, just not tagged

**Comment by TomasVotruba** [comment]
What version do you have?

```bash
vendor/bin/rector --version
```

**Comment by ruudk** [comment]
Amazing, it __does__ work! 

That means that I just verified that this PR fixed my problem! 👏 Thanks @samsonasik  @TomasVotruba

**Pull request merged**
