### PR TITLE
[Php80] Handle Nullable Type on ClassPropertyAssignToConstructorPromotionRector

### LINKED ISSUE #5608: Incorrect behavior of ArgumentAdderRector, ClassPropertyAssignToConstructorPromotionRector, UnionTypesRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/8ace6951-fa83-4f9e-8b1d-19aa8c54bf54

```php
<?php

final class DemoFile
{
    private ?DatetimeInterface $time;
    public function __construct(DatetimeInterface $time = null)
    {
        $this->time = $time;
    }
}
```

### Responsible rules

* `ArgumentAdderRector`

* `ClassPropertyAssignToConstructorPromotionRector`

* `UnionTypesRector`

## Expected Behavior

```php
<?php

final class DemoFile
{
    public function __construct(private ?DatetimeInterface $time = null)
    {
    }
}
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5608

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
