### PR TITLE
[Symfony] Skip construct with param Property Promotion on MakeCommandLazyRector in php 8

### LINKED ISSUE #5244: [MakeCommandLazyRector] Broken behaviour with php8 constructor property promotion and empty body
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.9.10              |
| Installed as   | composer dependency                           |

## Minimal PHP Code Causing Issue'

I'm using the rector's class with set `SetList::SYMFONY_CODE_QUALITY` and see wrong behavior

```diff
1) app/Cli/GenerateInviteCodeCommand.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -16,12 +16,6 @@
      */
     protected static $defaultName = 'calendar:security:generate-invite-code';

-    public function __construct(
-        private InviteRegistrationGeneratorInterface $inviteRegistration
-    ) {
-        parent::__construct();
-    }
-
     protected function execute(InputInterface $input, OutputInterface $output): int
     {
         $output->writeln($this->inviteRegistration->generate());
    ----------- end diff -----------


Applied rules:

 * Rector\Symfony\Rector\Class_\MakeCommandLazyRector
```

In my opinion the reason is empty body of constructor which deletes by method `MakeCommandLazyRector::removeConstructorIfHasOnlySetNameMethodCall()`

## Expected Behaviour

Empty constructor with constructor property promotion should not be deleted

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5244

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I updated to only check constructor with param only for property promotion in php 8

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :partying_face:

**Comment by dvapelnik** [comment]
@samsonasik thank you! 👋

**Pull request merged**
