### PR TITLE
[StrictTypes] Fixes #4429 Add ParamTypeToAssertTypeRector

### LINKED ISSUE #4429: [StrictTypes] Add param type to Assert type of validation Rule
```diff
    /**
     * @param PropertyFetch|StaticPropertyFetch $node
     */
    public function isReadContext(Node $node): bool
    {
-        \Webmozart\Assert\Assert::isAnyOf($node, [PropertyFetch::class, StaticPropertyFetch::class]);
```

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
PHPUnit error seems unrelated: 

```bash
 1) Rector\PHPStanExtensions\Tests\Rule\ConfigurableRectorRule\ConfigurableRectorRuleTest::testRule with data set #0 ('/home/runner/work/rector/rect...or.php', array())
_HumbugBoxc5228e318540\Nette\DI\ServiceCreationException: Service of type Rector\PHPStanExtensions\Rule\RequireClassTypeInClassMethodByTypeRule: Service of type Symplify\PHPStanRules\Naming\SimpleNameResolver needed by $simpleNameResolver in __construct() not found. Did you add it to configuration file?
```

**Comment by samsonasik** [comment]
btw, @TomasVotruba I am online at google meet if you want to talk

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
