### PR TITLE
Use require string argument in constructor rule

### PR DESCRIPTION
**Pull request by ruudk**
Waiting on new tagged release for Symplify PHPStan Rules now that https://github.com/symplify/symplify/pull/2968 is merged.

This PR is a reminder for that. 

It should prevent #5596 from happening again.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
It's better to test Symplify rule first, before tagging. We discovered many bugs before letting them out :)

Using `dev-master` for Symplify packages, temporarily

**Comment by ruudk** [comment]
@TomasVotruba Done, do you agree that these should be fixed?
```

 ------------------------------------------------------------------------
  rules/nette-to-symfony/src/NodeFactory/ActionWithFormProcessClassMethodFactory.php:40
 ------------------------------------------------------------------------
  - '#Use quoted string in constructor "new PhpParser\\Node\\Name\\FullyQualified\(\)" argument on position 0 instead of "\:\:class\. It prevent scoping of the class in building prefixed package#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  rules/nette-to-symfony/src/Rector/Class_/NetteControlToSymfonyControllerRector.php:151
 ------------------------------------------------------------------------
  - '#Use quoted string in constructor "new PhpParser\\Node\\Name\\FullyQualified\(\)" argument on position 0 instead of "\:\:class\. It prevent scoping of the class in building prefixed package#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php:34
 ------------------------------------------------------------------------
  - '#Method parameters must be compatible with its parent#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php:44
 ------------------------------------------------------------------------
  - '#Method parameters must be compatible with its parent#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  utils/doctrine-annotation-parser-syncer/src/Rector/Assign/AssignNewDocParserRector.php:41
 ------------------------------------------------------------------------
  - '#Use quoted string in constructor "new PhpParser\\Node\\Name\\FullyQualified\(\)" argument on position 0 instead of "\:\:class\. It prevent scoping of the class in building prefixed package#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  utils/doctrine-annotation-parser-syncer/src/Rector/ClassMethod/ChangeOriginalTypeToCustomRector.php:42
 ------------------------------------------------------------------------
  - '#Use quoted string in constructor "new PhpParser\\Node\\Name\\FullyQualified\(\)" argument on position 0 instead of "\:\:class\. It prevent scoping of the class in building prefixed package#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  utils/doctrine-annotation-parser-syncer/src/Rector/ClassMethod/LogIdentifierAndResolverValueInConstantClassMethodRector.php:134
 ------------------------------------------------------------------------
  - '#Use quoted string in constructor "new PhpParser\\Node\\Name\\FullyQualified\(\)" argument on position 0 instead of "\:\:class\. It prevent scoping of the class in building prefixed package#'
 ------------------------------------------------------------------------

```

**Comment by TomasVotruba** [comment]
> @TomasVotruba Done, do you agree that these should be fixed?

That was point of the rule, right? :+1:

**Comment by ruudk** [comment]
@TomasVotruba Yes, but I mean, are there no false positives? I know I'll have to manually change them and that's fine.

**Comment by TomasVotruba** [comment]
Not sure. I trust your jugment

**Comment by ruudk** [comment]
Updated the PR!

**Comment by TomasVotruba** [comment]
Good :+1:  I'm gonna release new patch Simplify today

CI is failing on PHP 7.3

**Comment by ruudk** [comment]
How to fix 7.3? As it doesn't have the type hints. Ignore the rule for that file?

**Comment by TomasVotruba** [comment]
Not sure. How did it happen?

It's PHPUnit, not PHPStan

image

**Comment by ruudk** [comment]
@TomasVotruba 2 more errors left:
```
 ------------------------------------------------------------------------
  packages/better-php-doc-parser/src/PhpDocParser/BetterPhpDocParser.php:240
 ------------------------------------------------------------------------
  - '#Regex must use string named capture groups instead of numeric#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  rules/php70/src/EregToPcreTransformer.php:277
 ------------------------------------------------------------------------
  - '#Regex must use string named capture groups instead of numeric#'
 ------------------------------------------------------------------------

```

ignore them?

Or please merge this PR so that at least some work is fixed already... master is now broken.

**Comment by TomasVotruba** [comment]
> ignore them?

Better fix them, if it's not a problem. Green CI is easy for me to merge :heavy_check_mark: 
Otherwise I have to check what is causing the problem and it creates extra unnecesary delays.

**Comment by ruudk** [comment]
I understand, but the 2 errors that are reported I don't know how to fix. It's happening because of changes in `symplify/phpstan-rules`. Unrelated to my original PR. 

Maybe @samsonasik can have a look at it?

**Comment by TomasVotruba** [comment]
Understood, this will happen more often as we test symplify/phpstan-rules here. Most of them were based on needs for Rector code, so we might also use Symplify dev version just to confirm they work correctly.

I usually fix it that I look for "Regex must use string named capture groups instead of numeric" string with PHPStorm. It shows `RequireStringRegexMatchKeyRule`. Then there is link to `RequireStringRegexMatchKeyRuleTest` tests. There are tests fixture that shows fixed/broken code, to demonstrate how it should be fixed.

**Comment by TomasVotruba** [comment]
I've upgraded to Symplify and fixes static reports in https://github.com/rectorphp/rector/pull/5655

**Comment by TomasVotruba** [comment]
Cherry picked in https://github.com/rectorphp/rector/pull/5656

**Pull request closed without merging**
