### PR TITLE
[DX] Architecture rules respect namespace

### PR DESCRIPTION
**Pull request by dobryy**

### CODE REVIEW

**Comment by dobryy** [comment]
@TomasVotruba Ready, but there is some issue with some composer library... that is why the pipeline fails...

**Comment by TomasVotruba** [comment]
It's because https://github.com/nikic/PHP-Parser/commit/aaee038b912e567780949787d5fe1977be11a778

Lockdown in `composer.json` to lower php-parser should help

**Comment by dobryy** [comment]
@TomasVotruba, ready for merging.

**Comment by TomasVotruba** [comment]
Thank you!

So clean :)


Rector code starts to smell like just washed laundry :lab_coat:  in the sunrise :white_flower:

**Pull request merged**
