### PR TITLE
[Meta] Add Monorepo Builder

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba I applied monorepo builder, and tried run locally with `--dry-run`, it got the following output:

Screen Shot 2021-02-24 at 20 52 01

Please verify if that is correct. Thank you.

**Comment by TomasVotruba** [comment]
Thanks! 
The first steps seem not useful here, only in monorepo.
What do you think?

**Comment by samsonasik** [comment]
Yes, it seems, I removed the first step so it got the following output:

Screen Shot 2021-02-24 at 22 29 39

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
