### PR TITLE
Performance improvement: use [] comparison check instead of count($var) for check array has data when possible

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

### CODE REVIEW

**Comment by TomasVotruba** [comment]
CI needs passing.

What is the performance relative improvement on how big project?

**Comment by samsonasik** [comment]
I updated with `[]` comparison check. Well, mostly micro optimization, other thing, it make consistent with others, searched with `[]` comparison in the `src` directory.

**Comment by TomasVotruba** [comment]
We need data to do performance optimizations. Otherwise it's just guessing and random changes in the code, that might only add extra manual work for contributors, without any proven added value. 

To make it work, there would have to be person that does PRs like these after every new line of code is added.

**If you can provide data and make a Rector rule that do these change automatically**, I'd be happy to merge it.

**Comment by TomasVotruba** [comment]
Closing for now, since the Rector rule is needed. 
Feel free to re-open new PR with one. 

Thanks for understanding

**Pull request closed without merging**
