### PR TITLE
Ignore PHPStorm .idea folder

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by mssimi** [comment]
What about ignoring .idea in your git global ignore config?

**Comment by carusogabriel** [comment]
@mssimi Can I do it? :open_mouth:

**Comment by grogy** [comment]
@carusogabriel yes, it is possible. You can read it in [documentation](https://git-scm.com/docs/gitignore) and inspire in [GitHub repository](https://github.com/github/gitignore)

**Comment by TomasVotruba** [comment]
@carusogabriel Could you always provide some reasoning for PRs, like what issue do you struggle with?
There might be some better solutions, but it's hard to that tell without knowing your troubles.

Btw, global gitignore is way to go :)

Here is the solution I use: https://help.github.com/articles/ignoring-files/#create-a-global-gitignore
It will just create a file you need to edit:

```bash
git config --global core.excludesfile ~/.gitignore_global
echo ".idea" > ~/.gitignore_global
```

**Pull request closed without merging**
