### PR TITLE
[Naming] Fixes #4621 : Skip rename when after rename has numeric in first char

### LINKED ISSUE #4621: Variable cannot begin with a number in PHP
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector dev-master@765862c (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/b983bbd2-3e35-4e32-af6c-f4ae1f2a130b

## Expected Behaviour

`$_3p` variable shouldn't be changed to `$3p`, because this is not a valid variable name in PHP (tested on PHP 7.3).

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
skip one char underscore as well : `$_`

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
