### PR TITLE
[DeadCode] Handle RemoveDefaultArgumentValueRector on removal default argument on not last argument

### LINKED ISSUE #5975: RemoveDefaultArgumentValueRector dropping arguments that aren't last
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

`RemoveDefaultArgumentValueRector` drops arguments that have the default value and aren't last.

E.g. the minimal code below has different behaviour when the `$b` and `$c` arguments to `doStuff()` are true, however `RemoveDefaultArgumentValueRector` drops the argument to `$b` (replacing it with the argument to `$c`) if it finds a call to `doStuff()` with the default value for `$b`.

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/298459d2-590f-4fc3-af21-ae1370efa305

```php
<?php

function doStuff($a = false, $b = false, $c = false, $d = false) {
    $level = getLevelFromSomewhere();
    
    if ($level == "a" && !$a) return false;
    if ($level == "b" && !$b) return false;
    if ($level == "c" && !$c) return false;
    if ($level == "d" && !$d) return false;
}

doStuff(true, false, true, false);
```

### Responsible rules

* `RemoveDefaultArgumentValueRector`

## Expected Behavior

```php
<?php

function doStuff($a = false, $b = false, $c = false, $d = false) {
    $level = getLevelFromSomewhere();
    
    if ($level == "a" && !$a) return false;
    if ($level == "b" && !$b) return false;
    if ($level == "c" && !$c) return false;
    if ($level == "d" && !$d) return false;
}

doStuff(true, false, true);
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5975

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by JulianCBC** [comment]
I hadn't looked at the code before now, but this seems a bit over complicated.

(Also, I must complement you on sorting this out so fast!)

Would something like this work:

```php
<?php

for ($key = count($node->args) - 1; $key--; $key >= 0) {
    if (! isset($defaultValues[$key])) {
        break;
    }

    if ($this->nodeComparator->areNodesEqual($defaultValues[$key], $arg->value) {
        $keysToRemove[] = $key;
    } else {
        break;
    }
}

return $keysToRemove;
```

**Comment by samsonasik** [comment]
@JulianCBC your approach is not working, I tried that and cause error in other fixtures tests. 

Please provide another pull request if you have another approach, thank you.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by JulianCBC** [comment]
Ok, fair enough then. I'm not objecting to your approach - I just think it could be simpler.

**Comment by samsonasik** [comment]
got another failing test case not in last very first set equal default https://github.com/rectorphp/rector/pull/5982/commits/27847a4c2ee07bbbb89c84678d1ca727de85d485

**Comment by samsonasik** [comment]
fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
