### PR TITLE
[Symfony Code Quality] Fixes EventListenerToEventSubscriberRector do not replace method call properly

### LINKED ISSUE #4899: EventListenerToEventSubscriberRector do not replace method call properly
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.8.56              |
| Installed as   | composer dependency                      |

## Minimal PHP Code Causing Issue

A single Symfony listener configured as this:
```yaml
# First example
App\EventListener\FooListener:
    tags:
      - { name: kernel.event_listener, event: event.success, method: onSuccess }
      - { name: kernel.event_listener, event: event.completed, method: onCompleted }

# second example
App\EventListener\BarListener:
    tags:
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: kernel.event_listener, event: event.completed, method: onCompleted }
```

## Expected Behaviour

Rector make the classes implementing the interface properly for both cases.
It adds the `getSubscribedEvents` method in the first case, not in the second.

```php
# first example
    public static function getSubscribedEvents(): array
    {
        return [
            'event.success' => 'onSuccess',
            'event.completed => 'onSuccess',
        ];
    }

# second example
// No code generated but the class does implements the interface
``` 

Let me know if you need more information.

Thank you for this awesome tools which helps me a lot! :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #4899

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
