### PR TITLE
Add Drupal logo + link to Drupal Rector rules to README.md

### PR DESCRIPTION
**Pull request by shaal**
Drupal has been using Rector to successfully upgrade massive amount of Drupal modules, including a bot that apply Rector rules and create patches for all available projects.

We'd like to add Drupal's logo (and a link to Drupal Rector rules) to Rector's README file.

Preview screenshot:
image

### CODE REVIEW

**Comment by TomasVotruba** [comment]
You can move the logo on first line (between Laravel and Symfony?), as the Drupal Rector set is very rich and activelly developed.

**Comment by shaal** [comment]
I moved Twig logo to first line, to optimize space (otherwise 3 lines are needed to display the logos).

Is that ok? Or should I keep the order of logos the same way you described it?

**Comment by TomasVotruba** [comment]
This look great! Thanks for the screenshot, it's easy to check it for me

**Comment by shaal** [comment]
Thank you!

**Pull request merged**
