### PR TITLE
[test] String class name to class constant rector ignore array keys 1539

### PR DESCRIPTION
**Pull request by Aerendir**
Issue #1539.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
First commit says, that keys are ignored.

Would you add test with namespaces class that proves that?

**Comment by Aerendir** [comment]
@TomasVotruba no, it is not clear my comment: it says that if I call `$var['Exception']`, then I get the `\Exception` object.

But instead, the key is transformed into `$var[\Exception::class]` and this is not correct: it should remain `$var['Exception']`, also if `Exception` is the name of an existent class.

**Comment by TomasVotruba** [comment]
> But instead, the key is transformed into $var[\Exception::class]

This is expected behavior.

```diff
'SomeClass' => new SomeClass

**Comment by Aerendir** [comment]
@TomasVotruba , in my case it is not intended as the name of a class but, instead, as a key by which I can get the Exception.

Maybe I need to change the name of my key to something like `ExceptionObj` 🤔

**Comment by TomasVotruba** [comment]
Why is it upper class anyway? How do you use it?

**Comment by Aerendir** [comment]
@TomasVotruba there is no particular reason: I simply wrote it this way 😅.

You are right: I can simply switch to lowercase, am I right?

**Comment by TomasVotruba** [comment]
I see :) lowercase would be better in this particular case. We'll see how it's used in the wild

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/rectorphp/rector/pull/1565

Thanks for the test case

**Pull request closed without merging**
