### PR TITLE
[PHP 7.3] Register existing ContinueToBreakInSwitchRector in PHP 5.2 set to PHP 7.3 config set

### PR DESCRIPTION
**Pull request by samsonasik**
As it actually still working in php 5.2, while in php 7.3, it already error https://3v4l.org/1Nnti. Another solution is move the `ContinueToBreakInSwitchRector` to `Php73` set.

### CODE REVIEW

**Comment by samsonasik** [comment]
Alternative : https://github.com/rectorphp/rector/pull/5821

**Comment by samsonasik** [comment]
PHPStan error caused by rectify seems unrelated.

**Comment by TomasVotruba** [comment]
The return adding should be fixed. It's probably related to `AddArrayParamDocTypeRector`
Could you check it?

**Comment by samsonasik** [comment]
I will try.

**Comment by samsonasik** [comment]
@TomasVotruba do you prefer this PR or the alternative PR https://github.com/rectorphp/rector/pull/5821 ?

**Comment by TomasVotruba** [comment]
Both seem ok

**Comment by samsonasik** [comment]
It seems caused by `AddArrayReturnDocTypeRector`:

```bash
in/rector process packages/comments/tests/CommentRemover/CommentRemoverTest.php --dry-run                          
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ! [NOTE] Ruleset contains 8 rules that need "--clear-cache" option to analyse full project                             

1 file with changes
===================

1) packages/comments/tests/CommentRemover/CommentRemoverTest.php

    ---------- begin diff ----------
--- Original
+++ New
@@ @@
         $this->assertNotSame($expectedContent, $originalContent);
     }

+    /**
+     * @return Iterator<mixed, SmartFileInfo[]>
+     */
     public function provideData(): Iterator
     {
         return StaticFixtureFinder::yieldDirectory(__DIR__ . '/Fixture', '*.php.inc');
    ----------- end diff -----------


Applied rules:

 * Rector\PostRector\Rector\NameImportingPostRector
 * Rector\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector
```

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :tada:

**Pull request merged**
