### PR TITLE
do not override printing files with previous stmts if possible

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@janmikes I got the same error :) :party: 

error_tokens

**Comment by JanMikes** [comment]
Hehe, should we celebrate that we have encounter same errors? 😄

**Comment by TomasVotruba** [comment]
> Hehe, should we celebrate that we have encounter same errors? smile

Yes, because that's 50 % of the fix :)

**Comment by TomasVotruba** [comment]
If found little bit hacky, but error-proof solution. It always uses previous formatting, if possible. But still works if not possible.

**Pull request merged**
