### PR TITLE
[Test] Add utils/ to whitelist test coverage

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
temporary trigger coverage on pull request to ensure coverage generated for `utils/`

**Comment by samsonasik** [comment]
It seems works, just coverage reduced to `76.45%`

Screen Shot 2020-12-29 at 2 33 47 PM

**Comment by samsonasik** [comment]
@TomasVotruba I think it is ready

**Comment by TomasVotruba** [comment]
Thank you

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Btw, coverage is now superslow and it prolongs waiting for the :green_circle:  on merge to master. 

Also it's not neccesary to see coverage on every merge.
What do you think about moving into weekly pull-requests?

**Comment by samsonasik** [comment]
Yes, weekly seems ok

**Pull request merged**
