### PR TITLE
Update 1_Bug_report.md

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by OskarStark** [comment]
Looks like this PR should be merged here

**Comment by OskarStark** [comment]
There is not .github folder in src

**Comment by TomasVotruba** [comment]
This repository is build from here:
https://github.com/rectorphp/rector-src/tree/main/build/target-repository

I've added your change as it bothered me for a while now too :)

**Comment by OskarStark** [comment]
Thanks Tomas!

**Pull request closed without merging**
