### PR TITLE
Add post run name imports

### PR DESCRIPTION
**Pull request by TomasVotruba**
Do you want to forget running `ImportFullyQualifiedNamesRector` after every class/name change?

## Enable Auto Import

```yaml
# rector.yaml
parameters:
    auto_import_names: true # false by default
```

## Before

```php
namespace Rector\Renaming;

class ClassToNewWithPostImport
{
    public function run()
    {
        return new \Rector\Renaming\FreshlyChangeClass();
    }
}
```

## After setting `auto_import_names` = `true`

```php
namespace Rector\Renaming;

use Rector\Renaming\FreshlyChangeClass;

class ClassToNewWithPostImport
{
    public function run()
    {
        return new FreshlyChangeClass();
    }
}
```

### CODE REVIEW

**Comment by benr77** [comment]
Can you configure this option to ignore global namespace imports?

i.e. do NOT convert `\DateTime()` in to `DateTime()` with `use DateTime;`

I think this would be a nice feature.
Thanks

**Comment by TomasVotruba** [comment]
Sure, propose PR

**Comment by benr77** [comment]
Sorry I didn't notice that you can already do this simply using:
```
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector:
    $shouldImportRootNamespaceClasses: false
```

**Comment by TomasVotruba** [comment]
Yes, that will also work

**Comment by clxmstaab** [comment]
I tried the above example but it didn't work.. how can I activate the mentioned option via rector.yml

```
# rector refactoring automation util: https://github.com/rectorphp/rector
parameters:
  auto_import_names: true
  php_version_features: '7.0'
  autoload_paths:
    - 'phpstan-bootstrap.php'
services:
  Rector\TypeDeclaration\Rector\Property\CompleteVarDocTypePropertyRector:
    $shouldImportRootNamespaceClasses: false
```

leads to 

```
$ rector process models --set php70


Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Invalid service "Rector\TypeDeclaration\Rector\Property\CompleteVarDocTypePropertyRector": method "__construct()" has no argument named "$shouldImportRootNamespaceClasses". Check your service definition. in C:\Users\mstaab\AppData\Roaming\Composer\vendor\symfony\dependency-injection\Compiler\ResolveNamedArgumentsPass.php:65
Stack trace:
#0 C:\Users\mstaab\AppData\Roaming\Composer\vendor\symfony\dependency-injection\Compiler\AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\ResolveNamedArgumentsPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 C:\Users\mstaab\AppData\Roaming\Composer\vendor\symfony\dependency-injection\Compiler\ResolveNamedArgumentsPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 C:\Users\mstaab\AppData\Roaming\Composer\vendor\symfony\dependency-injection\Compiler\AbstractRecursivePass. in C:\Users\mstaab\AppData\Roaming\Composer\vendor\symfony\dependency-injection\Compiler\ResolveNamedArgumentsPass.php on line 65
```

**Pull request merged**
