### PR TITLE
[Downgrade PHP 7.3] List reference assignment

### LINKED ISSUE #4315: [Downgrade PHP 7.3] `list()` and array destructuring reference assignment
# Feature Request

Downgrade new feature from PHP 7.3 to its equivalent PHP 7.2 code. [RFC with explanation](https://wiki.php.net/rfc/list_reference_assignment)

This feature must be handled with care. Check in the RFC all the nuances, and if there is any instance where downgrading is not possible, identify that case in the rule and throw a `DowngradeNotPossibleException`.
 
## Diff 

```diff
$array = [1, 2];
-list($a, &$b) = $array;
+$a = $array[0];
+$b =& $array[1];

/* Note; []= syntax works the same, so the following is functionally equivalent to the example */
-[$a, &$b] = $array;
+$a = $array[0];
+$b =& $array[1];
```

### PR DESCRIPTION
**Pull request by leoloso**
Fixes #4315

### CODE REVIEW

**Comment by leoloso** [comment]
@TomasVotruba I need your input here.

I'm checking if this use case is downgradable:

```php
$array = [[1, 2], [3, 4]];
foreach ($array as list(&$a, $b)) {
    $a = 7;
}
var_dump($array)
/*
array(2) {
  [0]=>
  array(2) {
    [0]=>
    int(7)
    [1]=>
    int(2)
  }
  [1]=>
  array(2) {
    [0]=>
    &int(7)
    [1]=>
    int(4)
  }
}
*/
```

According to the [RFC](https://wiki.php.net/rfc/list_reference_assignment) this is not downgradable:

> The predominant advantage of adding support for this is that it allows you to use reference assignment for multiple variables at once, **which is not currently possible**. [...] the advantage here is that **you can reference assign some, but not all of the variables in list()**.

After running this PHP code, the reference exists on `$array[1][0]` since `$a` is still in scope after the `foreach()`. This part **cannot be reproduced in PHP 7.2** 

If we didn't care about the references, but only about the final values, this is doable:

```php
$array = [[1, 2], [3, 4]];
foreach ($array as &$item) {
    $item[0] = 7;
}
dump($array);
/*
[0]=>
  array(2) {
    [0]=>
    int(7)
    [1]=>
    int(2)
  }
  [1]=>
  &array(2) {
    [0]=>
    int(7)
    [1]=>
    int(4)
  }
}
*/
```

Notice how the reference at the end points to the 2nd item in the array, and not to the 1st element of that item.

Hence, the final references cannot be recreated, but the values can.

So, what to do? I see 2 options:

- Downgrade it, explaining this situation clearly in the documentation
- Throw a `DowngradeNotPossibleException` (#4316)

Or maybe a bit more complex:

- Downgrade it, unless variable `$a` is still referenced after running the code, if so throw `DowngradeNotPossibleException`

What do you think?

**Comment by leoloso** [comment]
I thought a better alternative:

- Allow to downgrade the code, if enabled by a configuration entry `DANGEROUSLY_DOWNGRADE_LIST_REFERENCE_ASSIGNMENT_IN_FOREACH`
- By default, it is disabled
- If disabled, and that code is found, throw a `DangerousDowngradePossibleByConfigurationOnlyException`, and there it shows the error message explaining that values are recreated, but references are not

**Comment by leoloso** [comment]
Or maybe we could create a new set `DANGEROUS_DOWNGRADE_PHP73`, and extract this as a separate rule `DangerousDowngradeListReferenceAssignmentInsideForeachRector`

**Comment by leoloso** [comment]
Otherwise this rule is ready. So I'll remove it from draft, and you can decide if to already ship it

**Comment by TomasVotruba** [comment]
I think we can go for low hanging fruit now and test it in the wild. Just not to waste time on problem that might have 1 person from million.

If it will cause troubles, we can improve it :)

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by leoloso** [comment]
Ok, but we need to discuss this as a concept. This is just one example of a functionality that cannot be downgraded without side-effects. I actually think that having a set `DANGEROUS_DOWNGRADE_PHP73` is a pretty good idea. We'll also have `DANGEROUS_DOWNGRADE_PHP74` and `DANGEROUS_DOWNGRADE_PHP80` too, for instance for `WeakMap` and others.

We can talk about it on our next meeting.

Btw, if you can generate a tag that would be cool, so I can already publicize this new set

**Comment by TomasVotruba** [comment]
Set names makes sense :+1: 

I'll release it today

**Pull request merged**
