### PR TITLE
[CodeQuality] Handle Named Argument in ThrowWithPreviousExceptionRector

### LINKED ISSUE #5697: [ThrowWithPreviousExceptionRector] Previous exception duplication while named arguments used
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.31 (invoke `vendor/bin/rector --version`)              |
| Installed as   | composer dependency                           |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/81c701e0-a2c6-4f5b-93f0-486e87d37d64

```diff
@@ -7,7 +7,7 @@
 		try {
             $this->run();
         }catch(\Throwable $e) {
-            throw new LogicException('Some exception', previous: $e);
+            throw new LogicException('Some exception', previous: $e, $e);
         }
     }
 }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5697

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
@TomasVotruba the `rector-ci (rules)` seems hanging : 

```bash
rector-ci (rules) Expected — Waiting for status to be reported
```

other checks are passed 🎉 it is ready for review.

**Comment by TomasVotruba** [comment]
The Rector job is now narrowed, as static reflections on few places and we need to test it better.

I've updated the jobs to paths.

Thank you

**Pull request merged**
