### PR TITLE
Improve Action Inject to work with container

### PR DESCRIPTION
**Pull request by TomasVotruba**
### Todo

- [x] make all Kernel services public for service provider
    - kernel class extension?
    - [compiler pass](https://github.com/Symplify/PackageBuilder#9-make-services-public-for-tests-only) private injection?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@mssimi @OndraM @grogy 
Any ideas how to add comiler pass to external kernel? Or another way to make all services public?

I'm lost :(

**Comment by TomasVotruba** [comment]
@mssimi @OndraM @grogy @EdoBarnas 
Any ideas how to add comiler pass to external kernel? Or another way to make all services public?

I'm lost :(

**Comment by TomasVotruba** [comment]
Huge thanks to @EdoBarnas 

https://github.com/symfony/symfony/blob/226e2f3949c5843b67826aca4839c2c6b95743cf/src/Symfony/Bundle/FrameworkBundle/Command/ContainerDebugCommand.php#L200-L203

**Comment by EdoBarnas** [comment]
Nice work!

**Comment by TomasVotruba** [comment]
Your work, I've spent 4 hours on this with no success. And your idea solved in it 15 minutes :)

**Pull request merged**
