### PR TITLE
[Utils] Run validate-fixture-namespace/classname to rules/ directories

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
on `cakephp`, it applied with some manual changes as it modify `use` statement location.

**Comment by samsonasik** [comment]
on coding-style, it applied with some manual changes as it class already exists.

**Comment by samsonasik** [comment]
some false positive in `coding-style` : 

```bash
There were 3 failures:

1) Rector\CodingStyle\Tests\Rector\Namespace_\ImportFullyQualifiedNamesRector\ImportFullyQualifiedNamesRectorTest::test with data set #22 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules/coding-style/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/many_imports.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 namespace Rector\CodingStyle\Tests\Rector\Namespace_\ImportFullyQualifiedNamesRector\Fixture;
 
-use Rector\CodingStyle\Tests\Rector\Namespace_\ImportFullyQualifiedNamesRector\Source\Stock\Query;
 use InvalidArgumentException;
+use Rector\CodingStyle\Tests\Rector\Namespace_\ImportFullyQualifiedNamesRector\Source\Connection;
 final class StockRepository
 {
-    public function filter(Query $query)
+    public function filter(Stock\Query $query)
     {
-        /** @var Query $query */
+        /** @var Stock\Query $query */
         $query = 5;
 
         if (!($query instanceof Stock\Querying\Query)) {

/home/runner/work/rector/rector/packages/testing/src/PHPUnit/AbstractRectorTestCase.php:486
/home/runner/work/rector/rector/packages/testing/src/PHPUnit/AbstractRectorTestCase.php:308
/home/runner/work/rector/rector/rules/coding-style/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportFullyQualifiedNamesRectorTest.php:27

2) Rector\CodingStyle\Tests\Rector\String_\UseClassKeywordForClassNameResolutionRector\UseClassKeywordForClassNameResolutionRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/Fixture/mutiple_occurrences_in_one_string.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     public function run()
     {
-        return \Rector\CodingStyle\Tests\Rector\String_\UseClassKeywordForClassNameResolutionRector\Fixture\MultipleOccurrencesClass::class . '::staticCall() && ' . \Rector\CodingStyle\Tests\Rector\String_\UseClassKeywordForClassNameResolutionRector\Fixture\MultipleOccurrencesClass::class . '::staticCall()';
+        return 'Rector\CodingStyle\Tests\Rector\String_\UseClassKeywordForClassNameResolutionRector\Fixture\MultipleOccurrencesClass::staticCall() && Rector\CodingStyle\Tests\Rector\String_\UseClassKeywordForClassNameResolutionRector\Fixture\MultipleOccurrencesClass::staticCall()';
     }
 }

/home/runner/work/rector/rector/packages/testing/src/PHPUnit/AbstractRectorTestCase.php:486
/home/runner/work/rector/rector/packages/testing/src/PHPUnit/AbstractRectorTestCase.php:308
/home/runner/work/rector/rector/rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/UseClassKeywordForClassNameResolutionRectorTest.php:19

3) Rector\CodingStyle\Tests\Rector\String_\UseClassKeywordForClassNameResolutionRector\UseClassKeywordForClassNameResolutionRectorTest::test with data set #2 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/Fixture/fixture.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     public function run()
     {
-        return '<?php if (' . \Rector\CodingStyle\Tests\Rector\String_\UseClassKeywordForClassNameResolutionRector\Fixture\SomeClass::class . '::staticCall()) { ?>';
+        return '<?php if (Rector\CodingStyle\Tests\Rector\String_\UseClassKeywordForClassNameResolutionRector\Fixture\SomeClass::staticCall()) { ?>';
     }
 }

/home/runner/work/rector/rector/packages/testing/src/PHPUnit/AbstractRectorTestCase.php:486
/home/runner/work/rector/rector/packages/testing/src/PHPUnit/AbstractRectorTestCase.php:308
/home/runner/work/rector/rector/rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/UseClassKeywordForClassNameResolutionRectorTest.php:19

FAILURES!
Tests: 3363, Assertions: 6319, Failures: 3, Warnings: 1, Skipped: 138.
Error: Process completed with exit code 1.

```

**Comment by samsonasik** [comment]
coding-style fixture fixed.

**Comment by samsonasik** [comment]
dead-code fixture fixed.

**Comment by samsonasik** [comment]
psr-4 fixture fixed.

**Comment by samsonasik** [comment]
removing-static fixture fixed.

**Comment by samsonasik** [comment]
renaming fixture fixed with exclude various namespacing check.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you, amazing work :+1:

**Pull request merged**
