### PR TITLE
WIP: Testcase for unnecessary PHPdoc modification

### PR DESCRIPTION
**Pull request by C0pyR1ght**
This PR tries to provide Testcases for https://github.com/rectorphp/rector/issues/2994 and https://github.com/rectorphp/rector/issues/2991

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Better use explicit names... e.g. annotation_with_value_surrounded_by_space

**Comment by C0pyR1ght** [comment]
I just picked a random one of your existing test cases and added the spaces. Rector will always change the phpdoc if it is not exactly in the required syntax. This applies to braces, spaces, pipe etc

**Comment by TomasVotruba** [comment]
Do you think that's all covered from issues there?

**Comment by C0pyR1ght** [comment]
I suppose that all these different unnecessary doc changes come from one single source of failure. This thesis is also supported by the fact that this bug seems appear on all cases that we pointed out in the issues between https://github.com/rectorphp/rector/compare/v0.6.13...v0.7.3

**Comment by C0pyR1ght** [comment]
I think the next step would be to further investigate on the specific version this bug first occured

**Comment by staabm** [comment]
I would suggest to `git bisect` to discover the offending commit

**Comment by C0pyR1ght** [comment]
> I would suggest to `git bisect` to discover the offending commit

great idea. I will try that tomorrow

**Comment by TomasVotruba** [comment]
The doc printing was added for each node in https://github.com/rectorphp/rector/pull/2775/files

That lead to exposition of such bugs, where format preserving is not finished yet. Now the goal is to cover these edge cases, so format preserving is close to reality as possible. Saying that, each php doc node has to check for possible spaces and try to deal with them.

**Comment by C0pyR1ght** [comment]
In this case i have to correct my assumption that this testcase is representative for everything. If your solution this is to ignore spaces we have to come up with further cases for other characters like `()`

**Comment by TomasVotruba** [comment]
The goal is to preserve format as much as possible, without going crazy :D

**Comment by C0pyR1ght** [comment]
Okay, then I will just look into the cases mentioned in the issues

**Comment by C0pyR1ght** [comment]
These three should be it. The breaking characters are spcaes, linebreaks and round brackets. Some other Characters I tried, had no negative impact.

**Comment by TomasVotruba** [comment]
Thank you!

Would you take care of it with my guidance?

**Comment by TomasVotruba** [comment]
Could you rebase on current master? I wonder what has changed now

**Comment by C0pyR1ght** [comment]
had to open a new PR because i deleted the fork in the meantime
see https://github.com/rectorphp/rector/pull/3126

**Pull request closed without merging**
