### PR TITLE
Fix sync releases with rector-prefixed

### PR DESCRIPTION
**Pull request by Lctrs**
In combination with https://github.com/rectorphp/rector-prefixed/pull/7

### CODE REVIEW

**Comment by Lctrs** [comment]
@TomasVotruba I tested it on my fork. Works well.

**Comment by Lctrs** [comment]
Note that we could also use the [release](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#release-event-release) event to trigger an auto release in `rector-prefixed` only when a new release has been published in this repo.

**Comment by TomasVotruba** [comment]
No change should be needed from at `rectorphp/rector-prefixed`

**Comment by Lctrs** [comment]
The PR in `rector-prefixed` is not needed stricto sensu. It's just here to ease maintenance by automating the release. We could also just create a draft release there that you can manually publish if you want more control.

**Comment by TomasVotruba** [comment]
The release of both packages worked from here, just the tag was missed when migrated from Travis to Github Actinons

**Comment by TomasVotruba** [comment]
Let's give it a try

**Pull request merged**
