### PR TITLE
Failing test for #447

### PR DESCRIPTION
**Pull request by carusogabriel**
As requested https://github.com/rectorphp/rector/issues/447#issuecomment-385260542

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Just to be sure we didn't remove a test case, could you keep the old method and just add newline?

**Comment by carusogabriel** [comment]
Why? I can't see anything been losing with this change. If it is the case, we need to have a static call in ever TestCase of PHPUnit Rectors and that'd be a overengineer :(

**Comment by TomasVotruba** [comment]
Because this PR removes a test.
We need to add it only, removing tests doesn't help. Like this:

```diff
  $this->assertFalse(! ($something === false));
  $this->assertTrue(! $something);
+self::assertTrue(! $something);
```

**Comment by carusogabriel** [comment]
@TomasVotruba Sure, I'll work on that, thanks for the tip.

**Comment by TomasVotruba** [comment]
Fixed :+1:

**Comment by carusogabriel** [comment]
@TomasVotruba Thanks

**Pull request merged**
