### PR TITLE
[Renaming] Handle RenameClassRector to avoid duplicate interface definition

### PR DESCRIPTION
**Pull request by samsonasik**
Close #5401

### CODE REVIEW

**Comment by samsonasik** [comment]
Removing the duplication definition seems need to be handled in `BetterStandardPrinter` as it seems happen on re-define the interface:

```bash
1) Rector\Renaming\Tests\Rector\Name\RenameClassRector\RenameClassRectorTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules/renaming/tests/Rector/Name/RenameClassRector/Fixture/do_not_implement_twice.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 <?php
 
 interface MyBazInterface {};
+interface MyBazInterface {};
```

**Comment by samsonasik** [comment]
fixed by handling definition duplication on BetterStandardPrinter

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Added check duplication statement only in ClassLike and FunctionLike

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
