### PR TITLE
Resolve fixed version of nikic/php-parser

### LINKED ISSUE #4198: nikic/php-parser is pinned to exact version 4.9.0
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |0.8.0 and up              |
| Installed as   | composer dependency                      |

Twelve days ago the version for nikic/php-parser [was pinned ](https://github.com/rectorphp/rector/commit/989c3f41682afd92c7699835f43f033f552f1f7b#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L22)to strict 4.9.0 before this was `^4.9` This is causing issues 
with systems that are more up to date as version 4.9.1 was released 11 days ago.

## Minimal PHP Code Causing Issue
No code is affected, but to reproduce execute the following commands:
```bash
Laravel new test
cd test
composer require phpunit/phpunit:"^9.0" --dev --update-with-dependencies
composer require nunomaduro/collision:"^5.0" --dev --update-with-dependencies
composer require pestphp/pest --dev
composer require pestphp/pest-plugin-laravel --dev && php artisan pest:install
composer require rector/rector
```

Following the last command the error output is:
```bash
Using version ^0.8.6 for rector/rector
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nikic/php-parser (locked at v4.9.1) -> satisfiable by nikic/php-parser[v4.9.1].
    - rector/rector 0.8.x-dev requires nikic/php-parser 4.9.0 -> satisfiable by nikic/php-parser[v4.9.0].
    - rector/rector v0.8.6 requires nikic/php-parser 4.9.0 -> satisfiable by nikic/php-parser[v4.9.0].
    - Conclusion: don't install nikic/php-parser v4.9.0
    - Installation request for rector/rector ^0.8.6 -> satisfiable by rector/rector[0.8.x-dev, v0.8.6].


Installation failed, reverting ./composer.json to its original content.
```

## Expected Behaviour
I would expect rector to be compatible with nikic/php-parser `^4.9`

### PR DESCRIPTION
**Pull request by DannyvdSluijs**
Resolves #4198

### CODE REVIEW

**Comment by TomasVotruba** [comment]
CI is failing

**Comment by TomasVotruba** [comment]
```bash
UPDATE_TESTS=1 vendor/bin/phpunit
```

**Comment by samsonasik** [comment]
@DannyvdSluijs I've cherry-picked your commit and continue the work at PR https://github.com/rectorphp/rector/pull/4228

**Comment by samsonasik** [comment]
I tried continue with run  `UPDATE_TESTS=1 vendor/bin/phpunit` in PR https://github.com/rectorphp/rector/pull/4228, now, the error is on PHP 7.2 tests https://github.com/rectorphp/rector/pull/4228/checks?check_run_id=1117741622

**Pull request closed without merging**
