### PR TITLE
Failing tests

### PR DESCRIPTION
**Pull request by enumag**
Ref #1209

### CODE REVIEW

**Comment by enumag** [comment]
I'm trying to run the tests locally (on master first) but I'm getting this error. Did you encounter this yourself? (using ubuntu x64)

```
> vendor/bin/ecs check bin packages src tests utils
EasyCodingStandard v5.4.16
Config file: /home/enumag/Projects/rector/rector/ecs.yaml

 [OK] No errors found. Great job - your code is shiny in style!                 

> phpunit
PHPUnit 8.0.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.3-1+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.7.0
Configuration: /home/enumag/Projects/rector/rector/phpunit.xml

...............................................................  63 / 342 ( 18%)
............................................................... 126 / 342 ( 36%)
............................................................... 189 / 342 ( 55%)
............................................................... 252 / 342 ( 73%)
...............................PHP Warning:  include(/home/enumag/Projects/rector/rector/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /home/enumag/Projects/rector/rector/vendor/composer/ClassLoader.php on line 444
```

**Comment by TomasVotruba** [comment]
Disable Xdebug?

**Comment by TomasVotruba** [comment]
I'll ping the Travis to see if tests fail aleady

**Comment by TomasVotruba** [comment]
It works, thanks

**Pull request merged**
