### PR TITLE
[Php71] Skip AssignArrayToStringRector on assign var not defined before

### LINKED ISSUE #5983: Incorrect behavior of AssignArrayToStringRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/fa5a7a93-ef94-4fd6-a2b0-cc4be813f407

```php
<?php declare(strict_types=1);

class Demo
{
    public function demo(): array {
        $array[] = 'foo';
        $array[] = 'bar';

        return $array;
    }
}
```

### Responsible rules

* `AssignArrayToStringRector`

## Expected Behavior

The code should not be changed, as this is in fact completely valid (even though [discouraged](https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying) by php manual). 

Furthermore, the change suggested by `AssignArrayToStringRector` (add `$array = (array) $array;` before the first assignment) will make the code throw notices (`PHP Notice:  Undefined variable: array`).

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5983

### CODE REVIEW

**Comment by OndraM** [comment]
👍

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
