### PR TITLE
Use equal sign instead of colon in Symfony routing

### LINKED ISSUE #3225: Couldn't find constant expose:true
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.7.17              |
| Installed as   | composer dependency                       |

Rector changes options={"expose"=true} in @ Route annotation, causes error:

[Semantical Error] Couldn't find constant expose:true, method App\Controller\API\AccountingController::contact() in .... 
Make sure annotations are installed and enabled.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/e0fc28be-0156-41a9-bc98-5ccabf9b76d3

## Expected Behaviour

Rector should not touch options={"expose"=true} in @Route annotation.

Expose=true comes from FOSJsRoutingBundle.

### PR DESCRIPTION
**Pull request by stephanvierkant**
* Closes #3225
* Closes #3241

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I looked at a code and it seems there are multiple issues at once. I recommend sending 1 PR per issues.

I'd love to have the `=` first, as it influences the most users right now.

**Comment by stephanvierkant** [comment]
Rector removes the `"` because it assumes the options in the annotation are in json format, while it isn't.

`\Rector\BetterPhpDocParser\PhpDocNode\AbstractTagValueNode::printArrayItem` creates a JSON string and hacking this (stop removing the `"`) doesn't feel right. WDYT?

**Comment by TomasVotruba** [comment]
Not sure what is the question.

**Comment by stephanvierkant** [comment]
PrintArrayItem now returns a JSON string. But the `@Routing` options expect not a JSON format. So should this method be changed?

**Comment by TomasVotruba** [comment]
I'm change for better :+1:

**Comment by stephanvierkant** [comment]
Master changed significant, so can't complete this PR.

**Comment by TomasVotruba** [comment]
Feel free to delete fork, fork again and to re-open new one. 
There are mostly test fixtures in the PR, should be doable.

**Pull request closed without merging**
