### PR TITLE
[Downgade PHP 7.1] Add DowngradeNegativeStringOffsetToStrlenRector

### LINKED ISSUE #4197: [Downgrade PHP 7.1] Negative string offsets
# Feature Request

Downgrade new feature from PHP 7.1 to its equivalent PHP 7.0 code. [Feature description](https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.support-for-negative-string-offsets)

To replace the negative offset, obtain the equivalent positive offset
 
## Diff 

```diff
-var_dump("abcdef"[-2]);
+var_dump("abcdef"[strlen("abcdef")-2]);
-var_dump(strpos("aabbcc", "b", -3));
+var_dump(strpos("aabbcc", "b", strlen("aabbcc")-3));
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #4197

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by simivar** [comment]
Hey @samsonasik, "Fixes #4197" should be in the PR description, not the title :)

**Comment by samsonasik** [comment]
@simivar  updated

**Comment by samsonasik** [comment]
rebased and registered to downgade-php71 config set.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
