### PR TITLE
Allow later versions of nette/utils

### PR DESCRIPTION
**Pull request by sanmai**
This should be a no brainer. Let's see if CI tests pass.

### CODE REVIEW

**Comment by sanmai** [comment]
PHPStan sees some trouble, but it's unrelated to nette/utils.

**Comment by TomasVotruba** [comment]
Could you fix anyway?

**Comment by sanmai** [comment]
How about not in this PR? Thank you very much.

**Comment by TomasVotruba** [comment]
Sure, feel free to open new one

**Comment by TomasVotruba** [comment]
Replaced by #1323 

Thank you for the PR though

**Comment by sanmai** [comment]
No problem, but if you could push a release with that fix... it’ll be great!

**Comment by TomasVotruba** [comment]
I plan it in a week with bunch of other fixes. In the meantime this is how you make dependencies work:

```json
{
    "nette\utils": "3.0 as 2.5"
}
```

**Pull request closed without merging**
