### PR TITLE
[DeadCode] Failing fixture for not removing method parameter used on RemoveUnusedPrivatePropertyRector

### PR DESCRIPTION
**Pull request by samsonasik**
ref #5088

### CODE REVIEW

**Comment by samsonasik** [comment]
fixed.

**Comment by samsonasik** [comment]
seems cause an issue on `RemoveParentAndNameFromComponentConstructorRector` for used in `Arg` check in classmethod stmts.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
