### PR TITLE
[Order] Order constants by visibility

### PR DESCRIPTION
**Pull request by dobryy**
Closes: #3892 

This branch was created from #3933 that is why the target branch is not `master`

## Todo
- [x] phpstan #3936

### CODE REVIEW

**Comment by dobryy** [comment]
TODO:
- [ ] #3936

**Comment by TomasVotruba** [comment]
Could you rebase

**Comment by dobryy** [comment]
> Could you rebase

Ready, but phpstan is failing.

**Comment by TomasVotruba** [comment]
Thanks!

Could you fix those?

**Comment by dobryy** [comment]
> Thanks!
> 
> Could you fix those?

Sure, wasn't sure whether I have to because these are not related to the PR.

**Comment by TomasVotruba** [comment]
> Sure, wasn't sure whether I have to because these are not related to the PR.

Do you know [Boy Scout rule](https://medium.com/@biratkirat/step-8-the-boy-scout-rule-robert-c-martin-uncle-bob-9ac839778385)?

If CI was green, it would be merged already.

**Comment by TomasVotruba** [comment]
Btw, this is the reason for new errors:

image

**Comment by dobryy** [comment]
> Thanks 
> 
> Do you know [Boy Scout rule](https://medium.com/@biratkirat/step-8-the-boy-scout-rule-robert-c-martin-uncle-bob-9ac839778385)?
> 
> If CI was green, it would be merged already.

I didn't :) It just can be a problem when there are two boy scouts solving same issue in different branches :)

**Comment by TomasVotruba** [comment]
Don't worry, I'm buzy with other projects this week

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
