### PR TITLE
Split downgrade sets

### PR DESCRIPTION
**Pull request by leoloso**
As requested in https://github.com/rectorphp/rector/pull/4172#discussion_r485041789

### CODE REVIEW

**Comment by leoloso** [comment]
@TomasVotruba please check the error in the CI, I have no clue what that is:

```
 -
     message: '#Use explicit interface contract or a service over unclear abstract methods#'
     paths:
         - rules/generic/src/Rector/AbstractIsAbleRector.php
         - rules/nette/src/Rector/Identical/AbstractWithFunctionToNetteUtilsStringsRector.php
         - src/Testing/PHPUnit/AbstractGenericRectorTestCase.php
         - src/Testing/PHPUnit/AbstractNodeVisitorTestCase.php
```

Btw, I'm still unable to run `composer phpstan`

**Comment by TomasVotruba** [comment]
> I have no clue what that is

I wish PHPStan would show rule name, so people can understand it.

It's because this new rules was added to symplify set: https://github.com/symplify/symplify/pull/2144

The goal here is to extract behaviors from hidden `abstract` method to interface contract: https://github.com/symplify/symplify/pull/2144/files#diff-11c3b9432cf183a58cfe8cb83c2a2564

If you'd like to try to handle it, go for it. If not, I'll refactor later :+1:

**Comment by TomasVotruba** [comment]
I'll merge the sets as it they are, since the PHPStan error is unrelated and unnecessary blocker here.

Thanks

**Comment by leoloso** [comment]
> If you'd like to try to handle it, go for it. If not, I'll refactor later 👍

Yep, you do it please 😛

**Pull request merged**
