### PR TITLE
[CodeQuality] ForToForeachRector improvement on ArrayDimFetch handling

### PR DESCRIPTION
**Pull request by samsonasik**
Got 2 more false positive on : 

- skip re-assign array with same key on for statements 
- do not change use array dim fetch in count($var)

This patch handle them.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I found another false positive when array with key is unsetted inside for statement https://3v4l.org/Gt9Mh : 

```php
        $tokens = ['a'];
        for ($i = 0, $c = count($tokens); $i < $c; $i++) {
            unset($tokens[$i]);
        }
        
        var_dump($tokens);
```

**Comment by samsonasik** [comment]
Fixed to skip  unset ArrayDimFetch inside for

**Comment by samsonasik** [comment]
It seems CI hang again after " [ci-review] Rector Rectify " auto commit, currently hang on " Apply Coding Standard Expected — Waiting for status to be reported " and " Validate Monorepo Expected — Waiting for status to be reported "

**Comment by samsonasik** [comment]
close - re-open - rebased.

**Comment by samsonasik** [comment]
@TomasVotruba it shows in checklists:

```bash
All checks have passed
17 successful and 1 neutral checks 
```

but there are 2 still pendings CI waiting:

```bash
Some checks haven’t completed yet
17 successful, 2 expected, and 1 neutral checks 

Apply Coding Standard Expected — Waiting for status to be reported
Validate Monorepo Expected — Waiting for status to be reported
```

It seems hanging, could you verify? Thank you.

**Comment by TomasVotruba** [comment]
> It seems hanging, could you verify? Thank you.

They have been moved to automated daily pull-request job.
I forgot to remove it from required checks. Fixed

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
