### PR TITLE
[CodeQuality] Skip ChangeArrayPushToArrayAssignRector not in expression

### LINKED ISSUE #5844: Incorrect behavior of ChangeArrayPushToArrayAssignRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/77ca42cb-c843-4fde-a45f-befd62bd03f3

```php
<?php
function force_balance_tags( $text ) {
	$tagstack  = array();
	$stacksize = 0;
	$tag = 'a';
	$stacksize = array_push( $tagstack, $tag );
}
```

### Responsible rules

* `ChangeArrayPushToArrayAssignRector`

## Expected Behavior

Rector should not apply this rule if the return value is going to be used.
Rector does shows this error when it's run:
```
[ERROR] Could not process  file, due to:                    
         "Node "PhpParser\Node\Expr\FuncCall":7 is child of "PhpParser\Node\Expr\Assign", so it cannot be removed as it would break PHP code. Change or remove the parent node instead.". 
```
The demo environment doesn't show this error and it would be nice if it did.
Also it'd be nice if errors like this would automattically skip rules so things could continue.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5844

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by superdav42** [comment]
I can confirm this PR resolves the issue in the simple test and when applied to the legacy codebase I'm working with.

**Comment by TomasVotruba** [comment]
Thank you 👍

**Pull request merged**
