### PR TITLE
Remove stubs/ from rector.phar

### LINKED ISSUE #2602: Remove stubs from rector.phar
Would it be possible to remove the stubs/ folder from rector.phar to prevent PHPStorm multiple definition for classes (without having to exclude the whole phar from the project, which is useful to investigate Rectors) ?

### PR DESCRIPTION
**Pull request by gnutix**
Fixes #2602.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Probably this needs removing too: https://github.com/rectorphp/rector/blob/master/compiler/build/scoper.inc.php#L17

Not sure if phpstorm stubs break your code too, but then PHPStan will be missing them, as it's their dependency.

**Comment by gnutix** [comment]
I have *no idea* how this works... I just compiled it and ran it on my project, and it was still working and I had no inspections from PHPStorm anymore. Anything else, I'll ask you to try/fix yourself please, I'm of no use here.

**Comment by TomasVotruba** [comment]
Just remove the other line and see if it still works. Now it's dead code.

**Comment by gnutix** [comment]
@TomasVotruba Done, seems to work (at least running the phar on my project).

**Comment by TomasVotruba** [comment]
Thank you!

**Comment by TomasVotruba** [comment]
Possibly useful: https://github.com/rectorphp/rector/issues/2936

**Pull request merged**
