### PR TITLE
[DeadDocBlock] Skip RemoveUselessParamTagRector on Generic Type

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #5676

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by OskarStark** [comment]
Just asking to plan the way to go in my project. Can I expect a release soon or in a few days?

**Comment by TomasVotruba** [comment]
Somewhere between 1-5 days, depens how https://github.com/rectorphp/rector/pull/5665 goes. It has a priority now :)

**Comment by OskarStark** [comment]
Thanks 👍

**Pull request merged**
