### PR TITLE
Add Describe command

### PR DESCRIPTION
**Pull request by TomasVotruba**
### Todo

- [x] add to README

### Waits on

- [x] #407 
- [x] #409 

### Output

preview

### CODE REVIEW

**Comment by TomasVotruba** [comment]
> Maybe we can generate a README.md with these descriptions in our documentation. IMHO is easier for users, as they won't need to download Rector and run the command.

Agreed. That can be done in next PR

**Comment by TomasVotruba** [comment]
Ready to review :+1:

**Comment by carusogabriel** [comment]
This PR isn't working locally for me. I type `./bin/rector describe` or `bin/rector describe` and I got nothing

**Comment by mssimi** [comment]
Seems great, I will check it later today:)

**Comment by TomasVotruba** [comment]
> @carusogabriel  This PR isn't working locally for me. I type ./bin/rector describe or bin/rector describe and I got nothing

I've added exception to make this clear. It's consistent with `process` command now

**Comment by carusogabriel** [comment]
Perfect, I’ll test and report any issues that I face

**Pull request merged**
