### PR TITLE
 [Utils] Add validate-fixture-filename command 

### PR DESCRIPTION
**Pull request by samsonasik**
To detect fixture filename with `-` character instead of `_`

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you. Could you rebase 1 conflict on the master?

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Pull request merged**
