### PR TITLE
Remove dead coding standards rules

### PR DESCRIPTION
**Pull request by carusogabriel**
Following #381, this PR proposes the removal of "dead" coding standards rules.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Beautiful work :+1:

**Comment by TomasVotruba** [comment]
Btw, ECS should report these un-used cases, so you don't have to do it manually. It looks it's broken :/
Could you create issue at Symplify

**Comment by carusogabriel** [comment]
@TomasVotruba Yes. And I'll try to fix it there as well :nerd_face:

**Comment by TomasVotruba** [comment]
@carusogabriel It might be fixed in `master` or latest alpha. Just to be sure we wont miss it :)

**Pull request merged**
