### PR TITLE
[BetterPhpDocParser] Handle parseString() got ShouldNotHappenException 

### LINKED ISSUE #5267: Parsing error on `@var` in v0.9.12
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.9.12              |
| Installed as   | prefixed |

Parsing this code:

```php
<?php declare(strict_types=1);

namespace RectorBugTest;

class RectorBug
{
    public function fails(\Symfony\Component\HttpFoundation\Request $request): void
    {
        $request->query->get('xxx');
    }
}
```

results in this parsing error on `@var` annotation:

```
[parsing] src/RectorBug.php
PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser::parseTagValue()" on line 137 in <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php:137
Stack trace:
#0 <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php(128): Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser->parseTagValue(Object(PHPStan\PhpDocParser\Parser\TokenIterator), '@var')
#1 <project>\vendor\phpstan\phpdoc-parser\src\Parser\PhpDocParser.php(53): Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser->parseTag(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#2 <project>\vendor\phpstan\phpdoc-parser\src\Parser\PhpDocParser.php(40): PHPStan\PhpDocParser\Parser\PhpDocParser->parseChild(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#3 <project>\v in <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php on line 137
Fatal error: Uncaught Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser::parseTagValue()" on line 137 in <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php:137
Stack trace:
#0 <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php(128): Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser->parseTagValue(Object(PHPStan\PhpDocParser\Parser\TokenIterator), '@var')
#1 <project>\vendor\phpstan\phpdoc-parser\src\Parser\PhpDocParser.php(53): Rector\BetterPhpDocParser\PhpDocParser\BetterPhpDocParser->parseTag(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#2 <project>\vendor\phpstan\phpdoc-parser\src\Parser\PhpDocParser.php(40): PHPStan\PhpDocParser\Parser\PhpDocParser->parseChild(Object(PHPStan\PhpDocParser\Parser\TokenIterator))
#3 <project>\v in <project>\vendor\rector\rector-prefixed\packages\better-php-doc-parser\src\PhpDocParser\BetterPhpDocParser.php on line 137
```

I'm not sure what's special about Symfony's `Request` but I wasn't able to reproduce the problem with a custom code.

Surprisingly, the error shows even here: https://getrector.org/demo/15c3fd41-9764-4f6d-8f3e-e9ccc36b252d

Different line numbers (180 vs 137) because of unprefixed vs prefixed version

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5267

### CODE REVIEW

**Comment by samsonasik** [comment]
@vhenzl @ERuban please verify if this can fix #5267 , You can try with the following steps:

```bash
composer config minimum-stability dev  
composer config prefer-stable true
composer remove rector/rector
composer require --dev rector/rector:dev-fix-5267

# run rector process
composer rector -- process --no-progress-bar --dry-run --debug src/RectorBug.php
```

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by vhenzl** [comment]
Thanks @samsonasik for looking into that, but I don't think this is correct. I had just a quick glance, but the first impression is that you are here healing symptoms instead of the disease. 

By ignoring the parsing error of a comment with `@var` and providing empty comment instead, you lose the property type (`$abc` would be `mixed` instead of `Xyz`).

Also, having a logic based on an exception named `ShouldNotHappenException` isn't IMO correct. As for its name, the exception is for cases that really shouldn't happen (and afaik used mostly to silence PHPStan when it complains about something being `null` but you know it never should be `null` - like it this case where `CurrentNodeProvider` instance should contain the current node).

See these two my comments: https://github.com/rectorphp/rector/issues/5267#issuecomment-766025886 and https://github.com/rectorphp/rector/issues/5267#issuecomment-766080216. I believe the problem was introduced in #5250 which removed [PhpDocInfoNodeVisitor.php](https://github.com/rectorphp/rector/pull/5250/files#diff-39604fd0b665b53e10a032982b0bce22642f4129d95b7a9e43497dbed8029816) and as a result, `PhpDocInfoFactory` isn't called and the current node isn't set anymore.

**Comment by samsonasik** [comment]
@vhenzl thank you for verify, feel free to create other PR if you have better solution ;)

**Comment by samsonasik** [comment]
@vhenzl I created new commit to verify PropertyFetch by checking for its type from scope https://github.com/rectorphp/rector/pull/5299/commits/4faa09d3d376b51b62baf86baeffc6e689173273 as the PropertyFetch is came from the method parameter. 

Please verify if that is better solution ;)

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
updated with better approach with check PropertyFetch has `PhpDocInfo` https://github.com/rectorphp/rector/pull/5299/commits/57db2fef57a3c545225fbc4c259f9c02483a6561

**Comment by samsonasik** [comment]
I refactored to ensure  $phpDocInfo->getVarTagValueNode() instanceof VarTagValueNode and use the `VarTagValueNode`'s TypeNode to check with StaticTypeMapper.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by ERuban** [comment]
Good job, @samsonasik. The problem is disappeared in my project.
So, waiting the release with this fix. 
Thank you.

**Review by TomasVotruba — APPROVED** [review]

**Comment by vhenzl** [comment]
@TomasVotruba @samsonasik This isn't correct. Yes, it fixes the issue, but the resolved type of a property fetch is wrong.

There isn't any test for `PropertyFetchTypeResolver` so I modified `NodeTypeResolver::resolver()` to output the resolved types like this:

```php
// vendor/rector/rector/packages/node-type-resolver/src/NodeTypeResolver.php
    public function resolve(Node $node): Type
    {
        $type = $this->resolveFirstType($node);
        if (! $type instanceof TypeWithClassName) {
            echo "<1 " . __METHOD__ . ": {$node->getType()} ({$node->name}): ".$type->describe(VerbosityLevel::cache())."\n";
            return $type;
        }

        $type = $this->parentClassLikeTypeCorrector->correct($type);
        echo "<2 " . __METHOD__ . ": {$node->getType()} ({$node->name}): ".$type->describe(VerbosityLevel::cache())."\n";
        return $type;
    }
```

The original repro example isn't exactly good, so I modified it like this:

```php
// src/Abc.php
class Abc
{
    public function get(string $s): string
    {
        return $s;
    }
}

// src/Xyz.php
class Xyz
{
    /**
     * @var Abc
     */
    public $abc;

    /**
     * @var string
     */
    public $str;
}

// src/RectorBug.php
class RectorBug
{
    public function fails(Xyz $xyz): void
    {
        $xyz->abc->get('xxx');
        $xyz->str->xxx();
    }
}
```

Rector 0.9.10 correctly prints:

```
...
[parsing] src/RectorBug.php
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_Variable (xyz): RectorBugTest\Xyz
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_PropertyFetch (abc): Abc
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_Variable (xyz): RectorBugTest\Xyz
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_Variable (xyz): RectorBugTest\Xyz
<1 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_PropertyFetch (str): string
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_Variable (xyz): RectorBugTest\Xyz
[refactoring] src/RectorBug.php
...
```

Rector with this PR resolves types incorrectly and prints:
```

[parsing] src/RectorBug.php
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_Variable (xyz): RectorBugTest\Xyz
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_PropertyFetch (abc): RectorBugTest\Xyz
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_Variable (xyz): RectorBugTest\Xyz
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_Variable (xyz): RectorBugTest\Xyz
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_PropertyFetch (str): RectorBugTest\Xyz
<2 Rector\NodeTypeResolver\NodeTypeResolver::resolve: Expr_Variable (xyz): RectorBugTest\Xyz
[refactoring] src/RectorBug.php
```

**Comment by samsonasik** [comment]
@vhenzl please create PR with the failing fixture for that, thank you.

**Comment by vhenzl** [comment]
@samsonasik See #5307

**Pull request merged**
