### PR TITLE
RenamePropertyToMatchTypeRector failing test

### LINKED ISSUE #3897: RenamePropertyToMatchTypeRector issue
# Bug Report RenamePropertyToMatchTypeRector

Rector version: v0.7.61
Installed as composer dependency

**Vendor interface**

```php
namespace Some\Vendor\Namespace;

interface SomethingInterface 
{
    public function doSomething(Request $req): void;
}
```

**Before RenamePropertyToMatchTypeRector**

```php
namespace App\Service;

use Some\Vendor\Namespace\SomethingInterface;

final class Something implements SomethingInterface 
{
    public function doSomething(Request $req): void {
        // ...
    }
}
```

**After RenamePropertyToMatchTypeRector**

```php
namespace App\Service;

use Some\Vendor\Namespace\SomethingInterface;

final class Something implements SomethingInterface 
{
    public function doSomething(Request $request): void {
        // ...
    }
}
```

**Expected Behaviour**

Keep it as is. RenamePropertyToMatchTypeRector must not rename properties of methods that are implementation of vendor interface, as it will break code.

### PR DESCRIPTION
**Pull request by mssimi**
Closes #3897

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you for the test. The output is valid working code.

Could you provide the 3v4l.com code sample that demonstrates the fatal error?

**Comment by TomasVotruba** [comment]
Maybe the test fixture would benefit from RunnableInterface

**Comment by mssimi** [comment]
> Thank you for the test. The output is valid working code at first sight.
> 
> Could you provide the 3v4l.org code sample that demonstrates the fatal error?

How can I simulate vendor package on 3v4l.org?

I really don't understand what else you want from me, **SomeVendorInterface** is in vendor and when I implement interface from vendor in my own code base, it's methods params cannot be changed.

@dobryy Understands it, maybe he can explain better I am giving it up.

**Comment by TomasVotruba** [comment]
> How can I simulate vendor package on 3v4l.org?

No need to simulate that. Here is your code: https://3v4l.org/3kcB2
It shows the correct expected output.

<br>

I basically need to see error you have after Rector changes the code.

**Comment by TomasVotruba** [comment]
Works with interface too: https://3v4l.org/u4gqW

**Comment by mssimi** [comment]
Right, here is code https://3v4l.org/LAmoY

I am really sorry, this is embarrassing, but I didn't know variable names can be changed in class where interface method is implemented. It certainly works and I was the one the is wrong and I am very sorry about it.

**Comment by mssimi** [comment]
My apologize, I was wrong on this one.

**Comment by TomasVotruba** [comment]
That's why I was so confused :D 
No troubles! 

Yet you discovered another bug, that Rename**Property** should not touch **Param**.

I'll look into it, thanks

**Pull request closed without merging**
