### PR TITLE
[Performance] Bug Fix CountArrayToEmptyArrayComparisonRector for negation inside or / and operator

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
I skipped change if truthy negation is have `||` or `&&` in previous or next the expression.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@TomasVotruba I got the solution :tada: . The `BooleanNot` need to be added to `getNodeTypes()` so it can be checked and replaced directly  :tada:  :tada:  :tada:

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1: 

Nice work on adding more features with less lines :1st_place_medal:

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
