### PR TITLE
[PHP 7.1 Scoped] Register missing require & autoload

### PR DESCRIPTION
**Pull request by samsonasik**
refs https://github.com/rectorphp/rector/issues/5471#issuecomment-778218880

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba I tried the downgrade_packages.sh script, it seems only works on linux? I tried in macOS:

```bash
./.github/workflows/scripts/downgrade_packages.sh 7.1

./.github/workflows/scripts/downgrade_packages.sh: line 45: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

**Comment by leoloso** [comment]
@samsonasik Running `bash -x ./.github/workflows/scripts/downgrade_packages.sh 7.1` works. Don't ask me why.

**Comment by samsonasik** [comment]
@leoloso hm.., still not works, only works on a few steps:

```bash
bash -x ./.github/workflows/scripts/downgrade_packages.sh 7.1

+ set -e
+ supported_target_php_versions=(7.0 7.1 7.2 7.3 7.4)
+ GROUP_RECTOR_CONFIGS=true
+ DOWNGRADE_DEPENDENCIES_TOGETHER=true
+ declare -A downgrade_php_whynots
./.github/workflows/scripts/downgrade_packages.sh: line 45: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

**Comment by samsonasik** [comment]
@TomasVotruba is there a way we can test with docker?

**Comment by TomasVotruba** [comment]
@samsonasik Nothing I know of. Only what is available here in this repository.

**Comment by samsonasik** [comment]
@TomasVotruba probably merge for now and let see what happen?

**Comment by TomasVotruba** [comment]
@samsonasik Feel free to merge these PHP 7.1-related PRs yourself, so you don't have to wait on me.

**Comment by leoloso** [comment]
@samsonasik it may be the version of bash we have installed in Mac.

I have this one, doing `bash -x` works for me:

```
$ bash --version
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

**Comment by samsonasik** [comment]
@leoloso I have this version: 

```bash
➜  ~ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by leoloso** [comment]
Maybe that's why it doesn't work for you. You can try to upgrade it, and then try your luck again

**Comment by samsonasik** [comment]
@leoloso thank you, I just updated the bash and it seems running 🎉 

Screen Shot 2021-02-13 at 21 45 27

**Pull request merged**
