### PR TITLE
[DeadCode] Skip RemoveEmptyClassMethodRector on final method in non-final class

### LINKED ISSUE #4918: Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector
# Bug Report

Output:
```
    ---------- begin diff ----------
--- Original
+++ New
@@ -8,9 +8,6 @@

        use SmartObject;

-       final public function __construct() {
-       }
-
    ----------- end diff -----------

```

But code `final public function` is not dead code in abstract class

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #4918

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
