### PR TITLE
[CodingStyle]  Bug fix: ReservedKeywordAnalyzer should add _SESSION to NATIVE_VARIABLE_NAMES

### PR DESCRIPTION
**Pull request by samsonasik**
Re-create PR #4263 to this repo.

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba cs still failing even direct push to this repository branch. I tried locally and cs is ok. Could you verify it? Thank you.

**Comment by TomasVotruba** [comment]
The CI runs on latest package versoins, so this might help locally:

```
composer update
```

If that doesn't help, I'll check it locally

**Comment by samsonasik** [comment]
I already run composer update locally, and working fine in my local dev.

**Comment by TomasVotruba** [comment]
I'm on it

**Comment by TomasVotruba** [comment]
The local cache might be blocking it:

```bash
composer fix-cs -- --clear-cache
```

**Comment by TomasVotruba** [comment]
I've just added the fixing commit

**Comment by samsonasik** [comment]
Thank you, phpunit error seems unrelated

**Comment by TomasVotruba** [comment]
PHPUnit fails because of new PHPStan + php-parser.

Basically this must be solved first before any other PR gets merged:
https://github.com/rectorphp/rector/pull/4264

I'll look on it, this might take some time. In the meanwhile, you can work on @Symplify and PHPStan rules

**Pull request merged**
