### PR TITLE
[DeadCode] Skip RemoveUnusedPrivatePropertyRector on property fetch in unset

### LINKED ISSUE #5076: Incorrect behavior of Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@900b60c             |
| Installed as   | git clone                            |

Parameter `$packageName` is removed from constructor as unused, but it is used in the next method. Maybe problem is it is in unset function?
```php
unset($composerData[$section][$this->packageName]);
```

## Minimal PHP Code Causing Issue

https://getrector.org/demo/2ae1ce38-7504-4fae-84f5-6f78a8988d69

## Expected Behaviour

Do not remove private property from construct if it is in use

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5076

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by lulco** [comment]
@samsonasik I check another use case: https://getrector.org/demo/a8dfb6cc-936e-4f0b-8adf-5c50b81cf9c6

there is isset instead of unset and demo failed again, so probably unset isn't only problematic construction

**Comment by TomasVotruba** [comment]
@samsonasik Thank you :+1:

**Pull request merged**
