### PR TITLE
[Failing Test Case] #4013: Don't force type hint if already forced.

### PR DESCRIPTION
**Pull request by Aerendir**
Failing test case for #4013 .

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the rest!

What do you need to know to fix it?

**Comment by Aerendir** [comment]
@TomasVotruba , I read the rule, but didn't found where the type hint is added... And in this moment I'm not able to "play" with the code to further explore it.

**Comment by TomasVotruba** [comment]
I'll try to navigate

The rule (for easier link on mobile): https://github.com/rectorphp/rector/blob/master/rules/symfony/src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php

The retype: https://github.com/rectorphp/rector/blob/master/rules/symfony/src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php#L158

**Comment by TomasVotruba** [comment]
It's should be pretty straighfoward now, since it's just 1 line to add check fro `Int_` retype.

When do you think you'll finish it?

**Comment by TomasVotruba** [comment]
It's should be pretty straighfoward now, since it's just 1 line to add check fro `Int_` retype.

When do you think you'll finish it?

**Comment by Aerendir** [comment]
Sorry, I cannot for now... or at least I don't know when I will...

**Comment by samsonasik** [comment]
@Aerendir I cherry-picked your commit and create new PR https://github.com/rectorphp/rector/pull/4095 with a fix at https://github.com/rectorphp/rector/pull/4095

**Comment by TomasVotruba** [comment]
Resolved by #4095

**Pull request closed without merging**
