### PR TITLE
Add failing test fixture for DowngradeParameterTypeWideningRector

### LINKED ISSUE #5994: Incorrect behavior of DowngradeParameterTypeWideningRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1b8ee6a0-7d50-4fae-8e15-f19d19591fc5

```php
<?php
trait StreamDecoratorTrait
{
    protected function createStream()
    {
        // ...
    }
}

class MultipartStream
{
    use StreamDecoratorTrait;

    protected function createStream(array $elements)
    {
        // ...
    }
}
```

### Responsible rules

* `DowngradeParameterTypeWideningRector`

## Expected Behavior

The rule is currently doing this:

```diff
class MultipartStream
{
    use StreamDecoratorTrait;

-    protected function createStream(array $elements)
+    protected function createStream($elements)
    {
        // ...
    }
}
```

Instead, it should do nothing:

```diff
class MultipartStream
{
    use StreamDecoratorTrait;

    protected function createStream(array $elements)
    {
        // ...
    }
}
```

`DowngradeParameterTypeWideningRector` should not remove the type `array` of the param `$elements`, because the different method comes from a trait. But only parent classes and interfaces should be considered, not traits.

Debugging `DowngradeParameterTypeWideningRector`, I found out this:

```php
// Remove the types in:
// - all ancestors + their descendant classes
// - all implemented interfaces + their implementing classes
$parameterTypesByParentClassLikes = $this->resolveParameterTypesByClassLike(
    $classReflection,
    $methodName,
    $position
);
var_dump($parameterTypesByParentClassLikes);
```

Prints:

```
array(2) {
  ["GuzzleHttp\Psr7\MultipartStream"]=>
  object(PHPStan\Type\ArrayType)#27706 (2) {
    ["keyType":"PHPStan\Type\ArrayType":private]=>
    object(PHPStan\Type\MixedType)#27715 (2) {
      ["isExplicitMixed":"PHPStan\Type\MixedType":private]=>
      bool(false)
      ["subtractedType":"PHPStan\Type\MixedType":private]=>
      NULL
    }
    ["itemType":"PHPStan\Type\ArrayType":private]=>
    object(PHPStan\Type\MixedType)#27701 (2) {
      ["isExplicitMixed":"PHPStan\Type\MixedType":private]=>
      bool(false)
      ["subtractedType":"PHPStan\Type\MixedType":private]=>
      NULL
    }
  }
  ["GuzzleHttp\Psr7\StreamDecoratorTrait"]=>
  object(PHPStan\Type\MixedType)#27710 (2) {
    ["isExplicitMixed":"PHPStan\Type\MixedType":private]=>
    bool(false)
    ["subtractedType":"PHPStan\Type\MixedType":private]=>
    NULL
  }
}
```

Hence, `StreamDecoratorTrait` is also being picked by `resolveParameterTypesByClassLike`, that's the problem.

### PR DESCRIPTION
**Pull request by leoloso**
# Failing Test for DowngradeParameterTypeWideningRector

Based on https://getrector.org/demo/1b8ee6a0-7d50-4fae-8e15-f19d19591fc5

Fixes #5994

### CODE REVIEW

**Comment by leoloso** [comment]
Issue: #5994

**Comment by leoloso** [comment]
Alright, bug fixed!

Traits must be skipped for this rule, so I added:

```php
if ($ancestorClassReflection->isTrait()) {
    continue;
}
```

Please check and merge 🙏

**Comment by leoloso** [comment]
Fixes #5994

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you Leo

**Comment by samsonasik** [comment]
@leoloso it possibly cause issue on rector prefixed build which `string` parameter not removed:

https://github.com/rectorphp/rector-prefixed/blob/056cdf6b69602977e4227fe74e2c8b55ecb26c7f/vendor/symfony/service-contracts/ServiceLocatorTrait.php#L41

so make error:

```bash
PHP Fatal error:  Declaration of RectorPrefix20210420\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with RectorPrefix20210420\Psr\Container\ContainerInterface::has($id) in /home/runner/work/rector-prefixed/rector-prefixed/vendor/symfony/dependency-injection/ServiceLocator.php on line 25

Fatal error: Declaration of RectorPrefix20210420\Symfony\Component\DependencyInjection\ServiceLocator::has(string $id) must be compatible with RectorPrefix20210420\Psr\Container\ContainerInterface::has($id) in /home/runner/work/rector-prefixed/rector-prefixed/vendor/symfony/dependency-injection/ServiceLocator.php on line 25
Error: Process completed with exit code 255.
```

**Comment by leoloso** [comment]
I don't think this code I added is the one causing the issue.

I explained in #6176 but also, this rule was originally modifying code in the class, if it implemented a trait:

```php
foreach ($classReflection->getAncestors() as $ancestorClassReflection) {
``` 

But that's an error, because the same method defined in the class will override the one from the trait (check the fixture I added).

And in any case, the offending code is in the trait `ServiceLocatorTrait`, not in the class.

So these are related, but different issues.

**Comment by samsonasik** [comment]
@leoloso thank you for verify 👍

**Pull request merged**
