### PR TITLE
[Services] Failing test register invalid service

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba this should throw exception and inform user that service is not exists, ref https://github.com/rectorphp/rector/issues/5938

**Comment by TomasVotruba** [comment]
How would you recommend to check this in Symfony? I assume this should be handled in the framework itself

**Comment by samsonasik** [comment]
if we can get the `container->has()` check somewhere, probably we can override via event listener

**Comment by TomasVotruba** [comment]
That might create extra dependency on event listener, that we don't need here. 

But similar operation can do compiler pass on container compilation:
https://symfony.com/doc/current/service_container/compiler_passes.html

**Comment by TomasVotruba** [comment]
Yet, I think this should be resolved in Symfony core level, as any Symfony project will suffer this problem, not just Rector.

**Comment by samsonasik** [comment]
Ok, I will check if I can do something with Compiler Pass for now.

I am closing for now.

**Pull request closed without merging**
