### PR TITLE
rename ArgumentReplacerRector to ArgumentRector as it is now general

### LINKED ISSUE #356: Change ArgumentReplacerRector to ArgumentRector
Using this rector:
```
Rector\Rector\Dynamic\ArgumentRector:
    $argumentByMethod:
        -
            type: 'add'
            class: 'Sylius\Component\Core\Model\OrderInterface'
            method: 'getLastPayment'
            position: 0 # as append | default value is 0, config argument need not be listed
            typehint: false # default value is false, config argument need not be listed
            property: '$state'
            default_value: PaymentInterface::STATE_NEW
            can_be_nullable: # default value is false, config argument need not be listed
```

Possible types:
- **add** for adding new argument
- **replace** for replacing existing argument
- **remove** for removing existing argument

### PR DESCRIPTION
**Pull request by mssimi**
Closes #356 as for 'add' there is #398.

I renamed it as it is already general.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Good to know

**Comment by TomasVotruba** [comment]
Could you also resolve #398, so it's completed?

**Comment by mssimi** [comment]
One step at time:)

**Comment by TomasVotruba** [comment]
Is that yes? :)

**Comment by mssimi** [comment]
Yes after PHAR:D

**Pull request merged**
