### PR TITLE
add failing test for RemoveUnusedPrivateMethodRector

### PR DESCRIPTION
**Pull request by bendavies**
Here's a bug I found when running `dead-code` level on my project

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Nice catch!

I think methods with name starting `__` should be all skipped, since there is no way to verify they're usage/non-usage. What do you think?

**Comment by bendavies** [comment]
that sounds sensible to me

**Comment by TomasVotruba** [comment]
Could you add it the same way `isAbstract()`?

Something like this:

```php
if ($this->matchName($node, '#^__*#')) {
    return null;
}
```

**Comment by bendavies** [comment]
yep

**Comment by TomasVotruba** [comment]
Great job :+1:

**Pull request merged**
