### PR TITLE
[mysql-to-mysqli] Added fixture for issue#4977

### PR DESCRIPTION
**Pull request by genesiscz**
I hope I didn't do it completely wrong, if yes, please correct me so my next contribution can be better :-)

https://github.com/rectorphp/rector/issues/4977

### CODE REVIEW

**Comment by genesiscz** [comment]
I guess I was wrong about the file name, sorry about mixing it up. Should I rename it or is it fine like that?

**Comment by TomasVotruba** [comment]
Hi,

I'm sorry for late answer.
I'm pinging CI to see what is missing here.

@samsonasik I have feelign this was fixed somewhere else. Do you recall fixing it?

**Comment by samsonasik** [comment]
@TomasVotruba I've never fixed it yet. I will try check it.

**Comment by TomasVotruba** [comment]
@samsonasik  Thank you :+1:

**Comment by samsonasik** [comment]
@genesiscz I cherry-picked your commit at PR https://github.com/rectorphp/rector/pull/5130

**Pull request closed without merging**
