### PR TITLE
Add failing test fixture for MoveVariableDeclarationNearReferenceRector

### PR DESCRIPTION
**Pull request by TomasVotruba**
Based on https://getrector.org/demo/da17d61f-b12e-4fa8-85a0-0c20a502f19d

cc @samsonasik This should be avoided IMO, what do you think?

### CODE REVIEW

**Comment by samsonasik** [comment]
yes, that should be skipped.

**Comment by samsonasik** [comment]
fixed.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
