### PR TITLE
updated UnwrapFutureCompatibleIfRectorTest

### PR DESCRIPTION
**Pull request by C0pyR1ght**
added second test case to unittest

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Fix is needed

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/blob/9d82c9e76a7b8f256a52cba9e9094d0e04131d1a/packages/Polyfill/src/FeatureSupport/FunctionSupportResolver.php#L14-L21

**Comment by staabm** [comment]
Looks like the impl of the UnwrapFutureCompatibleIfRector needs tuning to work with if-cases without a else clause

**Comment by TomasVotruba** [comment]
I'll look into it

**Pull request merged**
