### PR TITLE
[CakePHPToSymfony] Add h function templates

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref #2705

### CODE REVIEW

**Comment by afilina** [comment]
This rector doesn't actually work. `$this->doTestFileWithoutAutoload($file);` is a trick that makes the test pass, but there's no way to skip the `require_once` in a real run.

All templates are causing fatal errors. I tried to run `CakePHPTemplateHToTwigRector` on the exact same file as in the test:

```
<li>
    <?php echo $this->Html->link(__('List Rights'), ['action' => 'index']); ?>
</li>
```

and got this:
```
Fatal error: Uncaught Error: Call to a member function link() 
```

**Comment by TomasVotruba** [comment]
> but there's no way to skip the require_once in a real run.

Apperantly it can work... What would you suggest to make this work?

**Comment by afilina** [comment]
I have no idea how it works deep down. I don't have any design documents and there's too much code to randomly go digging. We need the ability for a file to be the target of a rector without being force to `require_once` it.

**Comment by TomasVotruba** [comment]
Could add minimal failing test case to Github Actions? 
I'll try to dig it out

**Pull request merged**
