### PR TITLE
Fix AssertEqualsToSameRector

### PR DESCRIPTION
**Pull request by Bl00D4NGEL**
Requested failing fixtures for https://github.com/rectorphp/rector/issues/5799

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you. Could you try to fix it?

**Comment by Bl00D4NGEL** [comment]
I'll give it a shot once I get off work later on today - will report back :)

**Comment by Bl00D4NGEL** [comment]
Hey @TomasVotruba 
I think I've got a fix ready but it seems other tests are failing that I haven't touched. I'm not sure where these failing tests come from, is it because I started using the `nodeTypeResolver` inside the rector? I'm happy to fix those failing tests if you or anyone else wants to point me to the right direction.

**Comment by TomasVotruba** [comment]
It seems unrelated to your fix 

This might help https://github.com/rectorphp/rector/pull/5808

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
