### PR TITLE
[TASK] Take glob pattern for files into account

### PR DESCRIPTION
**Pull request by sabbelasichon**
For now you cannot use the glob pattern on a file basis. But as we now have the FileProcessors it would be awesome to speed up the processing by selecting also files with a glob pattern

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, I like it :+1: 

This behavior should be already handled in this method:
https://github.com/rectorphp/rector/pull/6376/files#diff-c1b4d526cfa7d17990bde4cf0146bcf748e35382d13d14ca350a21820d2df256R107

Could you check it if there is some bug?

**Comment by sabbelasichon** [comment]
Maybe it is a feature and not a bug ;-)

But for now only glob pattern for directories is allowed. File patterns have to be real file paths.

**Comment by TomasVotruba** [comment]
I see. It should be merged in one service, now we have 2 do to the glob job.

**Comment by sabbelasichon** [comment]
I know. But i was scared to change it in the other package due to side effects.

**Comment by TomasVotruba** [comment]
Go for it :+1:

**Comment by sabbelasichon** [comment]
I have streamlined the globbing without creating a whole new service. Not sure how to start without opening Pandora's Box which takes too much time for right now.

**Pull request closed without merging**
