### PR TITLE
remove unnecessary condition(NamespaceReplacerRector)

### PR DESCRIPTION
**Pull request by mssimi**
Hey, I think this condition is unnecessary as next method that retrieve name, also checks that:)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I see. As `isCandidate()`  should filter out all invalid cases, the duplication should be removed in the second method.

**Comment by mssimi** [comment]
No by next method I mean `resolveNameFromNode()`.

**Comment by TomasVotruba** [comment]
I see. Link to method code would more helpful next time.

In that case, `resolveNameFromNode()` should return  `?string`, so the invalid type is more explicit. `null` beats "is string empty"

**Comment by mssimi** [comment]
I am not fan of nullable typehints, I use them only when neccesary, coz if you make typehint nullable you have to deal with that later in code.

**Comment by TomasVotruba** [comment]
I see, let's keep it for now.

**Comment by mssimi** [comment]
Anytime bro:)

**Pull request merged**
