### PR TITLE
[EarlyReturn] Skip ChangeAndIfToEarlyReturnRector when parent if has next statement

### LINKED ISSUE #5410: Incorrect behavior of ChangeAndIfToEarlyReturnRector
# Bug Report

Hi! Thanks for your tool.

I've found a bug in ChangeAndIfToEarlyReturnRector rule. It return's from function but there is some logic below the statement (see an example).

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/c2db0ec3-9ea5-4ff3-9863-0a510001a1c8

```php
<?php

final class DemoFile
{
    private function test()
    {
        $firstStatement  = isFirstStatementTrue();
        $secondStatement = isSecondStatementTrue();
        $foo             = bar();

        if ($firstStatement) {
            if ($secondStatement && (null !== $foo)) {
                // some logic w/o returns here
            }
        }

        $thirdStatement = isThirdStatementTrue();
        if ($thirdStatement) {
            // some logic here
        }
    }
}
```

### Responsible rules

* `ChangeAndIfToEarlyReturnRector`

## Expected Behavior

ChangeAndIfToEarlyReturnRector should change only `$thirdStatement`

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5410

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by berezuev** [comment]
Thank you @samsonasik @TomasVotruba

**Pull request merged**
