### PR TITLE
[PhpSpecToPHPUnit] Init new package

### LINKED ISSUE #1199: [Migration] Phpspec to PHPunit migration
Requested by client

- https://gnugat.github.io/2015/09/23/phpunit-with-phpspec.html 
- https://johannespichler.com/testing-with-phpspec/

## Cases to Cover

```diff
-$this->cart->shouldThrow(NotFoundException::class)->during('item', [$id]);
+$this->expectException(NotFoundException::class);
+$this->cart->item($id);
```

```diff
-$cart->price()->shouldBeCalled()->willReturn($price);
+$this->assertSame($price, $cart->price();
```

```diff
-$checkout->shippingAddress(Argument::type(Address::class))->shouldBeCalled();
```

```diff
-$response->hasFailed()->shouldBe(false);
+$this->assertFalse($response->hasFailed());
```

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #1199

### CODE REVIEW

**Comment by bendavies** [comment]
just tried this. i have over 500 specs. there are some cases that do not work. is there a place we can chat so i can help resolve and provide testcases?

**Comment by TomasVotruba** [comment]
Wow! I didn't expect someone will use this specific set so soon :D 

Well, I rarely use IM/chat, but if you send failing test cases, I'm able to fix them.

**Comment by bendavies** [comment]
ok will do

**Comment by TomasVotruba** [comment]
Could you add it the same way `isAbstract()`?

Something like this:

```php
if ($this->matchName($node, '#^__*#')) {
    return null;
}
```

**Pull request merged**
