### PR TITLE
Use on published release to trigger a new release on rector-prefixed

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Have you tested it? Does it fix the tag issue?

**Comment by Lctrs** [comment]
I tested. It does. You'll still have to manually create the `0.6.11` tag in rector-prefixed though.

**Comment by Lctrs** [comment]
It didn't worked before I guessed the workflow wrong. Now, it will trigger the new release in rector prefixed no matter how you create the new release here.

**Comment by TomasVotruba** [comment]
Ok

**Comment by TomasVotruba** [comment]
It doesn't work. I release 0.6.12 here: https://github.com/rectorphp/rector/releases/tag/v0.6.12

But with no effect in prefixed: https://github.com/rectorphp/rector-prefixed/releases

**Comment by TomasVotruba** [comment]
```bash
git tag x
git push --tags
```

**Comment by TomasVotruba** [comment]
I've added manual release now: https://github.com/rectorphp/rector-prefixed/tree/v0.6.12

I'll revert to Travis, that worked, as this seems mission impossible for last 2 weeks

**Comment by Lctrs** [comment]
What's weird is that Github Actions hasn't been triggered at all. I swear I tested your workflow and it worked for me.

After pushing the tag, do you have an external application that create the release in GitHub or do you create it manually via the UI ?

**Comment by TomasVotruba** [comment]
Travis covers it now: https://github.com/rectorphp/rector-prefixed/tree/v0.6.13


> After pushing the tag, do you have an external application that create the release in GitHub or do you create it manually via the UI ?

Just push it, that's all. Then Travis or Github Actions do the release

**Comment by TomasVotruba** [comment]
> What's weird is that Github Actions hasn't been triggered at all. I swear I tested your workflow and it worked for me.

I'm quite new to Github Action, so I have no idea how they actually work her.

**Pull request merged**
