### PR TITLE
[EarlyReturn] Handle ChangeAndIfToEarlyReturnRector has Return expr in if stmt fixture

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/5619

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the current code example is not working as expected as new failing fixture I added https://github.com/rectorphp/rector/pull/5627/commits/387385e1112801fc5837017d9169017b50c1a610 : 

https://github.com/rectorphp/rector/blob/362ebbea46592bd5e2eb5ec8534a6cbe38f302dc/rules/early-return/src/Rector/If_/ChangeAndIfToEarlyReturnRector.php#L65-L101

**Comment by samsonasik** [comment]
Oh, there is `skip_non_void` fixture which is invalid fixture based on code example:

https://github.com/rectorphp/rector/blob/362ebbea46592bd5e2eb5ec8534a6cbe38f302dc/rules/early-return/tests/Rector/If_/ChangeAndIfToEarlyReturnRector/Fixture/skip_non_void_return.php.inc#L3-L15

**Comment by samsonasik** [comment]
prove https://3v4l.org/F2Ft0 vs https://3v4l.org/gNBak -> same result.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
