### PR TITLE
Fixes #3448 : Fixes relative path link on dump-rectors generate class link documentation

### LINKED ISSUE #3448: Running dump-rectors (on Drupal Rector project) creates broken links for classes in documentation
# Bug Report

Based on these instructions: https://github.com/rectorphp/rector/pull/3265

I ran: `vendor/bin/rector dump-rectors drupal-rector/src/ > drupal-rector/docs/drupal_rector_rules.md`

And created this PR https://github.com/palantirnet/drupal-rector/pull/102

The result:
https://github.com/palantirnet/drupal-rector/blob/master/docs/drupal_rector_rules.md

But if you try clicking on any of the classes links you'll get 404 page.
Example for a broken link:
https://github.com/palantirnet/drupal-rector/blob/master/drupal-rector/src/Rector/Deprecation/BrowserTestBaseGetMockRector.php

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #3448

Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

### CODE REVIEW

**Comment by samsonasik** [comment]
verified in deep directory inside  for command:

```
mkdir -p docs/bar/baz && bin/rector dump-rectors > docs/bar/baz/foo.md
```

ezgif com-video-to-gif

**Comment by TomasVotruba** [comment]
Wow, thanks :+1: 

If you regenerate the docs for our repository, are there some changes?

```bash
composer docs
```

**Comment by samsonasik** [comment]
Yes, I've run `composer docs` and commited the doc changes

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
