### PR TITLE
Fixes #4229 Add property camel case naming rule

### LINKED ISSUE #4229: [Naming] Add property camel case naming rule
```diff
-private $some_property;
+private $someProperty;


// ...

-$this->some_property
+$this->someProperty
```

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I just tried to use fixture that property has initial value, and it removed : 

```diff
-    private $someProperty = 1;
+    private $someProperty;
```

Need to check if there is a way to keep existing value if initial property has value.

**Comment by samsonasik** [comment]
All checks have passed again 🎉 . I've added handle to keep existing inital value of property if any. 

@TomasVotruba it is ready for review.

**Review by TomasVotruba — COMMENTED** [review]
Thank you!

What about property that is in 3rd party code?
It should not be renamed.

**Comment by TomasVotruba** [comment]
Ah, I just checked and we already have this rule: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#underscoretocamelcasepropertynamerector

My bad, I'm sorry :facepalm: 

Could you check it's the expected behaviour?

**Comment by samsonasik** [comment]
`UnderscoreToCamelCasePropertyNameRector` seems already handle it, I'm closing it.

**Comment by TomasVotruba** [comment]
Thanks for checking

**Comment by dobryy** [comment]
> Ah, I just checked and we already have this rule: https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#underscoretocamelcasepropertynamerector
> 
> My bad, I'm sorry 
> 
> Could you check it's the expected behaviour?

I'm wondering that this rule renames `public` and `protected` properties, also it doesn't solve any type of conflict. Am I missing something?

**Comment by TomasVotruba** [comment]
> I'm wondering that this rule renames public and protected properties, also it doesn't solve any type of conflict. Am I missing something?

No, you're not. The feature is missing :) would you handle it?

> Also... don't we want to move this rule to the Naming set?

Good idea, go for it :+1:

**Comment by dobryy** [comment]
Ok, I'll check it.
At the moment, I'm finishing the decoupling of PropertyRenamer from one rule where everything is handled pretty well. So it shouldn't be a problem to apply for this rule as well.

**Comment by dobryy** [comment]
It looks like I won't get to https://github.com/rectorphp/rector/issues/4071 this week then :) or I'll get to it at the very end of the week.

**Comment by dobryy** [comment]
One more rule that doesn't handle anything https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#renamepropertyrector

**Comment by TomasVotruba** [comment]
> One more rule that doesn't handle anything

What do you mean? It's used here:

https://github.com/rectorphp/rector/blob/3442308bba6cfbb4d5e1a508dd8fe9c897a71419/config/set/cakephp34.php#L38-L43

**Comment by dobryy** [comment]
Sorry, I meant it also doesn't handle conflicts and could cause problems with public and protected properties but maybe for this particular rule it is okay because it is up to the developer what he is renaming.

**Comment by TomasVotruba** [comment]
I see. Could you create standalone issue so we have this knowledge one place?

**Pull request closed without merging**
