### PR TITLE
[PHP 8.0] Add ChangeSwitchToMatchRector

### PR DESCRIPTION
**Pull request by TomasVotruba**
Covers https://github.com/nikic/PHP-Parser/pull/672, https://wiki.php.net/rfc/match_expression_v2

```diff
 class SomeClass
 {
     public function run()
     {
-        $statement = switch ($this->lexer->lookahead['type']) {
-            case Lexer::T_SELECT:
-                $statement = $this->SelectStatement();
-                break;
-            default:
-                $this->syntaxError('SELECT, UPDATE or DELETE');
-                break;
-        }
+        $statement = match ($this->lexer->lookahead['type']) {
+            Lexer::T_SELECT => $this->SelectStatement(),
+            default => $this->syntaxError('SELECT, UPDATE or DELETE'),
+        };
     }
 }
```

Ref #3127

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I've just added separated jobs for:

- php-parser 4.6 - works 
- php-parser 4.7 - breaks

Everything else in the code is the same

**Comment by ondrejmirtes** [comment]
I probably know what this is about:

* Here's the phpstan/phpstan autoloader: https://github.com/phpstan/phpstan/blob/master/bootstrap.php
* It's used when you use `phpstan/phpstan` but use PHPStan not by running `vendor/phpstan/phpstan/phpstan` executable but by asking for some internal classes, like NodeScopeResolver or RuleTestCase.
* At some point this line will be executed:

```
$composerAutoloader = require 'phar://' . __DIR__ . '/phpstan.phar/vendor/autoload.php';
```

* Which means that potentially the PHP-Parser library from inside the PHAR will be loaded some time later.
* But it has to be this way as PHPStan internals also rely on PHP-Parser.
* My conclusion is that if a project uses PHPStan internals but also requires PHP-Parser on its own, the PHP-Parser has to be the same version as it's bundled in the PHPStan's PHAR.

I really don't know the way out of this, it's a hard problem.

**Comment by TomasVotruba** [comment]
Great! I came to exact same conclussion.

**Comment by TomasVotruba** [comment]
The only solution that worked for me in the past is to use the same php-parser as PHPStan does.
Last bug was with property promotion, so we had to wait till new version of phpstan uses 4.6. It does now, but there is already 4.7 with more breaks.

**Comment by ondrejmirtes** [comment]
I'll be releasing PHPStan 0.12.34 with PHP-Parser 4.7 later today 🚀

**Comment by TomasVotruba** [comment]
That's way over my expectations. Epic, thank you :clap: :heart:

**Comment by TomasVotruba** [comment]
condrejmirtes I can confirm 0.12.34 works purfectly! Thanks :clap:  :clap: :

**Comment by TomasVotruba** [comment]
@ondrejmirtes I've just updated Rector and can confirm 0.12.34 works purfectly! Thanks :clap:  :clap:

**Comment by TomasVotruba** [comment]
@ondrejmirtes I've just updated Rector and can confirm 0.12.34 works purfectly! Thanks :clap:  :clap:

**Comment by ondrejmirtes** [comment]
Cool :)

**Pull request merged**
