### PR TITLE
improvement - argument analyzer dynamic

### PR DESCRIPTION
**Pull request by mssimi**
I noticed ArgumentAnalyzer has methods like isFirstSomething, IsSecondSomething. I think we should generalize it. Check it and let me know what you think.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Nth is really unreadable. What about classic count?

**Comment by mssimi** [comment]
Do you mean method name or method param or both?:D

**Comment by TomasVotruba** [comment]
"Nth" for naming fo anything.

**Comment by mssimi** [comment]
I'm open for suggestions, but "isMethodCountArgument" sounds worse:D

**Comment by TomasVotruba** [comment]
Thank you Marek

**Pull request merged**
