### PR TITLE
[Downgrade PHP 7.3] Flexible Heredoc syntax

### LINKED ISSUE #4169: [Downgrade PHP 7.3] Flexible Heredoc syntax
# Feature Request

Downgrade new feature from PHP 7.3 to its equivalent PHP 7.2 code
 
## Diff 

```diff
-$query = <<<SQL
-    SELECT * 
-    FROM `table`
-    WHERE `column` = true;
-    SQL;
+$query = <<<SQL
+SELECT * 
+FROM `table`
+WHERE `column` = true;
+SQL;
```

### PR DESCRIPTION
**Pull request by quisse**
Closes https://github.com/rectorphp/rector/issues/4169

### CODE REVIEW

**Comment by quisse** [comment]
Am I missing something to make the test run?

**Comment by TomasVotruba** [comment]
Test run, the CI just stops after first failed unit test set.

The PHP 7.2 run fail on invalid syntax: https://github.com/rectorphp/rector/pull/4272/checks?check_run_id=1149824926#step:7:80

**Comment by quisse** [comment]
It is normal that the 7.2 unit test fails, because it can't work with the test case. The flexible heredoc/nowdoc is introduced in php 7.3.

**Comment by samsonasik** [comment]
You may need extract fixture to different directory, and use `AppendIterator` with php version check, for example https://github.com/symplify/symplify/blob/9e542c92ffeeef055c3bc75c37f4d7b37038a58a/packages/coding-standard/tests/Fixer/Naming/StandardizeHereNowDocKeywordFixer/StandardizeHereNowDocKeywordFixerTest.php#L24-L30

**Comment by samsonasik** [comment]
Test can be splitted into 2 files see https://github.com/symplify/symplify/tree/master/packages/coding-standard/tests/Fixer/Naming/StandardizeHereNowDocKeywordFixer once with `@requires PHP >= 7.3` docblock

**Comment by quisse** [comment]
@samsonasik Why should it be splitted up in 2 tests? Since the case can't work < php 7.3, isn't just adding the annotation sufficient?

**Comment by TomasVotruba** [comment]
Thank you, looks good :+1:

**Pull request merged**
