### PR TITLE
Fix NewToStaticCallRector documentation

### PR DESCRIPTION
**Pull request by RusiPapazov**
Fix arguments documentation for `Rector\Rector\New_\NewToStaticCallRector`

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This file is generated, so it has to be changed directly in `NewToStaticCallRector` class instead

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by RusiPapazov** [comment]
@TomasVotruba The question is: when is it generated? I updated the .md again but didn't push the commit, decided it's not needed as you said `instead`. But I still don't see the changes on the master branch's docs.

**Comment by TomasVotruba** [comment]
Manually now occasionally

**Pull request merged**
