### PR TITLE
Issue #5180 - add intl extension

### PR DESCRIPTION
**Pull request by HenkPoley**
https://github.com/rectorphp/rector/issues/5180#issuecomment-760100459

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @HenkPoley

**Comment by samsonasik** [comment]
Got error:

```bash

error: 'intl' does not exist

usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc
```

https://github.com/rectorphp/rector/runs/1701806223

**Comment by HenkPoley** [comment]
It appears it needs `docker-php-ext-configure intl`: https://github.com/docker-library/php/issues/974

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector/pull/5185

**Pull request merged**
