### PR TITLE
[Laravel] Add request() to injection

### PR DESCRIPTION
**Pull request by TomasVotruba**
## Before

```php
<?php

namespace App\Http\Controllers;

class WelcomeController extends Controller
{
    public function index()
    {
        return view('welcome', [
            'foo' => request()->get('foo'),
        ]);
    }
}
```

## After

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index(Request $request)
    {
        return view('welcome', [
            'foo' => $request->get('foo'),
        ]);
    }
}
```

cc @azdanov :)

### CODE REVIEW

**Comment by azdanov** [comment]
In case of `request()->get('foo');` there are no issues.

But I get problems with `request('foo')`, it gets transformed to `$request;`

**Comment by azdanov** [comment]
I think it would be better to use [`$request->input('foo');`](https://laravel.com/docs/5.8/requests#retrieving-input), here's an explanation https://laravel.com/api/5.8/Illuminate/Http/Request.html#method_get.

**Comment by TomasVotruba** [comment]
Thank you for detailed review. 

Could you send cases  that are failing now as  PR test cases to this branch?

**Comment by azdanov** [comment]
https://github.com/rectorphp/rector/pull/1177

**Comment by TomasVotruba** [comment]
That's matter of PHPStan upgrade. This feature alone works. My local tests passes.

Thanks for failing test cases :+1:

**Comment by mrpixeldream** [comment]
Are you sure it's related to PHPStan? How can PHPStan possibly let the test cases fail that worked before? Isn't PHPStan only relevant when being invoked manually?

**Comment by TomasVotruba** [comment]
I'm sure. It worked on 0.11.2, it doesn't on 0.11.3

Rector uses part of PHPStan it to analyse types: https://github.com/rectorphp/rector/blob/master/composer.json#L14

**Comment by azdanov** [comment]
Oh, now it makes sense. Usually, PHPStan is used as an outside tool.

**Comment by mrpixeldream** [comment]
Ah, I see, didn't know that. Tested locally with a pinned version of 0.11.2 and it works. Maybe we should pin the version then? I can submit a PR if you want.

**Comment by TomasVotruba** [comment]
Please do send the PR. I'm looking into the upgrade now, but it might take a while

**Pull request merged**
