### PR TITLE
Point to the new parser nodes docs URL

### PR DESCRIPTION
**Pull request by matthiasnoback**
This would make it easier to include the interface in the book, @TomasVotruba Would you agree to do it like this?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
The correct place now is actually:
https://github.com/rectorphp/php-parser-nodes-docs

I would not put shortened urls into code, as it remove the trust from the source. I wan't to know what I'm clicking at.

**Comment by matthiasnoback** [comment]
Okay, no problem. The new URL is shorter anyway, so we just might be lucky :)

**Comment by matthiasnoback** [comment]
I've updated this PR to change the URL instead

**Comment by TomasVotruba** [comment]
Pesonally, I would extend the width for code in book. Modify format if needed.
The native code we use on Github and codebases have now around 120 chars.

E.g. the line here before change has only 108 chars:

image


Reading anything
shorted is pretty
annoying and hard
to read :D 

And can drag 5 to
10 pages.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by matthiasnoback** [comment]
For sure, we didn't talk about it, but for me it's important that the book also works in print format. So we can actually provide print copies ;) But let's discuss this next time we meet!

**Comment by TomasVotruba** [comment]
I see, but print format should not force non-printed code to be unreadable. Maybe other way around... Yea, we should discuss it :)

**Pull request merged**
