### PR TITLE
Readme and docs should be included in rector installation

### PR DESCRIPTION
**Pull request by samsonasik**
I think Readme and docs files should be included in rector installation so user doesn't need to look at github repo to read it.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by olivernybroe** [comment]
Hi @samsonasik,

I think we should consider at least not including `docs` folder or at least not `docs/images`, as images are often a big sin when talking filesize.

**Comment by samsonasik** [comment]
@olivernybroe the readme is consuming `docs/images` for displaying logos, so probably `docs/images` still needed. 

About `phpstan-for-rector.neon`, @TomasVotruba is the `phpstan-for-rector.neon` a fallback when there is no `Option::PHPSTAN_FOR_RECTOR_PATH` defined?

**Comment by olivernybroe** [comment]
@samsonasik Yes, we use it for images in the readme. However I don't think it hurts the readme that much that we don't display the images when browsing the readme through vendor folder.
I think that's better than adding 1MB of extra package size, for logos. 

We could potentially also just change the images to be url's to main branch instead? That way they will show locally if you have a internet connection.

**Comment by samsonasik** [comment]
Thank you. I've updated to use URL for images location, re-add back `docs` to `.gitattributes`.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you both :+1: 

> About phpstan-for-rector.neon, @TomasVotruba is the phpstan-for-rector.neon a fallback when there is no Option::PHPSTAN_FOR_RECTOR_PATH defined?

This config is needed only in our repository here. Each project can to defined their own config if needed.

**Pull request merged**
