### PR TITLE
Pass string to FullyQualified instead of ::class

### LINKED ISSUE #5596: InitializeDefaultEntityCollectionRector suggests \RectorPrefix20210215\Doctrine\Common\Collections\ArrayCollection
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.9.29              |
| Installed as   | prefixed Rector                           |

It suggests this code:
```
    ---------- begin diff ----------
--- Original
+++ New
@@ @@

     public function __construct(string $journeyId, string $ticketProviderId)
     {
+        $this->validation = new \RectorPrefix20210215\Doctrine\Common\Collections\ArrayCollection();
    ----------- end diff -----------

```

I think this is caused by https://github.com/rectorphp/rector/blob/1561e108c075ca7bc0ff7c87b858a9389625cdf8/rules/doctrine-code-quality/src/Rector/Class_/InitializeDefaultEntityCollectionRector.php#L153

Maybe it shouldn't reference the imported `ArrayCollection::class` but use just a FQCN string?

### PR DESCRIPTION
**Pull request by ruudk**
Fixes #5596

### CODE REVIEW

**Comment by ruudk** [comment]
Can we somehow prevent this from happening again? Because nobody thinks about prefixing when contributing new rectors.

**Comment by TomasVotruba** [comment]
Thanks :+1: 

The first choice would be PHPStan rule

**Comment by ruudk** [comment]
Do you know if there is such a rule?

**Comment by TomasVotruba** [comment]
If it would, I'd look for it here: https://github.com/symplify/phpstan-rules/blob/master/docs/rules_overview.md

There is similar for method calls: https://github.com/symplify/phpstan-rules/blob/master/docs/rules_overview.md#requirestringargumentinmethodcallrule

It can be duplicated and instead of `MethodCall` the `New_` node should be used.

**Pull request merged**
