### PR TITLE
Return also explicitly mixed types in IdentifierTypeMapper

### PR DESCRIPTION
**Pull request by ComiR**
For explicit `MixedType`s it was trying to resolve a type but ultimately fail and return an implicit `MixedType`.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi,

we need a failing test fixture to cover this change.
What exact rule broke? On what exact PHP code?

**Comment by ComiR** [comment]
sth. like 
```php
/**
 * @return mixed[]
 */
function foo(): array {}
```
would return a `MixedType(false)` instead of a `MixedType(true)` when called like
```php
$returnTagValueNode = $phpDocInfo->getReturnTagValue();
$this->staticTypeMapper->mapPHPStanPhpDocTypeToPHPStanType($returnTagValueNode, $functionLike);
```

**Comment by TomasVotruba** [comment]
Good! Could you add it to the tests?

**Comment by ComiR** [comment]
The failing tests mention some kind of token - so I don't think they fail because of sth. in the code.

I hope this test is sufficient 😃

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
