### PR TITLE
Failing test case for Aliased class not found #5259

### PR DESCRIPTION
**Pull request by lulco**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
The class must really exists. Otherwise it's just a string, as any missing class is in PHP.

**Comment by lulco** [comment]
I don’t think it is true. Without alias it works

**Comment by TomasVotruba** [comment]
That's how type resolution works here. It's not related to alias

**Comment by lulco** [comment]
I rewrote the test case. I used existing class `NowString` and reuse whole fixture.php.inc with only one change - I added alias to NowString class. Result is the same: without alias it works, with alias it doesn't. For me it is the proof that it is related to alias.

**Comment by samsonasik** [comment]
@lulco I cherry-picked your commit at PR https://github.com/rectorphp/rector/pull/5408

**Pull request closed without merging**
