### PR TITLE
Make `AnnotateThrowablesRector` continue on unhandled node types.

### PR DESCRIPTION
**Pull request by Aerendir**

### CODE REVIEW

**Comment by Aerendir** [comment]
The branch is based on commit fcec6e30 and anyway fails 😓

**Comment by TomasVotruba** [comment]
There is problem with code coverage only, skip it

**Comment by Aerendir** [comment]
Ok, then it is ready to merge.

I simply removed two throws and returned a value anyway.

This way the rector doesn’t stop (it was for dev purposes only) and continues its work.

Later I will start implementing the other node types...

There is the problem of accessing the called function/method doc block, but I will describe the problem extensively in another issue/PR.

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
