### PR TITLE
[Naming] Skip RenameForeachValueVariableToMatchExprVariableRector on empty singular value name result

### LINKED ISSUE #5977: Incorrect behavior of RenameForeachValueVariableToMatchExprVariableRector when the expression variable is predefined variable
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/18d18b97-037e-4fec-9323-6f304e970b34

```php
<?php

final class DemoFile
{
    public function run()
    {
        foreach ($_FILES as $file) {
            dump($file);
        }
    }
}
```

### Responsible rules

* `RenameForeachValueVariableToMatchExprVariableRector`

## Expected Behavior

Nothing needs to be changed

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5977

### CODE REVIEW

**Comment by zingimmick** [comment]
Thanks for catching this!

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
