### PR TITLE
[Naming] Various Improve RenameForeachValueVariableToMatchExprVariableRector 

### PR DESCRIPTION
**Pull request by samsonasik**
- skip repetitive single prefix.
- skip non-Variable and non-PropertyFetch.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
