### PR TITLE
[EarlyReturn]  Add ReturnBinaryAndToEarlyReturnRector

### LINKED ISSUE #4869: [EarlyReturn] Single return of && && to ealry returns
- new rule for `EarlyReturn` set
- name, e.g. `ReturnBinaryAndToEarlyReturnRector` 
 
## Diff 

```diff
 class SomeClass
 {
     public function accept($something, $somethignElse)
     {
-        return $something && $somethignElse;
+ 		 if (! $something) {
+            return false;
+        }
+        return $somethignElse;
     }
 }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #4869

### CODE REVIEW

**Comment by samsonasik** [comment]
weird error in github action: 

```bash
1) Rector\EarlyReturn\Tests\Rector\Return_\ReturnBinaryAndToEarlyReturnRector\ReturnBinaryAndToEarlyReturnRectorTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Undefined offset: 43

phar:///home/runner/work/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:221
```

It is working ok in my local dev:

Screen Shot 2020-12-17 at 2 59 59 AM

**Comment by samsonasik** [comment]
refactored without `removeNode()`

**Comment by samsonasik** [comment]
weird, still error in github action event without `removeNode()` usage

**Comment by samsonasik** [comment]
refactored with use local variable for collect `If_` collection

**Comment by samsonasik** [comment]
PHPStan error, seems caused by latest symplify:

```bash
[WARNING] Internal error: Internal error: Argument 1 passed to                 
           Symplify\PHPStanRules\Rules\CheckConstantExpressionDefinedInConstruct
           OrSetupRule::isNotInsideClassMethodDirectly() must implement         
           interface PhpParser\Node, null given, called in                      
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/CheckConstantExpressionDefinedInConstructOrSetupRule.php on line  
           81 in file                                                           
           /home/runner/work/rector/rector/rules/php72/src/Rector/FuncCall/Abstr
           actConvertToAnonymousFunctionRector.php                              
           Run PHPStan with --debug option and post the stack trace to:         
           https://github.com/phpstan/phpstan/issues/new            
           
[WARNING] Child process error (exit code 1): PHP Notice:  Undefined property:  
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/NoDuplicatedShortClassNameRule.php on line 57                     
           Notice: Undefined property:                                          
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/NoDuplicatedShortClassNameRule.php on line 57                     
           PHP Notice:  Undefined property:                                     
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/NoSuffixValueObjectClassRule.php on line 46                       
           Notice: Undefined property:                                          
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/NoSuffixValueObjectClassRule.php on line 46                       
           PHP Notice:  Undefined property:                                     
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/PrefixAbstractClassRule.php on line 49                            
           Notice: Undefined property:                                          
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/PrefixAbstractClassRule.php on line 49                            
           PHP Notice:  Undefined property:                                     
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/CheckClassNamespaceFollowPsr4Rule.php on line 60                  
           Notice: Undefined property:                                          
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/CheckClassNamespaceFollowPsr4Rule.php on line 60                  
           PHP Notice:  Undefined property:                                     
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/AbstractSymplifyRule.php on line 166                              
           Notice: Undefined property:                                          
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/AbstractSymplifyRule.php on line 166                              
           PHP Notice:  Undefined property:                                     
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/SeeAnnotationToTestRule.php on line 158                           
           Notice: Undefined property:                                          
           PhpParser\Node\Stmt\Class_::$namespacedName in                       
           /home/runner/work/rector/rector/vendor/symplify/phpstan-rules/src/Rul
           es/SeeAnnotationToTestRule.php on line 158   
```

**Comment by samsonasik** [comment]
Finally, All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by TomasVotruba** [comment]
The next step is to enable it in `early-return.php` set. Could you handle it?

**Comment by samsonasik** [comment]
yes https://github.com/rectorphp/rector/pull/4915

**Pull request merged**
