### PR TITLE
[Phalcon 4.0] init

### PR DESCRIPTION
**Pull request by TomasVotruba**
# This is Huge

See https://docs.phalcon.io/4.0/en/upgrade#general-notes

image

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ping @ruudboon

**Comment by niden** [comment]
I need to send you the correct graphic but great job!!!!

**Comment by ruudboon** [comment]
@TomasVotruba This is awesome!!!  Gonna test it tomorrow!

**Comment by niden** [comment]
https://github.com/phalcon/assets/tree/master/phalcon/mockup FYI

**Comment by TomasVotruba** [comment]
@niden Updated :+1:

**Pull request merged**
