### PR TITLE
 [Downgrade PHP 7.4] Skip DowngradeNumericLiteralSeparatorRector on value contains + char

### LINKED ISSUE #4401: DowngradeNumericLiteralSeparatorRector must not convert 1.0 to 1
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.8.21       |
| Installed as   | composer dependency                      |

Running rector `DowngradeNumericLiteralSeparatorRector` (to replace `1_000` with `1000`) on an `int` such as `1.0` currently replaces it with `1`:

```diff
-if (0 > $beta = $beta ?? 1.0) {
+if (0 > $beta = $beta ?? 1) {
```

It must not.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/715a5acd-2f03-4db3-a7f2-d9e0a5d02ba5#result

## Expected Behaviour

Do not replace `1.0` with `1`, keep it as it is.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #4401

### CODE REVIEW

**Comment by leoloso** [comment]
This solves the specific case of the max float, but it doesn't fix the underlying problem: that the rule should not be applied on numbers using the scientific notation. However, that cannot be fixed currently.

**Review by leoloso — APPROVED** [review]

**Comment by samsonasik** [comment]
@leoloso do you think it needs check the string version, and verify if the value contains like `+` character?

**Comment by leoloso** [comment]
Exactly. But that can't be done since the number you're dealing with is already a float, and PHP-Parser doesn't preserve the parsed number, where you can find the `+`

**Comment by samsonasik** [comment]
Fixed now 🎉 , the solution is clone the node for tested against `+` so it doesn't use original behaviour.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
