### PR TITLE
Add PHPUnit 8.0 changes

### LINKED ISSUE #798: PHPUnit 8.0 level
- ref https://github.com/sebastianbergmann/phpunit/commit/1c17ac33af234045ff27ba92433be8d9e5884c0a
- https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-8.0.md

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #798

### CODE REVIEW

**Comment by Slamdunk** [comment]
I think this PR misses `$this->assertInternalType('null', $var);` to `$this->assertNull($var);`

**Comment by TomasVotruba** [comment]
It might. Care for adding it with PR?

**Comment by Slamdunk** [comment]
No I'm sorry, I dedicate my few energies to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4144 :disappointed:

**Comment by TomasVotruba** [comment]
I see, no troubles.

Thanks for informing me

**Comment by TomasVotruba** [comment]
:heavy_check_mark: 

https://github.com/rectorphp/rector/commit/1d8deff30a9ce13fa34a0724dd6c4e8c91939c9c

**Pull request merged**
