### PR TITLE
[fixtures] Enable validate-fixture-skip-naming check

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the vendor/bin/easy-testing file is not found, any clue?

**Comment by samsonasik** [comment]
it seems need full path vendor bin vendor/symplify/easy-testing/bin/easy-testing validate-fixture-skip-naming rules tests

**Comment by samsonasik** [comment]
@TomasVotruba there seems false positives, eg: 

```
 ! [NOTE] The file "rules/naming/tests/Rector/Class_/RenamePropertyToMatchTypeRector/Fixture/keep_param.php.inc" should 
 !        drop the "skip" prefix   
```

The `keep_param.php.inc` file doesn't has `skip` prefix, has before after `-----`, so `drop the "skip" prefix` notice is invalid.

**Comment by samsonasik** [comment]
it seems the wording message need to be updated, as `keep` and `skip` is allowed when no `-----`, and no need when no `------`, so the message should be:

```
 ! [NOTE] The file "rules/naming/tests/Rector/Class_/RenamePropertyToMatchTypeRector/Fixture/keep_param.php.inc" should 
 !        drop the "skip/keep" prefix   
```

**Comment by samsonasik** [comment]
it seems the is no `'-----'` check yet:

```
 ! [NOTE] The file "rules/php-spec-to-phpunit/tests/Rector/Variable/PhpSpecToPHPUnitRector/Fixture/keep_method.php.inc" 
 !        should drop the "skip/keep" prefix         
```

for fixture content:

```php
<?php

declare(strict_types=1);

namespace Rector\PhpSpecToPHPUnit\Tests\Rector\Variable\PhpSpecToPHPUnitRector\Fixture;

final class KeepMethod
{

}
```

**Comment by samsonasik** [comment]
implemented, require https://github.com/symplify/symplify/pull/2736 to be merged first.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clap: :clap:

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
