### PR TITLE
[Symfony 5.2] Upgrade Definition/Alias::setPrivate to setPublic

### PR DESCRIPTION
**Pull request by samsonasik**
part of #4824

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba change `Definition/Alias`::`setPrivate()` to `Definition/Alias`::`setPublic()` need to include parameter change to pass boolean not the passed value, any param value changer that can be used for it?

**Comment by TomasVotruba** [comment]
There is couple of rules that change default value, look for "change arg value".

It might require a new rule. What do you think?

**Comment by samsonasik** [comment]
New rule seems ok. I will try create new rule for it.

**Comment by samsonasik** [comment]
I've added `DefinitionSetPrivateToSetPublicRector` for it.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
