### PR TITLE
Callable type

### PR DESCRIPTION
**Pull request by TomasVotruba**
Covers #2881 

@snapshotpl This is the best I could do. The return `mixed` is removed, as its default value and it would polute all the callables by default.

### CODE REVIEW

**Comment by snapshotpl** [comment]
Looks like missing mixed is a problem... https://github.com/phpstan/phpstan/issues/3008

**Comment by snapshotpl** [comment]
@TomasVotruba did you see that ^^ ?

**Comment by TomasVotruba** [comment]
tl;dr; I don't have time for this part anymore, but I can guide you in the possible fix

**Comment by snapshotpl** [comment]
@TomasVotruba waiting for hints :)

**Comment by TomasVotruba** [comment]
You need to detect format of original content in:
https://github.com/rectorphp/rector/blob/3dd1e7ca6929301fe5889d2bb721c3eba426f7d4/packages/attribute-aware-php-doc/src/Ast/Type/AttributeAwareCallableTypeNode.php

Then modify __toString() method to reflect it

**Pull request merged**
