### PR TITLE
[Php72] Handle usage super global on CreateFunctionToAnonymousFunctionRector

### LINKED ISSUE #5769: Incorrect behavior of CreateFunctionToAnonymousFunctionRector
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-master@4758dad             |
| Installed as   | composer dependency / prefixed Rector                           |

I have used this rector configuration file to update all the deprecated _create_function_ uses.
I have used the following rector init code

```
<?php

use Rector\Core\Configuration\Option;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector;

return static function (ContainerConfigurator $containerConfigurator) {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/src',
    ]);

    $services = $containerConfigurator->services();
    $services->set(CreateFunctionToAnonymousFunctionRector::class);
};
```

As result rector has replaced sections as

```
function register_skin_deactivation_hook_function($code, $function) {
    $GLOBALS[ 'register_skin_deactivation_hook_function' . $code] = $function;
    $fn=create_function('$skin', ' call_user_func($GLOBALS["register_skin_deactivation_hook_function' . $code . '"]); delete_option("skin_is_activated_' . $code. '");');
    add_action( 'switch_s' , $fn );
}
```
with

```
function register_skin_deactivation_hook_function($code, $function) {
    $GLOBALS[ 'register_skin_deactivation_hook_function' . $code] = $function;
    $fn=function ($skin) use ($GLOBALS, $code) {
            call_user_func($GLOBALS["register_skin_deactivation_hook_function{$code}"]);
            delete_option("skin_is_activated_{$code}");
    };
    add_action( 'switch_s' , $fn );
}
```

That isn't a correct syntax and it causes
**Fatal error: Cannot use auto-global as lexical variable**

on

`$fn=function ($skin) use ($GLOBALS, $code) {`

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5769

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
It should be included, just not in `use (...)`

See https://3v4l.org/YtHgU

**Comment by samsonasik** [comment]
I will try.

**Comment by samsonasik** [comment]
implemented https://github.com/rectorphp/rector/pull/5778/commits/7d3886979992c6fe33e35dc1d8f79c1c8a9468ed

**Comment by TomasVotruba** [comment]
Thanks. I wonder if same rule applies for $_POST/$_GET etc. Could you verify?

**Comment by samsonasik** [comment]
the `$_POST` is handled via `ReservedKeywordAnalyzer` service https://github.com/rectorphp/rector/pull/5778/commits/6447c811caa82e1bfc30cd130f58d868d3886147

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
