### PR TITLE
Added SplitIfsRector

### PR DESCRIPTION
**Pull request by jeroensmit**
Might be what @JanMikes meant in #1107

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Might be covered by https://github.com/rectorphp/rector/blob/master/packages/SOLID/src/Rector/If_/RemoveAlwaysElseRector.php already

Could you check?

We'll close #1107 then

**Comment by TomasVotruba** [comment]
I see there are few more cases you've added.
Could you add them to `RemoveAlwaysElseRector` and `RemoveAlwaysElseRectorTest`?

Thanks

**Comment by jeroensmit** [comment]
Yes, I will.

**Comment by TomasVotruba** [comment]
Thanks! Feel free to open a new PR

**Pull request closed without merging**
