### PR TITLE
Fix extra commas in EventInfosFactory

### PR DESCRIPTION
**Pull request by JanMikes**

### CODE REVIEW

**Comment by vasilvestre** [comment]
https://github.com/rectorphp/rector/issues/1040
Extra comma in function call is valid with 7.3 but composer requirement is 7.2

**Comment by TomasVotruba** [comment]
> In addition, you could add no_trailing_comma_in_list_call at php cs fixer before 7.3 :)

Does is separate list and functions args?

**Comment by vasilvestre** [comment]
no_trailing_comma_in_list_call
Remove trailing commas in list function calls.

I don't know much more than what doc is telling

**Comment by TomasVotruba** [comment]
I just tried it on this case and it ignored it.

**Pull request merged**
