### PR TITLE
Support latest php-parser

### PR DESCRIPTION
**Pull request by nexxai**
Update composer.json to pin to latest version of php-parser

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by sandermarechal** [comment]
Why is the version pinned to the patch version begin with? It makes installing rector a hassle. I have php-parser 4.10.2 in my project. I cannot install rector at the moment because composer won't downgrade. Why not use php-parser 4.10.* or even ^4.10?

**Comment by TomasVotruba** [comment]
Because of constant BC breaks that happen with Rector, php-parser and phpstan trio.

See e.g.
https://github.com/nikic/PHP-Parser/issues/714

**Comment by TomasVotruba** [comment]
Also https://github.com/rectorphp/rector/issues/3718, 
https://github.com/rectorphp/rector/issues/3643, https://github.com/rectorphp/rector/issues/3537

**Pull request merged**
