### PR TITLE
[mysql-to-mysqli] Handle second parameter on mysqli_query swap for sql - conn variable 

### LINKED ISSUE #4977: [mysql-to-mysqli] Not renaming mysql_query to mysqli_query on legacy PHP5 code
https://github.com/rectorphp/rector/blob/9433616c634e3e2513112dd441b8163dc12f6767/config/set/mysql-to-mysqli.php#L39

Here it says it should swap the parameters and then rename the function. mysql_query, mysql_real_escape_string are two that are not being renamed.

On another note, second parameter in most of these functions are optional, which is connection handler. Rector doesn't correctly work in this situation. I understand that this is because of rector not being able to find the $connection, but shouldn't this be stated somewhere in the execution/documentation of the set?

### PR DESCRIPTION
**Pull request by samsonasik**
Close #5000 Fixes #4977

### CODE REVIEW

**Comment by samsonasik** [comment]
seems cause another error, I will recheck.

**Comment by samsonasik** [comment]
The issue is because the check is rely on variable named `connection`:

https://github.com/rectorphp/rector/blob/20588b78a08b241b1830867dfbdc24febc1cec4c/rules/mysql-to-mysqli/src/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector.php#L176

which it will be unreliable if variable changed to `conn` or `con` or `koneksi`

**Comment by samsonasik** [comment]
fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
