### PR TITLE
[EarlyReturn] Add ReturnAfterToEarlyBreakRector

### LINKED ISSUE #5218: [EarlyReturn] Foreach with continue, then return to early return
```diff
-$pathOK = false;

foreach ($pathConstants as $allowedPath) {
    if ($dirPath == $allowedPath) {
-        $pathOK = true;
+		 return false; 
-        break;
    }
}

-return $pathOK;
+return false;
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #5218

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the current `BetterNodeFinder::findFirstPrevious()` seems invalid as when it locate parent, the filter also filtered next of current node that located as already in parent. 

I will try to fix the `BetterNodeFinder::findFirstPrevious()` to able to correctly locate findFirstPrevious for the following use case locate `$pathOK` before foreach:

```php
        $pathOK = false;
        foreach ($pathConstants as $allowedPath) {
            if ($dirPath == $allowedPath) {
                $pathOK = true;
                break;
            }
        }

        return $pathOK;
```

**Comment by samsonasik** [comment]
I keep existing `BetterNodeFinder::findFirstPrevious()` as changing it break other tests. 
I added new method `BetterNodeFinder::findFirstPreviousOfNode()` for to get previous node in previous node.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
