### PR TITLE
added get started to readme

### PR DESCRIPTION
**Pull request by C0pyR1ght**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks!

How useful did you find those 2 repositories?

**Comment by C0pyR1ght** [comment]
The demo project was a very good starting point for a first and quick way of trying rector on a sample codebase.
haven't had enough time to dive deeper into the training repo yet. But I will do that in the next few days.
@staabm

**Comment by TomasVotruba** [comment]
Thanks for letting me know :+1: .

If you find anthing to update at rector/demo, that might help others, just send PR there. I want it to be as easy to understand as possible and I know I'm too deep to make it clear for newcomers.

**Comment by staabm** [comment]
Great job @C0pyR1ght !

**Pull request merged**
