### PR TITLE
[DeadCode] Add RemoveNullPropertyInitializationRector to dead-code set

### PR DESCRIPTION
**Pull request by TomasVotruba**
(before `RemoveDeadInitializationRector`)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ref #1870

**Comment by UFTimmy** [comment]
Maybe this is the wrong place to ask this, but why are nulls on property declarations considered bad? I know I can remove the rector from applying if I don't like, but I was hoping to get a better understanding of why it's considered bad first.

I don't typically use them, but with PHP 7.4 there is a difference between not initialized and null, so for some properties I do initialize them to null so you don't get the accessing an uninitialized field error.

**Comment by TomasVotruba** [comment]
They're not bad at all. 

They're as useful as first line here:

```php
$value = [];
$value = [
  $this->getSome();
];
```

**Comment by TomasVotruba** [comment]
For typed properties it's a different case, see: https://github.com/rectorphp/rector/blob/master/rules/php74/src/Rector/Property/TypedPropertyRector.php

If they're in conflict and this rule breaks PHP 7.4 code, please open an issue. That's a bug.

**Pull request merged**
