### PR TITLE
[DeadCode] Failing fixture remove unused variable assign in expr

### PR DESCRIPTION
**Pull request by samsonasik**
#5152

### CODE REVIEW

**Comment by samsonasik** [comment]
fixed 🎉

**Comment by brucealdridge** [comment]
> fixed 🎉

Thank you! If I understood more how it worked and could get the dev env setup I would start fixing my own bugs!

**Comment by samsonasik** [comment]
After some thinking, I think assignment inside Expr should be skipped, as it may cause side effect.

**Comment by samsonasik** [comment]
I've updated to skip change when parent of assign is not dedicated `Expression` statement

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
