### PR TITLE
Clear apt and composer cache after installing

### PR DESCRIPTION
**Pull request by t3easy**

### CODE REVIEW

**Review by JanMikes — APPROVED** [review]
LGTM, looking forward to see results, how many MBs we will save :-)

**Comment by t3easy** [comment]
> LGTM, looking forward to see results, how many MBs we will save :-) 

@JanMikes To save a lot more the composer commands could be in one step and then the installed app could be copied over to the final image. No composer dependencies... and switch to an alpine based images.

**Comment by JanMikes** [comment]
Well, it depends. From my own experience, it makes development and debugging in such image very inconvenient.

Since we do not deploy the image to cloud or anywhere and it is only targeted for CI or local environment, resulting image size is not such pain here.

**Comment by JanMikes** [comment]
We could in the end have multistage docker build or multiple dockerfiles - 1) as official distribution of rector in docker 2) for rector development itself

**Comment by t3easy** [comment]
@JanMikes It saved 19 MB compressed. Is a first step ;)

https://hub.docker.com/layers/rector/rector/0.9.7/images/sha256-56cd13047e0f3dccab368d20555cf0f8b9185ba552f7d0acce15b5f3995e7daa?context=explore
https://hub.docker.com/layers/rector/rector/0.9.8/images/sha256-725b4a1d0d221b0fe3345b61b2d3b5fe54a665564b54bfb5593192c6b8330204?context=explore

https://hub.docker.com/layers/rector/rector/0.9.7/images/sha256-56cd13047e0f3dccab368d20555cf0f8b9185ba552f7d0acce15b5f3995e7daa?context=explore
https://hub.docker.com/layers/rector/rector/0.9.8/images/sha256-725b4a1d0d221b0fe3345b61b2d3b5fe54a665564b54bfb5593192c6b8330204?context=explore

**Pull request merged**
