### PR TITLE
added support post class move rename in XML files

### PR DESCRIPTION
**Pull request by vladyslavstartsev**
XML support will be useful for cases like `DoctrineGedmoToKnplabsRector`

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks!

Are you able to add test case too so we have this feature covered for 100 %?

Basically an XML version of this fixture: https://github.com/rectorphp/rector/pull/3565/files

**Comment by vladyslavstartsev** [comment]
Like this one?

Am I correct?

**Comment by TomasVotruba** [comment]
Perfect :clap:

**Comment by TomasVotruba** [comment]
Thank you for such a fast contribution

**Comment by vladyslavstartsev** [comment]
@TomasVotruba don't like to rebase things :laughing: :rofl:

**Pull request merged**
