### PR TITLE
[FrameworkBundle] Add test for services alias as well

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@mssimi Alias is not the proble. We need more details on this

**Comment by mssimi** [comment]
Example project [here](https://github.com/mssimi/rector-example)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by TomasVotruba** [comment]
It seem the trait is the problm

**Comment by mssimi** [comment]
We already had trait problem before, but I cannot remember where:D

**Comment by TomasVotruba** [comment]
It was fixed before, but PHPStan kind of skips including traits. I though it's not important if PHPStan doesn't do it, so I didn't add them.

Now I see it IS important, so re-added them :) 

Short story: believe your guts and keep tests 1:1 :D

**Pull request merged**
