### PR TITLE
Bug fix: ReservedKeywordAnalyzer should add _SESSION to NATIVE_VARIABLE_NAMES

### PR DESCRIPTION
**Pull request by samsonasik**
Add missing handling for `$_SESSION` to ReservedKeywordAnalyzer

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba  failure checks seems unrelated. 

1. phpstan error, can be ignored for now?

```php
#Do not use scalar or array as constructor parameter\. Use ParameterProvider service instead#
```

2. cs error ConfiguredCodeSample new line ( should be in separate PR )

It is ready for review.

**Comment by TomasVotruba** [comment]
> 1. phpstan error, can be ignored for now?

Sure, add it ignored errors.

> 2. cs error ConfiguredCodeSample new line ( should be in separate PR )

Could you include it here, so we have passing CI without red?

<br>

Tests are failing because new php-parser & phpstan.

Could I ask you to create a PR to update them first, so we have passing tests?

- https://github.com/nikic/PHP-Parser/releases/tag/v4.10.0
- https://github.com/phpstan/phpstan/releases/tag/0.12.43

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector/pull/4264 to update php-parser and phpstan to latest version.

**Comment by samsonasik** [comment]
Running cs-fix locally seems fine:

```
➜  rector git:(bug-fix-reservedkeyword-analyzer) composer fix-cs
> vendor/bin/ecs check --fix --ansi

[OK] No errors found. Great job - your code is shiny in style!                 
                                                                                
> vendor/bin/ecs check-markdown README.md --fix --ansi
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                         
 [OK] No errors found. Great job - your code is shiny in style!                 
```

I will try to push to this repo instead.

**Comment by samsonasik** [comment]
Closing, re-created directly to this repo at #4265

**Pull request closed without merging**
