### PR TITLE
Test exclude_paths weird behaviour

### PR DESCRIPTION
**Pull request by JanMikes**

### CODE REVIEW

**Comment by JanMikes** [comment]
In this case it is weird that `'Exception.php'` is in excluded paths but even SomeException.php is ignored.

**Comment by TomasVotruba** [comment]
Rebased on master...

**Comment by TomasVotruba** [comment]
CI build passes: https://travis-ci.org/rectorphp/rector/builds/612473224?utm_source=github_status&utm_medium=notification


If it still fails on your machine, could try same build on Travis just with Mac.

**Comment by TomasVotruba** [comment]
image

**Pull request closed without merging**
