### PR TITLE
Skip RenameMethodRector on interface wildcard used

### PR DESCRIPTION
**Pull request by ruudk**
I realized that I did not provide the test case in #5564 correctly as I was running it in my project.

By changing the existing test it fails again.

Why? Because `OtherWildcardSubscriber` does match the wildcard `*WildcardSubscriber`. That one does not implement an interface.

Because `$this->classManipulator->hasParentMethodOrInterface` just tries to find the first matching class that matches the wildcard, it checks that one always. And since that one does not implement an interface, it will allow refactoring. While it shouldn't.

That means that the implementation in #5622 is not correct (and naive). 

I'm trying to think of a way how to do this.

/cc @samsonasik

### CODE REVIEW

**Comment by ruudk** [comment]
I think the best thing to do would be to rollback #5622 as it does not what it should do.

**Comment by ruudk** [comment]
I'll work on a PR to see if I can implement it. /cc @samsonasik

**Comment by ruudk** [comment]
Master is broken... partial fix here > https://github.com/rectorphp/rector/pull/5623

@samsonasik What do you think of this approach?

**Comment by samsonasik** [comment]
I think new fixture is better instead of modifying existing fixture to keep existing behaviour.

**Comment by ruudk** [comment]
Yeah, not sure. As the old one did not solve my use case + I reverted the PR.

**Comment by ruudk** [comment]
Ran this on my project and now it finally works without issues 🎉

**Comment by ruudk** [comment]
@TomasVotruba What do you think?

**Comment by TomasVotruba** [comment]
I'm waiting for CI to be green, so I can review & merge.

Also, could you separate the fixture into new file? Now it's extending an existing one and it's harder to see what is going on.

**Comment by TomasVotruba** [comment]
Surpassed by https://github.com/rectorphp/rector/pull/5693#issuecomment-787034952

**Pull request closed without merging**
