### PR TITLE
Fix sentence.

### PR DESCRIPTION
**Pull request by dereuromark**
Small grammar thing.
Not sure about `doing` part though.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks

**Comment by dereuromark** [comment]
> Turns old method call with specfici type

also contains a typo on https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#general

**Comment by dereuromark** [comment]
And https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#getandsettomethodcallrector
```
services:
    Rector\Rector\MagicDisclosure\GetAndSetToMethodCallRector:
        SomeContainer:
            set: addService
```
wouldnt that be

    +$container->addService("someService", $someService);

instead of 

    +$container->setService("someService", $someService);

**Comment by TomasVotruba** [comment]
https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#general

This file is generated from particular Rectora and getDescription() method.

Feel free to send PR for those typos there.

**Pull request merged**
