### PR TITLE
[ConstFetchResolver] Support keyword in uppercase

### PR DESCRIPTION
**Pull request by carusogabriel**
Following #231

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Nice!

Could you add here one line to the test as well?

**Comment by carusogabriel** [comment]
The class of tests is `packages/NodeValueResolver/tests/NodeValueResolverTest`? :thinking:

**Comment by TomasVotruba** [comment]
Yep

**Comment by carusogabriel** [comment]
I'm going to. If anything blows up, I call you :fire:

**Comment by TomasVotruba** [comment]
Nice, thanks!

**Pull request merged**
