### PR TITLE
Removed duplicit package sebastian/diff from composer.json

### PR DESCRIPTION
**Pull request by lulco**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
It seems used:

```php
use SebastianBergmann\Diff...
```

And just once in `composer.jsonh

**Comment by lulco** [comment]
Where it is used? Ok we can remove it from require-dev section. IDE marks it as diplicated

**Comment by TomasVotruba** [comment]
Here: https://github.com/rectorphp/rector/search?q=use+SebastianBergmann

I see it now. Better remove the dev one.

I thought composer validate is handling this one by default, but it needs a `--strict` flag:

```bash
composer validate --strict
```

Could you update the CI here too to avoid it next time?

**Comment by lulco** [comment]
Is there any test in CI for composer validate? I don't see any. Or should I add another one?

**Comment by lulco** [comment]
Removed package from require-dev and composer validate test added

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
