### PR TITLE
[PSR-4 Split] Split interfaces and traits as well

### PR DESCRIPTION
**Pull request by JanMikes**

### CODE REVIEW

**Comment by JanMikes** [comment]
@TomasVotruba before this MR files containing interface and/or trait with class would fail splitting - it deleted non class nodes and did not move them to new files.

**Comment by TomasVotruba** [comment]
Better create new test instead of deleting one

**Comment by JanMikes** [comment]
Fixed 😉

**Comment by JanMikes** [comment]
@TomasVotruba can we merge? 😉

**Comment by TomasVotruba** [comment]
Sure, nice test btw, simple and clear :+1:

**Pull request merged**
