### PR TITLE
Skip test case with named constructor

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi,  thanks for the test.

When do you plan to send a fix, so we can merge it

**Comment by snapshotpl** [comment]
I don't have enough knowledge about rector implementation. I just want to point you what is wrong.

**Comment by TomasVotruba** [comment]
I see.

Do you want to learn that so you can contribute feature as well?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback

**Pull request closed without merging**
