### PR TITLE
[CodingStyle] Failing test case for cannot change this to self 

### PR DESCRIPTION
**Pull request by samsonasik**
for class extends PHPUnit\Framework\TestCase

### CODE REVIEW

**Comment by samsonasik** [comment]
fixed 🎉

**Comment by samsonasik** [comment]
self to this seems still not covered

**Comment by samsonasik** [comment]
Finally fixed  :tada:

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
